// dataSerieA.js — Serie A + Serie B

const SERIE_A_TEAMS = [
    { id: 'int', name: 'Inter Milan',    short: 'INT', color: '#010E80', colorAlt: '#000000', prestige: 90, budget: Math.round(Math.pow(Math.max(0,90-40),2)*45000), stadium: 'Giuseppe Meazza',          capacity: 75923, squad: [
        makePlayer(pid(), 'Yann Sommer',             'GK', 35, 87, 'SUI'),
        makePlayer(pid(), 'Antonio Di Gennaro',      'GK', 35, 71, 'ITA'),
        makePlayer(pid(), 'Denzel Dumfries',         'RB', 28, 83, 'NED'),
        makePlayer(pid(), 'Matteo Darmian',          'RB', 34, 79, 'ITA'),
        makePlayer(pid(), 'Francesco Acerbi',        'CB', 36, 83, 'ITA'),
        makePlayer(pid(), 'Stefan de Vrij',          'CB', 32, 83, 'NED'),
        makePlayer(pid(), 'Alessandro Bastoni',      'CB', 25, 86, 'ITA'),
        makePlayer(pid(), 'Carlos Augusto',          'LB', 25, 81, 'BRA'),
        makePlayer(pid(), 'Federico Dimarco',        'LB', 26, 84, 'ITA'),
        makePlayer(pid(), 'Nicolo Barella',          'CM', 27, 88, 'ITA'),
        makePlayer(pid(), 'Hakan Calhanoglu',        'CDM',30, 86, 'TUR'),
        makePlayer(pid(), 'Henrikh Mkhitaryan',      'CM', 35, 82, 'ARM'),
        makePlayer(pid(), 'Davide Frattesi',         'CM', 24, 81, 'ITA'),
        makePlayer(pid(), 'Lautaro Martinez',        'ST', 26, 89, 'ARG'),
        makePlayer(pid(), 'Marcus Thuram',           'ST', 27, 85, 'FRA'),
        makePlayer(pid(), 'Marko Arnautovic',        'ST', 35, 78, 'AUT'),
        makePlayer(pid(), 'Alexis Sanchez',          'CAM',35, 79, 'CHI'),
        makePlayer(pid(), 'Juan Cuadrado',           'RW', 36, 77, 'COL'),
        makePlayer(pid(), 'Kristjan Asllani',        'CM', 22, 76, 'ALB'),
    ]},
    { id: 'juv', name: 'Juventus',       short: 'JUV', color: '#000000', colorAlt: '#FFFFFF', prestige: 88, budget: Math.round(Math.pow(Math.max(0,88-40),2)*45000), stadium: 'Allianz Stadium',          capacity: 41507, squad: [
        makePlayer(pid(), 'Wojciech Szczesny',       'GK', 34, 84, 'POL'),
        makePlayer(pid(), 'Mattia Perin',            'GK', 31, 78, 'ITA'),
        makePlayer(pid(), 'Danilo',                  'RB', 33, 81, 'BRA'),
        makePlayer(pid(), 'Timothy Weah',            'RW', 24, 76, 'USA'),
        makePlayer(pid(), 'Gleison Bremer',          'CB', 27, 86, 'BRA'),
        makePlayer(pid(), 'Daniele Rugani',          'CB', 30, 76, 'ITA'),
        makePlayer(pid(), 'Federico Gatti',          'CB', 26, 79, 'ITA'),
        makePlayer(pid(), 'Alex Sandro',             'LB', 33, 79, 'BRA'),
        makePlayer(pid(), 'Andrea Cambiaso',         'LB', 24, 82, 'ITA'),
        makePlayer(pid(), 'Manuel Locatelli',        'CDM',26, 82, 'ITA'),
        makePlayer(pid(), 'Nicolo Fagioli',          'CM', 23, 79, 'ITA'),
        makePlayer(pid(), 'Weston McKennie',         'CM', 25, 78, 'USA'),
        makePlayer(pid(), 'Adrien Rabiot',           'CM', 29, 82, 'FRA'),
        makePlayer(pid(), 'Filip Kostic',            'LW', 31, 80, 'SRB'),
        makePlayer(pid(), 'Federico Chiesa',         'RW', 26, 83, 'ITA'),
        makePlayer(pid(), 'Dusan Vlahovic',          'ST', 24, 87, 'SRB'),
        makePlayer(pid(), 'Arkadiusz Milik',         'ST', 30, 80, 'POL'),
        makePlayer(pid(), 'Moise Kean',              'ST', 24, 78, 'ITA'),
        makePlayer(pid(), 'Kenan Yildiz',            'CAM',19, 78, 'TUR'),
    ]},
    { id: 'acm', name: 'AC Milan',       short: 'ACM', color: '#FB090B', colorAlt: '#000000', prestige: 87, budget: Math.round(Math.pow(Math.max(0,87-40),2)*45000), stadium: 'Giuseppe Meazza',          capacity: 75923, squad: [
        makePlayer(pid(), 'Mike Maignan',            'GK', 28, 89, 'FRA'),
        makePlayer(pid(), 'Marco Sportiello',        'GK', 32, 74, 'ITA'),
        makePlayer(pid(), 'Davide Calabria',         'RB', 27, 80, 'ITA'),
        makePlayer(pid(), 'Alessandro Florenzi',     'RB', 33, 77, 'ITA'),
        makePlayer(pid(), 'Fikayo Tomori',           'CB', 26, 84, 'ENG'),
        makePlayer(pid(), 'Malick Thiaw',            'CB', 23, 81, 'GER'),
        makePlayer(pid(), 'Matteo Gabbia',           'CB', 27, 77, 'ITA'),
        makePlayer(pid(), 'Theo Hernandez',          'LB', 26, 87, 'FRA'),
        makePlayer(pid(), 'Ismael Bennacer',         'CDM',26, 83, 'ALG'),
        makePlayer(pid(), 'Rade Krunic',             'CM', 30, 78, 'BIH'),
        makePlayer(pid(), 'Yunus Musah',             'CM', 21, 79, 'USA'),
        makePlayer(pid(), 'Tommaso Pobega',          'CM', 25, 76, 'ITA'),
        makePlayer(pid(), 'Christian Pulisic',       'RW', 25, 82, 'USA'),
        makePlayer(pid(), 'Samuel Chukwueze',        'RW', 25, 79, 'NGA'),
        makePlayer(pid(), 'Rafael Leao',             'LW', 24, 87, 'POR'),
        makePlayer(pid(), 'Olivier Giroud',          'ST', 37, 82, 'FRA'),
        makePlayer(pid(), 'Luka Jovic',              'ST', 26, 77, 'SRB'),
        makePlayer(pid(), 'Tijjani Reijnders',       'CM', 25, 82, 'NED'),
        makePlayer(pid(), 'Noah Okafor',             'LW', 24, 78, 'SUI'),
    ]},
    { id: 'nap', name: 'Napoli',         short: 'NAP', color: '#087FC6', colorAlt: '#FFFFFF', prestige: 86, budget: Math.round(Math.pow(Math.max(0,86-40),2)*45000), stadium: 'Diego Armando Maradona',   capacity: 54726, squad: [
        makePlayer(pid(), 'Alex Meret',              'GK', 27, 84, 'ITA'),
        makePlayer(pid(), 'Pierluigi Gollini',       'GK', 30, 74, 'ITA'),
        makePlayer(pid(), 'Giovanni Di Lorenzo',     'RB', 30, 84, 'ITA'),
        makePlayer(pid(), 'Alessandro Zanoli',       'RB', 23, 73, 'ITA'),
        makePlayer(pid(), 'Amir Rrahmani',           'CB', 30, 82, 'KVX'),
        makePlayer(pid(), 'Juan Jesus',              'CB', 33, 76, 'BRA'),
        makePlayer(pid(), 'Natan',                   'CB', 22, 77, 'BRA'),
        makePlayer(pid(), 'Mathias Olivera',         'LB', 27, 79, 'URU'),
        makePlayer(pid(), 'Mario Rui',               'LB', 33, 78, 'POR'),
        makePlayer(pid(), 'Stanislav Lobotka',       'CDM',29, 85, 'SVK'),
        makePlayer(pid(), 'Piotr Zielinski',         'CM', 30, 84, 'POL'),
        makePlayer(pid(), 'Andre-Frank Anguissa',    'CM', 28, 83, 'CMR'),
        makePlayer(pid(), 'Matteo Politano',         'RW', 30, 79, 'ITA'),
        makePlayer(pid(), 'Giacomo Raspadori',       'ST', 24, 80, 'ITA'),
        makePlayer(pid(), 'Khvicha Kvaratskhelia',   'LW', 23, 88, 'GEO'),
        makePlayer(pid(), 'Victor Osimhen',          'ST', 25, 88, 'NGA'),
        makePlayer(pid(), 'Giovanni Simeone',        'ST', 29, 76, 'ARG'),
        makePlayer(pid(), 'Jesper Lindstrom',        'CM', 24, 76, 'DEN'),
        makePlayer(pid(), 'Elif Elmas',              'CM', 24, 78, 'MKD'),
    ]},
    { id: 'rom', name: 'AS Roma',        short: 'ROM', color: '#9B0000', colorAlt: '#F5C400', prestige: 82, budget: Math.round(Math.pow(Math.max(0,82-40),2)*45000), stadium: 'Olimpico',                 capacity: 72698, squad: [
        makePlayer(pid(), 'Rui Patricio',            'GK', 36, 81, 'POR'),
        makePlayer(pid(), 'Mile Svilar',             'GK', 24, 77, 'BEL'),
        makePlayer(pid(), 'Rick Karsdorp',           'RB', 29, 78, 'NED'),
        makePlayer(pid(), 'Zeki Celik',              'RB', 28, 76, 'TUR'),
        makePlayer(pid(), 'Gianluca Mancini',        'CB', 27, 81, 'ITA'),
        makePlayer(pid(), 'Chris Smalling',          'CB', 34, 82, 'ENG'),
        makePlayer(pid(), 'Evan Ndicka',             'CB', 24, 80, 'FRA'),
        makePlayer(pid(), 'Leonardo Spinazzola',     'LB', 31, 79, 'ITA'),
        makePlayer(pid(), 'Rasmus Kristensen',       'RB', 27, 75, 'DEN'),
        makePlayer(pid(), 'Leandro Paredes',         'CDM',30, 80, 'ARG'),
        makePlayer(pid(), 'Lorenzo Pellegrini',      'CM', 28, 83, 'ITA'),
        makePlayer(pid(), 'Edoardo Bove',            'CM', 22, 76, 'ITA'),
        makePlayer(pid(), 'Houssem Aouar',           'CM', 26, 78, 'FRA'),
        makePlayer(pid(), 'Paulo Dybala',            'CAM',30, 85, 'ARG'),
        makePlayer(pid(), 'Romelu Lukaku',           'ST', 31, 84, 'BEL'),
        makePlayer(pid(), 'Andrea Belotti',          'ST', 30, 78, 'ITA'),
        makePlayer(pid(), 'Stephan El Shaarawy',     'LW', 32, 77, 'ITA'),
        makePlayer(pid(), 'Tommaso Baldanzi',        'CAM',21, 75, 'ITA'),
    ]},
    { id: 'laz', name: 'Lazio',          short: 'LAZ', color: '#87CEEB', colorAlt: '#FFFFFF', prestige: 78, budget: Math.round(Math.pow(Math.max(0,78-40),2)*45000), stadium: 'Olimpico',                 capacity: 72698, squad: [
        makePlayer(pid(), 'Ivan Provedel',           'GK', 30, 82, 'ITA'),
        makePlayer(pid(), 'Christos Mandas',         'GK', 23, 74, 'GRE'),
        makePlayer(pid(), 'Manuel Lazzari',          'RB', 30, 79, 'ITA'),
        makePlayer(pid(), 'Adam Marusic',            'RB', 32, 78, 'MNE'),
        makePlayer(pid(), 'Alessio Romagnoli',       'CB', 29, 82, 'ITA'),
        makePlayer(pid(), 'Nicolo Casale',           'CB', 26, 78, 'ITA'),
        makePlayer(pid(), 'Mario Gila',              'CB', 22, 77, 'ESP'),
        makePlayer(pid(), 'Elseid Hysaj',            'LB', 30, 75, 'ALB'),
        makePlayer(pid(), 'Luca Pellegrini',         'LB', 24, 76, 'ITA'),
        makePlayer(pid(), 'Matteo Guendouzi',        'CDM',25, 81, 'FRA'),
        makePlayer(pid(), 'Mattia Cataldi',          'CDM',29, 77, 'ITA'),
        makePlayer(pid(), 'Luis Alberto',            'CM', 32, 83, 'ESP'),
        makePlayer(pid(), 'Marco Vecino',            'CM', 32, 77, 'URU'),
        makePlayer(pid(), 'Felipe Anderson',         'RW', 31, 81, 'BRA'),
        makePlayer(pid(), 'Mattia Zaccagni',         'LW', 29, 82, 'ITA'),
        makePlayer(pid(), 'Ciro Immobile',           'ST', 34, 84, 'ITA'),
        makePlayer(pid(), 'Pedro',                   'ST', 36, 80, 'ESP'),
        makePlayer(pid(), 'Taty Castellanos',        'ST', 25, 77, 'ARG'),
    ]},
    { id: 'ata', name: 'Atalanta',       short: 'ATA', color: '#1C83C5', colorAlt: '#000000', prestige: 80, budget: Math.round(Math.pow(Math.max(0,80-40),2)*45000), stadium: 'Gewiss Stadium',           capacity: 21300, squad: [
        makePlayer(pid(), 'Juan Musso',              'GK', 30, 82, 'ARG'),
        makePlayer(pid(), 'Marco Rossi',             'GK', 26, 72, 'ITA'),
        makePlayer(pid(), 'Davide Zappacosta',       'RB', 32, 77, 'ITA'),
        makePlayer(pid(), 'Hans Hateboer',           'RB', 30, 77, 'NED'),
        makePlayer(pid(), 'Berat Djimsiti',          'CB', 30, 80, 'ALB'),
        makePlayer(pid(), 'Jose Palomino',           'CB', 34, 78, 'ARG'),
        makePlayer(pid(), 'Giorgio Scalvini',        'CB', 20, 80, 'ITA'),
        makePlayer(pid(), 'Sead Kolasinac',          'LB', 31, 77, 'BIH'),
        makePlayer(pid(), 'Matteo Ruggeri',          'LB', 22, 74, 'ARG'),
        makePlayer(pid(), 'Marten de Roon',          'CDM',33, 80, 'NED'),
        makePlayer(pid(), 'Teun Koopmeiners',        'CM', 26, 85, 'NED'),
        makePlayer(pid(), 'Ederson',                 'CM', 25, 80, 'BRA'),
        makePlayer(pid(), 'Mario Pasalic',           'CM', 29, 79, 'CRO'),
        makePlayer(pid(), 'Ademola Lookman',         'RW', 26, 83, 'NGA'),
        makePlayer(pid(), 'Aleksey Miranchuk',       'LW', 28, 78, 'RUS'),
        makePlayer(pid(), 'Gianluca Scamacca',       'ST', 25, 82, 'ITA'),
        makePlayer(pid(), 'Luis Muriel',             'ST', 33, 78, 'COL'),
        makePlayer(pid(), 'Charles De Ketelaere',    'CAM',23, 80, 'BEL'),
    ]},
    { id: 'fio', name: 'Fiorentina',     short: 'FIO', color: '#4B0082', colorAlt: '#FFFFFF', prestige: 73, budget: Math.round(Math.pow(Math.max(0,73-40),2)*45000), stadium: 'Artemio Franchi',          capacity: 43147, squad: [
        makePlayer(pid(), 'Pietro Terracciano',      'GK', 34, 79, 'ITA'),
        makePlayer(pid(), 'Olivier Christensen',     'GK', 26, 72, 'DEN'),
        makePlayer(pid(), 'Dodo',                    'RB', 26, 79, 'BRA'),
        makePlayer(pid(), 'Lorenzo Venuti',          'RB', 29, 72, 'ITA'),
        makePlayer(pid(), 'Nikola Milenkovic',       'CB', 26, 82, 'SRB'),
        makePlayer(pid(), 'Lucas Martinez Quarta',   'CB', 28, 79, 'ARG'),
        makePlayer(pid(), 'Pietro Ranieri',          'CB', 22, 74, 'ITA'),
        makePlayer(pid(), 'Cristiano Biraghi',       'LB', 31, 78, 'ITA'),
        makePlayer(pid(), 'Fabiano Parisi',          'LB', 24, 75, 'ITA'),
        makePlayer(pid(), 'Rolando Mandragora',      'CDM',27, 77, 'ITA'),
        makePlayer(pid(), 'Arthur',                  'CM', 28, 78, 'BRA'),
        makePlayer(pid(), 'Antonin Barak',           'CM', 29, 76, 'CZE'),
        makePlayer(pid(), 'Giacomo Bonaventura',     'CM', 35, 78, 'ITA'),
        makePlayer(pid(), 'Jonathan Ikone',          'RW', 26, 76, 'FRA'),
        makePlayer(pid(), 'Andrea Sottil',           'LW', 24, 74, 'ITA'),
        makePlayer(pid(), 'Nico Gonzalez',           'RW', 26, 81, 'ARG'),
        makePlayer(pid(), 'M Bala Nzola',            'ST', 27, 76, 'ANG'),
        makePlayer(pid(), 'Lucas Beltran',           'ST', 23, 76, 'ARG'),
        makePlayer(pid(), 'Josip Brekalo',           'LW', 26, 75, 'CRO'),
    ]},
    { id: 'tor', name: 'Torino',         short: 'TOR', color: '#8B0000', colorAlt: '#FFFFFF', prestige: 67, budget: Math.round(Math.pow(Math.max(0,67-40),2)*45000), stadium: 'Olimpico Grande Torino',   capacity: 27958, squad: [
        makePlayer(pid(), 'Vanja Milinkovic-Savic',  'GK', 27, 76, 'SRB'),
        makePlayer(pid(), 'Luca Gemello',            'GK', 26, 65, 'ITA'),
        makePlayer(pid(), 'Wilfried Singo',          'RB', 23, 74, 'CIV'),
        makePlayer(pid(), 'Mergim Vojvoda',          'RB', 28, 70, 'KVX'),
        makePlayer(pid(), 'Alessandro Buongiorno',   'CB', 24, 76, 'ITA'),
        makePlayer(pid(), 'Perr Schuurs',            'CB', 23, 75, 'NED'),
        makePlayer(pid(), 'Koffi Djidji',            'CB', 30, 72, 'CIV'),
        makePlayer(pid(), 'Ricardo Rodriguez',       'LB', 31, 75, 'SUI'),
        makePlayer(pid(), 'Valentino Lazaro',        'LB', 27, 72, 'AUT'),
        makePlayer(pid(), 'Samuele Ricci',           'CDM',22, 76, 'ITA'),
        makePlayer(pid(), 'Karol Linetty',           'CM', 28, 72, 'POL'),
        makePlayer(pid(), 'Nemanja Radonjic',        'LW', 27, 72, 'SRB'),
        makePlayer(pid(), 'Yann Karamoh',            'RW', 26, 71, 'FRA'),
        makePlayer(pid(), 'Aleksey Miranchuk',       'CM', 28, 74, 'RUS'),
        makePlayer(pid(), 'Antonio Sanabria',        'ST', 27, 74, 'PAR'),
        makePlayer(pid(), 'Duvan Zapata',            'ST', 32, 77, 'COL'),
        makePlayer(pid(), 'Ivan Ilic',               'CM', 22, 73, 'SRB'),
        makePlayer(pid(), 'Pietro Pellegri',         'ST', 23, 70, 'ITA'),
    ]},
    { id: 'bol', name: 'Bologna',        short: 'BOL', color: '#990000', colorAlt: '#003DA5', prestige: 70, budget: Math.round(Math.pow(Math.max(0,70-40),2)*45000), stadium: "Renato Dall'Ara",          capacity: 36452, squad: [
        makePlayer(pid(), 'Lukasz Skorupski',        'GK', 32, 77, 'POL'),
        makePlayer(pid(), 'Nicola Bagnolini',        'GK', 24, 64, 'ITA'),
        makePlayer(pid(), 'Stefan Posch',            'RB', 26, 74, 'AUT'),
        makePlayer(pid(), 'Gabriele Corbo',          'RB', 21, 69, 'ITA'),
        makePlayer(pid(), 'Jhon Lucumi',             'CB', 25, 75, 'COL'),
        makePlayer(pid(), 'Adama Soumaoro',          'CB', 30, 73, 'FRA'),
        makePlayer(pid(), 'Federico Ravaglia',       'GK', 24, 64, 'ITA'),
        makePlayer(pid(), 'Charalampos Lykogiannis', 'LB', 29, 72, 'GRE'),
        makePlayer(pid(), 'Riccardo Calafiori',      'LB', 22, 75, 'ITA'),
        makePlayer(pid(), 'Remo Freuler',            'CM', 31, 77, 'SUI'),
        makePlayer(pid(), 'Lewis Ferguson',          'CM', 24, 74, 'SCO'),
        makePlayer(pid(), 'Nicolas Dominguez',       'CM', 25, 72, 'ARG'),
        makePlayer(pid(), 'Oussama El Azzouzi',      'CM', 22, 71, 'MAR'),
        makePlayer(pid(), 'Joshua Zirkzee',          'ST', 23, 77, 'NED'),
        makePlayer(pid(), 'Riccardo Orsolini',       'RW', 26, 75, 'ITA'),
        makePlayer(pid(), 'Alexis Saelemaekers',     'RW', 25, 75, 'BEL'),
        makePlayer(pid(), 'Dan Ndoye',               'LW', 23, 73, 'SUI'),
        makePlayer(pid(), 'Victor Kristiansen',      'LB', 21, 72, 'DEN'),
    ]},
    { id: 'udi', name: 'Udinese',        short: 'UDI', color: '#000000', colorAlt: '#FFFFFF', prestige: 63, budget: Math.round(Math.pow(Math.max(0,63-40),2)*45000), stadium: 'Dacia Arena',              capacity: 25144, squad: [
        makePlayer(pid(), 'Marco Silvestri',         'GK', 31, 74, 'ITA'),
        makePlayer(pid(), 'Maduka Okoye',            'GK', 24, 69, 'NGA'),
        makePlayer(pid(), 'Nehuen Perez',            'RB', 23, 72, 'ARG'),
        makePlayer(pid(), 'Brandon Soppy',           'RB', 21, 69, 'FRA'),
        makePlayer(pid(), 'Rodrigo Becao',           'CB', 28, 74, 'BRA'),
        makePlayer(pid(), 'Jaka Bijol',              'CB', 25, 73, 'SVN'),
        makePlayer(pid(), 'Adam Masina',             'LB', 30, 71, 'MAR'),
        makePlayer(pid(), 'Destiny Udogie',          'LB', 21, 74, 'ITA'),
        makePlayer(pid(), 'Tolgay Arslan',           'CDM',31, 70, 'GER'),
        makePlayer(pid(), 'Lazar Samardzic',         'CM', 21, 75, 'SRB'),
        makePlayer(pid(), 'Sandi Lovric',            'CM', 24, 72, 'SVN'),
        makePlayer(pid(), 'Roberto Pereyra',         'CM', 33, 74, 'ARG'),
        makePlayer(pid(), 'Gerard Deulofeu',         'RW', 29, 75, 'ESP'),
        makePlayer(pid(), 'Florian Thauvin',         'RW', 31, 73, 'FRA'),
        makePlayer(pid(), 'Isaac Success',           'LW', 27, 71, 'NGA'),
        makePlayer(pid(), 'Beto',                    'ST', 25, 75, 'POR'),
        makePlayer(pid(), 'Lorenzo Lucca',           'ST', 23, 72, 'ITA'),
        makePlayer(pid(), 'Ola Aina',                'RB', 27, 71, 'NGA'),
    ]},
    { id: 'gen', name: 'Genoa',          short: 'GEN', color: '#C8102E', colorAlt: '#003DA5', prestige: 62, budget: Math.round(Math.pow(Math.max(0,62-40),2)*45000), stadium: 'Luigi Ferraris',           capacity: 36685, squad: [
        makePlayer(pid(), 'Josep Martinez',          'GK', 25, 74, 'ESP'),
        makePlayer(pid(), 'Nicola Leali',            'GK', 30, 67, 'ITA'),
        makePlayer(pid(), 'Silvan Hefti',            'RB', 26, 71, 'SUI'),
        makePlayer(pid(), 'Radu Dragusin',           'CB', 22, 71, 'ROU'),
        makePlayer(pid(), 'Johan Vasquez',           'CB', 25, 69, 'MEX'),
        makePlayer(pid(), 'Andrea Masiello',         'CB', 36, 67, 'ITA'),
        makePlayer(pid(), 'Aaron Martin',            'LB', 25, 70, 'ESP'),
        makePlayer(pid(), 'Nikola Maksimovic',       'CB', 32, 70, 'SRB'),
        makePlayer(pid(), 'Morten Frendrup',         'CDM',22, 71, 'DEN'),
        makePlayer(pid(), 'Ruslan Malinovskyi',      'CM', 30, 74, 'UKR'),
        makePlayer(pid(), 'Milan Badelj',            'CM', 34, 72, 'CRO'),
        makePlayer(pid(), 'Caleb Ekuban',            'LW', 27, 70, 'GHA'),
        makePlayer(pid(), 'Kelvin Yeboah',           'ST', 22, 69, 'GHA'),
        makePlayer(pid(), 'Junior Messias',          'RW', 32, 71, 'BRA'),
        makePlayer(pid(), 'Mateo Retegui',           'ST', 24, 73, 'ITA'),
        makePlayer(pid(), 'Andrea Pinamonti',        'ST', 24, 72, 'ITA'),
        makePlayer(pid(), 'Anass Ankeye',            'CM', 24, 68, 'SEN'),
        makePlayer(pid(), 'Albert Gudmundsson',      'RW', 26, 76, 'ISL'),
    ]},
    { id: 'emp', name: 'Empoli',         short: 'EMP', color: '#0066CC', colorAlt: '#FFFFFF', prestige: 60, budget: Math.round(Math.pow(Math.max(0,60-40),2)*45000), stadium: 'Carlo Castellani',         capacity: 16284, squad: [
        makePlayer(pid(), 'Guglielmo Vicario',       'GK', 26, 75, 'ITA'),
        makePlayer(pid(), 'Devis Vasquez',           'GK', 26, 66, 'COL'),
        makePlayer(pid(), 'Tyronne Ebuehi',          'RB', 27, 68, 'NGA'),
        makePlayer(pid(), 'Lorenzo Tonelli',         'CB', 33, 68, 'ITA'),
        makePlayer(pid(), 'Sebastiano Luperto',      'CB', 26, 69, 'ITA'),
        makePlayer(pid(), 'Ardian Ismajli',          'CB', 25, 70, 'ALB'),
        makePlayer(pid(), 'Fabiano Parisi',          'LB', 22, 71, 'ITA'),
        makePlayer(pid(), 'Simone Bastoni',          'LB', 25, 69, 'ITA'),
        makePlayer(pid(), 'Filippo Bandinelli',      'CM', 28, 68, 'ITA'),
        makePlayer(pid(), 'Liam Henderson',          'CM', 26, 69, 'SCO'),
        makePlayer(pid(), 'Emmanuel Ekong',          'CM', 25, 68, 'NGA'),
        makePlayer(pid(), 'Tommaso Baldanzi',        'CAM',20, 72, 'ITA'),
        makePlayer(pid(), 'Nicolo Cambiaghi',        'RW', 22, 70, 'ITA'),
        makePlayer(pid(), 'Francesco Caputo',        'ST', 36, 70, 'ITA'),
        makePlayer(pid(), 'Andrea Pinamonti',        'ST', 24, 71, 'ITA'),
        makePlayer(pid(), 'Nedim Bajrami',           'CM', 24, 70, 'SUI'),
        makePlayer(pid(), 'Jacopo Fazzini',          'CAM',20, 68, 'ITA'),
        makePlayer(pid(), 'Petar Stojanovic',        'RB', 26, 68, 'SVN'),
    ]},
    { id: 'mon', name: 'Monza',          short: 'MON', color: '#CC0000', colorAlt: '#FFFFFF', prestige: 63, budget: Math.round(Math.pow(Math.max(0,63-40),2)*45000), stadium: 'U-Power Stadium',          capacity: 18568, squad: [
        makePlayer(pid(), 'Michele Di Gregorio',     'GK', 25, 75, 'ITA'),
        makePlayer(pid(), 'Stefano Cragno',          'GK', 29, 71, 'ITA'),
        makePlayer(pid(), 'Pedro Pedro',             'RB', 26, 71, 'ESP'),
        makePlayer(pid(), 'Armando Izzo',            'CB', 31, 72, 'ITA'),
        makePlayer(pid(), 'Pablo Mari',              'CB', 30, 73, 'ESP'),
        makePlayer(pid(), 'Luca Caldirola',          'CB', 32, 70, 'ITA'),
        makePlayer(pid(), 'Carlos Augusto',          'LB', 24, 74, 'BRA'),
        makePlayer(pid(), 'Marlon Santos',           'CB', 27, 70, 'BRA'),
        makePlayer(pid(), 'Roberto Gagliardini',     'CDM',29, 72, 'ITA'),
        makePlayer(pid(), 'Stefano Sensi',           'CM', 28, 74, 'ITA'),
        makePlayer(pid(), 'Matteo Pessina',          'CM', 26, 74, 'ITA'),
        makePlayer(pid(), 'Andrea Colpani',          'CM', 24, 72, 'ITA'),
        makePlayer(pid(), 'Gianluca Caprari',        'RW', 29, 74, 'ITA'),
        makePlayer(pid(), 'Dany Mota Carvalho',      'ST', 24, 71, 'POR'),
        makePlayer(pid(), 'Patrick Ciurria',         'RW', 28, 71, 'ITA'),
        makePlayer(pid(), 'Valentin Carboni',        'CAM',18, 70, 'ARG'),
        makePlayer(pid(), 'Luca Marrone',            'CDM',31, 68, 'ITA'),
        makePlayer(pid(), 'Milan Djuric',            'ST', 33, 70, 'BIH'),
    ]},
    { id: 'fro', name: 'Frosinone',      short: 'FRO', color: '#FFCC00', colorAlt: '#003DA5', prestige: 57, budget: Math.round(Math.pow(Math.max(0,57-40),2)*45000), stadium: 'Benito Stirpe',            capacity: 16227, squad: [
        makePlayer(pid(), 'Stefano Turati',          'GK', 22, 70, 'ITA'),
        makePlayer(pid(), 'Federico Ravaglia',       'GK', 24, 65, 'ITA'),
        makePlayer(pid(), 'Nadir Zortea',            'RB', 24, 68, 'ITA'),
        makePlayer(pid(), 'Luca Monterisi',          'CB', 23, 66, 'ITA'),
        makePlayer(pid(), 'Matias Lulic',            'CB', 29, 66, 'BIH'),
        makePlayer(pid(), 'Giorgio Cittadini',       'CB', 25, 66, 'ITA'),
        makePlayer(pid(), 'Jeremy Karev',            'LB', 22, 66, 'FRA'),
        makePlayer(pid(), 'Pawel Dawidowicz',        'CB', 27, 70, 'POL'),
        makePlayer(pid(), 'Marco Brescianini',       'CM', 24, 68, 'ITA'),
        makePlayer(pid(), 'Mateusz Klich',           'CM', 33, 70, 'POL'),
        makePlayer(pid(), 'Francesco Gelli',         'CM', 27, 66, 'ITA'),
        makePlayer(pid(), 'Luca Mazzitelli',         'CM', 29, 68, 'ITA'),
        makePlayer(pid(), 'Matteo Garritano',        'LW', 30, 68, 'ITA'),
        makePlayer(pid(), 'Matias Soule',            'RW', 20, 72, 'ARG'),
        makePlayer(pid(), 'Roberto Insigne',         'LW', 30, 67, 'ITA'),
        makePlayer(pid(), 'Walid Cheddira',          'ST', 26, 69, 'MAR'),
        makePlayer(pid(), 'Tommaso Ciofani',         'ST', 36, 65, 'ITA'),
    ]},
    { id: 'lec', name: 'Lecce',          short: 'LEC', color: '#CC0000', colorAlt: '#F5C400', prestige: 59, budget: Math.round(Math.pow(Math.max(0,59-40),2)*45000), stadium: 'Via del Mare',             capacity: 31533, squad: [
        makePlayer(pid(), 'Wladimiro Falcone',       'GK', 28, 73, 'ITA'),
        makePlayer(pid(), 'Branimir Kalaica',        'GK', 22, 62, 'CRO'),
        makePlayer(pid(), 'Valentin Gendrey',        'RB', 24, 69, 'FRA'),
        makePlayer(pid(), 'Antonino Gallo',          'LB', 23, 68, 'ITA'),
        makePlayer(pid(), 'Frederic Baschirotto',    'CB', 28, 71, 'ITA'),
        makePlayer(pid(), 'Santiago Gigot',          'CB', 27, 70, 'ARG'),
        makePlayer(pid(), 'Marin Pongracic',         'CB', 26, 71, 'CRO'),
        makePlayer(pid(), 'Ylber Ramadani',          'CDM',25, 70, 'ALB'),
        makePlayer(pid(), 'Joan Gonzalez',           'CDM',22, 68, 'ESP'),
        makePlayer(pid(), 'Alexis Blin',             'CM', 27, 69, 'FRA'),
        makePlayer(pid(), 'Thorge Hazard',           'CM', 21, 68, 'GER'),
        makePlayer(pid(), 'Remi Oudin',              'RW', 27, 69, 'FRA'),
        makePlayer(pid(), 'Roberto Almqvist',        'RW', 24, 67, 'SWE'),
        makePlayer(pid(), 'Lameck Banda',            'LW', 22, 68, 'ZAM'),
        makePlayer(pid(), 'Gabriel Strefezza',       'RW', 27, 70, 'BRA'),
        makePlayer(pid(), 'Nikola Krstovic',         'ST', 23, 71, 'MNE'),
        makePlayer(pid(), 'Lorenzo Colombo',         'ST', 22, 69, 'ITA'),
        makePlayer(pid(), 'Panagiotis Retsos',       'CB', 24, 68, 'GRE'),
    ]},
    { id: 'cag', name: 'Cagliari',       short: 'CAG', color: '#990000', colorAlt: '#003DA5', prestige: 60, budget: Math.round(Math.pow(Math.max(0,60-40),2)*45000), stadium: 'Sardegna Arena',           capacity: 16000, squad: [
        makePlayer(pid(), 'Boris Radunovic',         'GK', 28, 71, 'SRB'),
        makePlayer(pid(), 'Simone Scuffet',          'GK', 27, 70, 'ITA'),
        makePlayer(pid(), 'Nahitan Nandez',          'RB', 28, 75, 'URU'),
        makePlayer(pid(), 'Raoul Bellanova',         'RB', 23, 72, 'ITA'),
        makePlayer(pid(), 'Giorgio Altare',          'CB', 26, 70, 'ITA'),
        makePlayer(pid(), 'Sebastian Walukiewicz',   'CB', 23, 70, 'POL'),
        makePlayer(pid(), 'Matija Nastasic',         'CB', 31, 70, 'SRB'),
        makePlayer(pid(), 'Antonio Barreca',         'LB', 29, 67, 'ITA'),
        makePlayer(pid(), 'Adam Obert',              'LB', 21, 69, 'SVK'),
        makePlayer(pid(), 'Alessandro Deiola',       'CDM',28, 69, 'ITA'),
        makePlayer(pid(), 'Razvan Marin',            'CM', 27, 73, 'ROU'),
        makePlayer(pid(), 'Jakub Jankto',            'LW', 28, 70, 'CZE'),
        makePlayer(pid(), 'Zito Luvumbo',            'LW', 21, 70, 'ANG'),
        makePlayer(pid(), 'Alessandro Mancosu',      'CM', 33, 68, 'ITA'),
        makePlayer(pid(), 'Gianluca Lapadula',       'ST', 33, 72, 'ITA'),
        makePlayer(pid(), 'Leonardo Pavoletti',      'ST', 35, 70, 'ITA'),
        makePlayer(pid(), 'Ante Budimir',            'ST', 31, 72, 'CRO'),
        makePlayer(pid(), 'Gaetano Prati',           'CDM',22, 68, 'ITA'),
    ]},
    { id: 'sal', name: 'Salernitana',    short: 'SAL', color: '#8B0000', colorAlt: '#FFFFFF', prestige: 56, budget: Math.round(Math.pow(Math.max(0,56-40),2)*45000), stadium: 'Arechi',                   capacity: 37843, squad: [
        makePlayer(pid(), 'Luigi Sepe',              'GK', 33, 71, 'ITA'),
        makePlayer(pid(), 'Vincenzo Fiorillo',       'GK', 35, 66, 'ITA'),
        makePlayer(pid(), 'Pasquale Mazzocchi',      'RB', 28, 69, 'ITA'),
        makePlayer(pid(), 'Flavius Daniliuc',        'CB', 22, 68, 'AUT'),
        makePlayer(pid(), 'Lorenzo Pirola',          'CB', 21, 69, 'ITA'),
        makePlayer(pid(), 'Matteo Lovato',           'CB', 23, 69, 'ITA'),
        makePlayer(pid(), 'Pawel Jaroszynski',       'LB', 27, 68, 'POL'),
        makePlayer(pid(), 'Domagoj Bradaric',        'LB', 24, 68, 'CRO'),
        makePlayer(pid(), 'Lassana Coulibaly',       'CDM',27, 70, 'MLI'),
        makePlayer(pid(), 'Giulio Maggiore',         'CM', 25, 68, 'ITA'),
        makePlayer(pid(), 'Tonny Vilhena',           'CM', 29, 68, 'NED'),
        makePlayer(pid(), 'Mohamed Coulibaly',       'CM', 22, 67, 'SEN'),
        makePlayer(pid(), 'Loum Tchaouna',           'RW', 19, 67, 'FRA'),
        makePlayer(pid(), 'Grigoris Kastanos',       'CM', 27, 68, 'CYP'),
        makePlayer(pid(), 'Boulaye Dia',             'ST', 26, 73, 'SEN'),
        makePlayer(pid(), 'Milan Djuric',            'ST', 33, 70, 'BIH'),
        makePlayer(pid(), 'Krzysztof Piatek',        'ST', 28, 70, 'POL'),
    ]},
    { id: 'ver', name: 'Verona',         short: 'VER', color: '#003DA5', colorAlt: '#FFD700', prestige: 60, budget: Math.round(Math.pow(Math.max(0,60-40),2)*45000), stadium: 'Marcantonio Bentegodi',    capacity: 39211, squad: [
        makePlayer(pid(), 'Lorenzo Montipo',         'GK', 27, 72, 'ITA'),
        makePlayer(pid(), 'Simone Perilli',          'GK', 30, 65, 'ITA'),
        makePlayer(pid(), 'Davide Faraoni',          'RB', 31, 71, 'ITA'),
        makePlayer(pid(), 'Filippo Terracciano',     'RB', 24, 68, 'ITA'),
        makePlayer(pid(), 'Adrien Tameze',           'CDM',29, 71, 'FRA'),
        makePlayer(pid(), 'Federico Ceccherini',     'CB', 30, 69, 'ITA'),
        makePlayer(pid(), 'Pawel Dawidowicz',        'CB', 27, 71, 'POL'),
        makePlayer(pid(), 'Darko Lazovic',           'LW', 32, 72, 'SRB'),
        makePlayer(pid(), 'Cedric Doumbe',           'LB', 22, 66, 'FRA'),
        makePlayer(pid(), 'Cyril Ngonge',            'RW', 23, 69, 'BEL'),
        makePlayer(pid(), 'Albin Ekdal',             'CDM',34, 69, 'SWE'),
        makePlayer(pid(), 'Thomas Henry',            'ST', 29, 70, 'FRA'),
        makePlayer(pid(), 'Nikola Kalinic',          'ST', 36, 72, 'CRO'),
        makePlayer(pid(), 'Josh Doig',               'LB', 22, 68, 'SCO'),
        makePlayer(pid(), 'Kevin Lasagna',           'LW', 31, 69, 'ITA'),
        makePlayer(pid(), 'Giangiacomo Magnani',     'CB', 27, 70, 'ITA'),
        makePlayer(pid(), 'Ivor Pandur',             'GK', 22, 64, 'CRO'),
        makePlayer(pid(), 'Henry Bonazzoli',         'ST', 27, 68, 'ITA'),
    ]},
    { id: 'sas', name: 'Sassuolo',       short: 'SAS', color: '#007A33', colorAlt: '#000000', prestige: 62, budget: Math.round(Math.pow(Math.max(0,62-40),2)*45000), stadium: 'MAPEI Stadium',            capacity: 21525, squad: [
        makePlayer(pid(), 'Andrea Consigli',         'GK', 36, 73, 'ITA'),
        makePlayer(pid(), 'Gianluca Pegolo',         'GK', 38, 68, 'ITA'),
        makePlayer(pid(), 'Jeremy Toljan',           'RB', 29, 71, 'GER'),
        makePlayer(pid(), 'Rogério',                 'LB', 25, 72, 'BRA'),
        makePlayer(pid(), 'Gian Marco Ferrari',      'CB', 31, 73, 'ITA'),
        makePlayer(pid(), 'Kaan Ayhan',              'CB', 28, 72, 'GER'),
        makePlayer(pid(), 'Giorgos Kyriakopoulos',   'LB', 27, 71, 'GRE'),
        makePlayer(pid(), 'Ervin Zukanovic',         'CB', 35, 68, 'BIH'),
        makePlayer(pid(), 'Maxime Lopez',            'CM', 26, 72, 'FRA'),
        makePlayer(pid(), 'Kristian Thorstvedt',     'CM', 23, 71, 'NOR'),
        makePlayer(pid(), 'Hamed Traore',            'CM', 23, 73, 'CIV'),
        makePlayer(pid(), 'Domenico Berardi',        'RW', 29, 80, 'ITA'),
        makePlayer(pid(), 'Armand Lauriente',        'LW', 24, 72, 'FRA'),
        makePlayer(pid(), 'Daniel Boloca',           'CDM',22, 69, 'ITA'),
        makePlayer(pid(), 'Andrea Pinamonti',        'ST', 24, 72, 'ITA'),
        makePlayer(pid(), 'Matheus Henrique',        'CM', 25, 70, 'BRA'),
        makePlayer(pid(), 'Davide Frattesi',         'CM', 24, 75, 'ITA'),
        makePlayer(pid(), 'Filippo Romagna',         'CB', 27, 69, 'ITA'),
    ]},
];

const SERIE_B_TEAMS = [
    { id: 'par', name: 'Parma',          short: 'PAR', color: '#FFFF00', colorAlt: '#003DA5', prestige: 59, budget: Math.round(Math.pow(Math.max(0,59-40),2)*45000), stadium: 'Tardini',                          capacity: 27906, squad: [
        makePlayer(pid(), 'Gianluigi Buffon',        'GK', 46, 70, 'ITA'),
        makePlayer(pid(), 'Simone Colombi',          'GK', 32, 66, 'ITA'),
        makePlayer(pid(), 'Enrico Delprato',         'RB', 25, 68, 'ITA'),
        makePlayer(pid(), 'Yordan Osorio',           'CB', 25, 68, 'VEN'),
        makePlayer(pid(), 'Botond Balogh',           'CB', 22, 68, 'HUN'),
        makePlayer(pid(), 'Woyo Coulibaly',          'CB', 24, 68, 'GUI'),
        makePlayer(pid(), 'Filippo Zanellato',       'LB', 27, 68, 'ITA'),
        makePlayer(pid(), 'Pontus Almqvist',         'LW', 24, 68, 'SWE'),
        makePlayer(pid(), 'Jasmin Kurtic',           'CDM',34, 69, 'SVN'),
        makePlayer(pid(), 'Adrian Bernabe',          'CM', 21, 71, 'ESP'),
        makePlayer(pid(), 'Mateus Sohm',             'CM', 24, 68, 'SUI'),
        makePlayer(pid(), 'Valentin Mihaila',        'LW', 23, 71, 'ROU'),
        makePlayer(pid(), 'Dennis Man',              'RW', 25, 72, 'ROU'),
        makePlayer(pid(), 'Matteo Cancellieri',      'LW', 22, 69, 'ITA'),
        makePlayer(pid(), 'Gennaro Tutino',          'ST', 28, 69, 'ITA'),
        makePlayer(pid(), 'Roberto Inglese',         'ST', 32, 69, 'ITA'),
        makePlayer(pid(), 'Yann Karamoh',            'RW', 26, 67, 'FRA'),
    ]},
    { id: 'com', name: 'Como',           short: 'COM', color: '#003DA5', colorAlt: '#FFFFFF', prestige: 57, budget: Math.round(Math.pow(Math.max(0,57-40),2)*45000), stadium: 'Stadio G. Sinigaglia',              capacity: 13602, squad: [
        makePlayer(pid(), 'Fabio Gliubizzi',         'GK', 28, 66, 'ITA'),
        makePlayer(pid(), 'Eduardo Ionita',          'GK', 32, 62, 'ROU'),
        makePlayer(pid(), 'Cesc Fabregas',           'CM', 37, 70, 'ESP'),
        makePlayer(pid(), 'Marco Curto',             'CB', 27, 65, 'ITA'),
        makePlayer(pid(), 'Luca Goldaniga',          'CB', 31, 66, 'ITA'),
        makePlayer(pid(), 'Alessandro Gabrielloni',  'ST', 27, 66, 'ITA'),
        makePlayer(pid(), 'Patrick Cutrone',         'ST', 27, 68, 'ITA'),
        makePlayer(pid(), 'Nico Iardino',            'RB', 27, 64, 'ITA'),
        makePlayer(pid(), 'Simone Verdi',            'RW', 31, 66, 'ITA'),
        makePlayer(pid(), 'Da Riva Gabriele',        'LB', 25, 63, 'ITA'),
        makePlayer(pid(), 'Marcus Zak Yanez',        'CM', 25, 65, 'ITA'),
        makePlayer(pid(), 'Blanco Federico',         'CM', 23, 64, 'ITA'),
        makePlayer(pid(), 'Stijepovic Luka',         'RW', 26, 64, 'MNE'),
        makePlayer(pid(), 'Iovine Stefano',          'CM', 23, 63, 'ITA'),
        makePlayer(pid(), 'Cerri Alberto',           'ST', 27, 65, 'ITA'),
        makePlayer(pid(), 'La Gumina Antonino',      'ST', 28, 64, 'ITA'),
        makePlayer(pid(), 'Odenthal Obed',           'CB', 22, 63, 'NED'),
    ]},
    { id: 'ven', name: 'Venezia',        short: 'VEN', color: '#FF6600', colorAlt: '#007A33', prestige: 57, budget: Math.round(Math.pow(Math.max(0,57-40),2)*45000), stadium: 'Pier Luigi Penzo',                  capacity: 11150, squad: [
        makePlayer(pid(), 'Niki Maenpaa',            'GK', 37, 68, 'FIN'),
        makePlayer(pid(), 'Luca Lezzerini',          'GK', 28, 66, 'ITA'),
        makePlayer(pid(), 'Pasquale Mazzocchi',      'RB', 28, 68, 'ITA'),
        makePlayer(pid(), 'Daan Heymans',            'CM', 24, 67, 'BEL'),
        makePlayer(pid(), 'Michael Svoboda',         'CB', 22, 67, 'CZE'),
        makePlayer(pid(), 'Ridgeciano Haps',         'LB', 28, 67, 'NED'),
        makePlayer(pid(), 'Massimo Gorgon',          'CB', 27, 65, 'ITA'),
        makePlayer(pid(), 'Pietro Ceccaroni',        'CB', 27, 68, 'ITA'),
        makePlayer(pid(), 'Tanner Tessmann',         'CDM',22, 68, 'USA'),
        makePlayer(pid(), 'Gianluca Busio',          'CM', 22, 68, 'USA'),
        makePlayer(pid(), 'Mattia Aramu',            'CAM',27, 69, 'ITA'),
        makePlayer(pid(), 'Simone Edera',            'RW', 27, 66, 'ITA'),
        makePlayer(pid(), 'Jordi Mboula',            'RW', 23, 67, 'ESP'),
        makePlayer(pid(), 'Salim Ben Seghir',        'CM', 20, 68, 'FRA'),
        makePlayer(pid(), 'Joel Pohjanpalo',         'ST', 29, 71, 'FIN'),
        makePlayer(pid(), 'Christian Gytkjaer',      'ST', 30, 68, 'DEN'),
        makePlayer(pid(), 'Kristoffer Askildsen',    'CM', 23, 66, 'NOR'),
    ]},
    { id: 'pal', name: 'Palermo',        short: 'PAL', color: '#FE4A00', colorAlt: '#000000', prestige: 56, budget: Math.round(Math.pow(Math.max(0,56-40),2)*45000), stadium: 'Renzo Barbera',                     capacity: 36349, squad: [
        makePlayer(pid(), 'Piragibe',                'GK', 26, 65, 'BRA'),
        makePlayer(pid(), 'Sebastiano Desplanches',  'GK', 22, 63, 'ITA'),
        makePlayer(pid(), 'Dario Sala',              'RB', 25, 63, 'ITA'),
        makePlayer(pid(), 'Ionut Nedelcearu',        'CB', 26, 66, 'ROU'),
        makePlayer(pid(), 'Francesco Lucioni',       'CB', 32, 66, 'ITA'),
        makePlayer(pid(), 'Luca Sala',               'LB', 25, 63, 'ITA'),
        makePlayer(pid(), 'Tommaso Augello',         'LB', 27, 65, 'ITA'),
        makePlayer(pid(), 'Mateju Martin',           'RB', 24, 64, 'CZE'),
        makePlayer(pid(), 'Leo Stulac',              'CDM',30, 66, 'SVN'),
        makePlayer(pid(), 'Damiani',                 'CM', 23, 65, 'ITA'),
        makePlayer(pid(), 'Claudio Gomes',           'CDM',22, 65, 'FRA'),
        makePlayer(pid(), 'Jagiello Pawel',          'CM', 24, 64, 'POL'),
        makePlayer(pid(), 'Roberto Insigne',         'LW', 29, 66, 'ITA'),
        makePlayer(pid(), 'Nicola Valente',          'LW', 24, 65, 'ITA'),
        makePlayer(pid(), 'Kristoffer Soleri',       'ST', 27, 64, 'ITA'),
        makePlayer(pid(), 'Matteo Brunori',          'ST', 28, 69, 'ITA'),
        makePlayer(pid(), 'Grzegorz Grosicki',       'RW', 35, 67, 'POL'),
    ]},
    { id: 'bre', name: 'Brescia',        short: 'BRE', color: '#003DA5', colorAlt: '#FFFFFF', prestige: 56, budget: Math.round(Math.pow(Math.max(0,56-40),2)*45000), stadium: 'Mario Rigamonti',                   capacity: 16999, squad: [
        makePlayer(pid(), 'Lorenzo Andrenacci',      'GK', 28, 66, 'ITA'),
        makePlayer(pid(), 'Emanuele Beccaro',        'GK', 25, 62, 'ITA'),
        makePlayer(pid(), 'Stefano Sabelli',         'RB', 28, 65, 'ITA'),
        makePlayer(pid(), 'Andrea Papetti',          'CB', 22, 64, 'ITA'),
        makePlayer(pid(), 'Roberto Pirrone',         'CB', 28, 63, 'ITA'),
        makePlayer(pid(), 'Flavio Bianchi',          'ST', 24, 65, 'ITA'),
        makePlayer(pid(), 'Luca Corrado',            'LB', 23, 63, 'ITA'),
        makePlayer(pid(), 'Dimitri Bisoli',          'CM', 27, 67, 'ITA'),
        makePlayer(pid(), 'Matteo Bertagnoli',       'CM', 22, 64, 'ITA'),
        makePlayer(pid(), 'Emanuele Ndoj',           'CM', 27, 63, 'ALB'),
        makePlayer(pid(), 'Sandro Tonali',           'CDM',23, 62, 'ITA'),
        makePlayer(pid(), 'Luka Spalek',             'LW', 25, 63, 'SVK'),
        makePlayer(pid(), 'Florian Aye',             'ST', 28, 66, 'FRA'),
        makePlayer(pid(), 'Lorenzo Moreo',           'ST', 31, 65, 'ITA'),
        makePlayer(pid(), 'Luca Caprari',            'LW', 29, 66, 'ITA'),
        makePlayer(pid(), 'Emanuele Valeri',         'LB', 24, 64, 'ITA'),
        makePlayer(pid(), 'Massimo van de Looi',     'CDM',31, 64, 'NED'),
    ]},
    { id: 'pis', name: 'Pisa',           short: 'PIS', color: '#003DA5', colorAlt: '#000000', prestige: 55, budget: Math.round(Math.pow(Math.max(0,55-40),2)*45000), stadium: 'Arena Garibaldi',                   capacity: 10150, squad: [
        makePlayer(pid(), 'Nicolas Andrade',         'GK', 26, 65, 'BRA'),
        makePlayer(pid(), 'Gori Stefano',            'GK', 30, 63, 'ITA'),
        makePlayer(pid(), 'Barbieri Lorenzo',        'RB', 22, 64, 'ITA'),
        makePlayer(pid(), 'Hermannsson Birn',        'CB', 25, 65, 'ISL'),
        makePlayer(pid(), 'Ionut Rus',               'CB', 28, 64, 'ROU'),
        makePlayer(pid(), 'Ionut Nedelcearu',        'CB', 26, 64, 'ROU'),
        makePlayer(pid(), 'Nicola Esteves',          'RB', 22, 63, 'POR'),
        makePlayer(pid(), 'Simone Calabresi',        'RB', 27, 62, 'ITA'),
        makePlayer(pid(), 'Veljan Nikolic',          'CDM',25, 64, 'SRB'),
        makePlayer(pid(), 'Touré Lamine',            'CM', 27, 65, 'GUI'),
        makePlayer(pid(), 'Matteo Tramoni',          'LW', 23, 66, 'ITA'),
        makePlayer(pid(), 'Piccinini Daniele',       'CM', 23, 63, 'ITA'),
        makePlayer(pid(), 'Sibilli Davide',          'LW', 26, 64, 'ITA'),
        makePlayer(pid(), 'Mlakar Jan',              'RW', 24, 64, 'SVN'),
        makePlayer(pid(), 'Morutan Olimpiu',         'CM', 23, 64, 'ROU'),
        makePlayer(pid(), 'Lorenzo Torregrossa',     'ST', 32, 66, 'ITA'),
        makePlayer(pid(), 'Arena Cristian',          'CDM',23, 62, 'ITA'),
    ]},
    { id: 'cat', name: 'Catanzaro',      short: 'CAT', color: '#FF0000', colorAlt: '#FFFF00', prestige: 53, budget: Math.round(Math.pow(Math.max(0,53-40),2)*45000), stadium: 'Nicola Ceravolo',                   capacity: 10310, squad: [
        makePlayer(pid(), 'Fulignati Luca',          'GK', 30, 63, 'ITA'),
        makePlayer(pid(), 'Sala Emilio',             'GK', 27, 59, 'ITA'),
        makePlayer(pid(), 'Scognamillo Nicolò',      'CB', 26, 62, 'ITA'),
        makePlayer(pid(), 'Brighenti Simone',        'CB', 34, 62, 'ITA'),
        makePlayer(pid(), 'Antonini Luca',           'LB', 25, 61, 'ITA'),
        makePlayer(pid(), 'Martinelli Andrea',       'RB', 24, 59, 'ITA'),
        makePlayer(pid(), 'Situm Antonio',           'RW', 27, 62, 'CRO'),
        makePlayer(pid(), 'Ohene Welbeck',           'RW', 26, 60, 'GHA'),
        makePlayer(pid(), 'Verna Lorenzo',           'CDM',28, 62, 'ITA'),
        makePlayer(pid(), 'Petriccione Mirko',       'CM', 29, 62, 'ITA'),
        makePlayer(pid(), 'Vandeputte Niklas',       'LW', 26, 61, 'BEL'),
        makePlayer(pid(), 'Sounas Dimitris',         'CM', 27, 61, 'GRE'),
        makePlayer(pid(), 'Biasci Simone',           'ST', 31, 63, 'ITA'),
        makePlayer(pid(), 'Iemmello Pietro',         'ST', 31, 65, 'ITA'),
        makePlayer("D'Andrea Matteo",         'ST', 22, 60, 'ITA', 65),
        makePlayer(pid(), 'Pontisso Stefano',        'CM', 28, 60, 'ITA'),
        makePlayer(pid(), 'Fazio Gianluca',          'LB', 25, 59, 'ITA'),
    ]},
    { id: 'spe', name: 'Spezia',         short: 'SPE', color: '#003DA5', colorAlt: '#FFFFFF', prestige: 54, budget: Math.round(Math.pow(Math.max(0,54-40),2)*45000), stadium: 'Alberto Picco',                     capacity: 10336, squad: [
        makePlayer(pid(), 'Bartlomiej Dragowski',    'GK', 26, 68, 'POL'),
        makePlayer(pid(), 'Jernej Zoet',             'GK', 32, 64, 'NED'),
        makePlayer(pid(), 'Luca Vignali',            'RB', 27, 65, 'ITA'),
        makePlayer(pid(), 'Jakub Kiwior',            'CB', 23, 70, 'POL'),
        makePlayer(pid(), 'Giorgio Bertola',         'CB', 22, 64, 'ITA'),
        makePlayer(pid(), 'Arkadiusz Reca',          'LB', 29, 65, 'POL'),
        makePlayer(pid(), 'Hristov Kristyan',        'CB', 28, 63, 'BUL'),
        makePlayer(pid(), 'Mehdi Bourabia',          'CDM',32, 65, 'MAR'),
        makePlayer(pid(), 'Salvatore Esposito',      'CM', 22, 67, 'ITA'),
        makePlayer(pid(), 'Giulio Maggiore',         'CM', 25, 66, 'ITA'),
        makePlayer(pid(), 'Kevin Agudelo',           'CM', 24, 65, 'COL'),
        makePlayer(pid(), 'Simone Bastoni',          'LW', 24, 66, 'ITA'),
        makePlayer(pid(), 'Emmanuel Gyasi',          'RW', 30, 67, 'GHA'),
        makePlayer(pid(), 'Verde Simone',            'LW', 27, 65, 'ITA'),
        makePlayer(pid(), 'Petros Mantalos',         'CM', 31, 65, 'GRE'),
        makePlayer(pid(), 'Mbala Nzola',             'ST', 27, 69, 'ANG'),
        makePlayer(pid(), 'Daniele Verde',           'CAM',27, 65, 'ITA'),
    ]},
    { id: 'mod', name: 'Modena',         short: 'MOD', color: '#FFFF00', colorAlt: '#003DA5', prestige: 52, budget: Math.round(Math.pow(Math.max(0,52-40),2)*45000), stadium: 'Alberto Braglia',                   capacity: 21151, squad: [
        makePlayer(pid(), 'Riccardo Gagno',          'GK', 28, 63, 'ITA'),
        makePlayer(pid(), 'Filippo Perucchini',      'GK', 26, 61, 'ITA'),
        makePlayer(pid(), 'Andrea Oukhadda',         'RB', 25, 61, 'ITA'),
        makePlayer(pid(), 'Maxime Busi',             'RB', 24, 62, 'BEL'),
        makePlayer(pid(), 'Davide Gagliolo',         'CB', 33, 63, 'ITA'),
        makePlayer(pid(), 'Mattia Caldara',          'CB', 28, 66, 'ITA'),
        makePlayer(pid(), 'Federico Renzetti',       'LB', 29, 60, 'ITA'),
        makePlayer(pid(), 'Luca Duca',               'CB', 27, 60, 'ITA'),
        makePlayer(pid(), 'Gian Luca Gavioli',       'CDM',25, 60, 'ITA'),
        makePlayer(pid(), 'Edoardo Gerli',           'CM', 27, 62, 'ITA'),
        makePlayer(pid(), 'Stefano Battistella',     'CM', 26, 61, 'ITA'),
        makePlayer(pid(), 'Antonio Palumbo',         'CM', 25, 64, 'ITA'),
        makePlayer(pid(), 'Luca Tremolada',          'LW', 29, 63, 'ITA'),
        makePlayer(pid(), 'Lorenzo Mosti',           'CM', 24, 61, 'ITA'),
        makePlayer(pid(), 'Mirko Marsura',           'LW', 27, 60, 'ITA'),
        makePlayer(pid(), 'Alessio Diaw',            'ST', 28, 64, 'ITA'),
        makePlayer(pid(), 'Marco Bonfanti',          'ST', 24, 62, 'ITA'),
    ]},
    { id: 'cre', name: 'Cremonese',      short: 'CRE', color: '#CC0000', colorAlt: '#FFFF00', prestige: 54, budget: Math.round(Math.pow(Math.max(0,54-40),2)*45000), stadium: 'Giovanni Zini',                     capacity: 16003, squad: [
        makePlayer(pid(), 'Marco Carnesecchi',       'GK', 23, 72, 'ITA'),
        makePlayer(pid(), 'Felice Brancolini',       'GK', 23, 62, 'ITA'),
        makePlayer(pid(), 'Leonardo Sernicola',      'RB', 24, 63, 'ITA'),
        makePlayer(pid(), 'Johan Vasquez',           'CB', 25, 66, 'MEX'),
        makePlayer(pid(), 'Matteo Bianchetti',       'CB', 31, 65, 'ITA'),
        makePlayer(pid(), 'Luka Lochoshvili',        'CB', 21, 63, 'GEO'),
        makePlayer(pid(), 'Emanuele Valeri',         'LB', 24, 64, 'ITA'),
        makePlayer(pid(), 'Giacomo Quagliata',       'LB', 25, 63, 'ITA'),
        makePlayer(pid(), 'Castagnetti Filippo',     'CDM',29, 63, 'ITA'),
        makePlayer(pid(), 'Andrea Pickel',           'CM', 22, 63, 'ITA'),
        makePlayer(pid(), 'Baez Santiago',           'CM', 26, 64, 'ARG'),
        makePlayer(pid(), 'Cyriel Dessers',          'ST', 29, 69, 'NGA'),
        makePlayer(pid(), 'Stephane Buonaiuto',      'RW', 25, 63, 'ITA'),
        makePlayer(pid(), 'Zanimacchia Luca',        'RW', 26, 63, 'ITA'),
        makePlayer(pid(), 'Tsadjout Frank',          'LW', 23, 62, 'FRA'),
        makePlayer(pid(), 'Massimo Coda',            'ST', 33, 66, 'ITA'),
        makePlayer(pid(), 'Daniel Ciofani',          'ST', 36, 65, 'ITA'),
    ]},
    { id: 'sam', name: 'Sampdoria',      short: 'SAM', color: '#003DA5', colorAlt: '#CC0000', prestige: 60, budget: Math.round(Math.pow(Math.max(0,60-40),2)*45000), stadium: 'Luigi Ferraris',                    capacity: 36685, squad: [
        makePlayer(pid(), 'Emil Audero',             'GK', 26, 72, 'ITA'),
        makePlayer(pid(), 'Nikita Contini',          'GK', 27, 65, 'ITA'),
        makePlayer(pid(), 'Bartosz Bereszynski',     'RB', 31, 71, 'POL'),
        makePlayer(pid(), 'Andrea Conti',            'RB', 30, 69, 'ITA'),
        makePlayer(pid(), 'Alexander Ferrari',       'CB', 28, 69, 'ITA'),
        makePlayer(pid(), 'Omar Colley',             'CB', 30, 71, 'GAM'),
        makePlayer(pid(), 'Nicola Murru',            'LB', 31, 69, 'ITA'),
        makePlayer(pid(), 'Jeison Murillo',          'CB', 32, 69, 'COL'),
        makePlayer(pid(), 'Tomas Rincon',            'CDM',36, 70, 'VEN'),
        makePlayer(pid(), 'Gonzalo Villar',          'CM', 25, 70, 'ESP'),
        makePlayer(pid(), 'Valerio Verre',           'CM', 30, 70, 'ITA'),
        makePlayer(pid(), 'Albin Ekdal',             'CDM',34, 69, 'SWE'),
        makePlayer(pid(), 'Mikkel Damsgaard',        'CM', 23, 72, 'DEN'),
        makePlayer(pid(), 'Kristoffer Askildsen',    'CM', 23, 68, 'NOR'),
        makePlayer(pid(), 'Manolo Gabbiadini',       'ST', 32, 72, 'ITA'),
        makePlayer(pid(), 'Francesco Caputo',        'ST', 36, 70, 'ITA'),
        makePlayer(pid(), 'Gerry Coda',              'ST', 27, 67, 'ITA'),
    ]},
    { id: 'reg', name: 'Reggiana',       short: 'REG', color: '#CC0000', colorAlt: '#FFFFFF', prestige: 50, budget: Math.round(Math.pow(Math.max(0,50-40),2)*45000), stadium: 'Mapei Football Center',             capacity: 7500,  squad: [
        makePlayer(pid(), 'Stefano Voltolini',       'GK', 28, 61, 'ITA'),
        makePlayer(pid(), 'Christian Gibert',        'GK', 26, 57, 'ITA'),
        makePlayer(pid(), 'Luca Nardi',              'RB', 23, 61, 'ITA'),
        makePlayer(pid(), 'Lorenzo Lucchesi',        'CB', 22, 60, 'ITA'),
        makePlayer(pid(), 'Matteo Marcandalli',      'CB', 23, 61, 'ITA'),
        makePlayer(pid(), 'Rozzio Fabio',            'CB', 30, 61, 'ITA'),
        makePlayer(pid(), 'Cigarini Luca',           'CDM',37, 62, 'ITA'),
        makePlayer(pid(), 'Serena Maximiliano',      'LW', 27, 61, 'ITA'),
        makePlayer(pid(), 'Girma Ghion',             'CM', 24, 60, 'ITA'),
        makePlayer(pid(), 'Vergara Maximiliano',     'CM', 25, 60, 'ITA'),
        makePlayer(pid(), 'Portanova Manolo',        'CM', 22, 62, 'ITA'),
        makePlayer(pid(), 'Davide Marchi',           'CM', 26, 59, 'ITA'),
        makePlayer(pid(), 'Urso Fabio',              'CDM',27, 60, 'ITA'),
        makePlayer(pid(), 'Riveros Carlos',          'CM', 29, 60, 'PAR'),
        makePlayer(pid(), 'Gondo Christian',         'ST', 27, 60, 'BUL'),
        makePlayer(pid(), 'Yeboah Emmanuel',         'ST', 22, 61, 'GHA'),
        makePlayer(pid(), 'Pettinari Stefano',       'ST', 30, 60, 'ITA'),
    ]},
    { id: 'bar', name: 'Bari',           short: 'BAR', color: '#CC0000', colorAlt: '#FFFFFF', prestige: 54, budget: Math.round(Math.pow(Math.max(0,54-40),2)*45000), stadium: 'San Nicola',                        capacity: 58270, squad: [
        makePlayer(pid(), 'Nicola Radunovic',        'GK', 28, 65, 'SRB'),
        makePlayer(pid(), 'Elia Caprile',            'GK', 23, 64, 'ITA'),
        makePlayer(pid(), 'Vito Bellomo',            'LW', 30, 65, 'ITA'),
        makePlayer(pid(), 'Pucino Alexis',           'RB', 26, 63, 'ITA'),
        makePlayer(pid(), 'Federico Gori',           'CB', 26, 63, 'ITA'),
        makePlayer(pid(), 'Davide Bais',             'CB', 25, 62, 'ITA'),
        makePlayer(pid(), 'Sgarbi Umberto',          'CB', 29, 62, 'ITA'),
        makePlayer(pid(), 'Riccardo Maiello',        'CDM',31, 64, 'ITA'),
        makePlayer(pid(), 'Cristiano Lupatelli',     'GK', 35, 62, 'ITA'),
        makePlayer(pid(), 'Salim Ben Seghir',        'CM', 20, 66, 'FRA'),
        makePlayer(pid(), 'Maita Michele',           'CM', 27, 64, 'ITA'),
        makePlayer(pid(), 'Bianco Michele',          'CDM',22, 64, 'ITA'),
        makePlayer(pid(), 'Dorval Etienne',          'RW', 23, 63, 'FRA'),
        makePlayer(pid(), 'Walid Cheddira',          'ST', 26, 67, 'MAR'),
        makePlayer(pid(), 'Mirco Antenucci',         'ST', 37, 65, 'ITA'),
        makePlayer(pid(), 'Citro Federico',          'ST', 25, 62, 'ITA'),
        makePlayer(pid(), 'Benedetti Cristian',      'CM', 29, 62, 'ITA'),
    ]},
    { id: 'cit', name: 'Cittadella',     short: 'CIT', color: '#990000', colorAlt: '#FFFFFF', prestige: 51, budget: Math.round(Math.pow(Math.max(0,51-40),2)*45000), stadium: 'Pier Cesare Tombolato',             capacity: 7623,  squad: [
        makePlayer(pid(), 'Matej Handanovic',        'GK', 39, 62, 'SVN'),
        makePlayer(pid(), 'Luca Maniero',            'GK', 26, 59, 'ITA'),
        makePlayer(pid(), 'Perticone Marcello',      'CB', 33, 61, 'ITA'),
        makePlayer(pid(), 'Donnarumma Alessio',      'CM', 30, 61, 'ITA'),
        makePlayer(pid(), 'Visentin Nicolas',        'RB', 25, 60, 'ITA'),
        makePlayer(pid(), 'Pavan Alessandro',        'CM', 24, 60, 'ITA'),
        makePlayer(pid(), 'Branca Luca',             'CB', 24, 60, 'ITA'),
        makePlayer(pid(), 'Cassandro Davide',        'RB', 26, 60, 'ITA'),
        makePlayer(pid(), 'Berardi Alessandro',      'LW', 23, 61, 'ITA'),
        makePlayer(pid(), 'Magrassi Enrico',         'ST', 27, 62, 'ITA'),
        makePlayer(pid(), 'Antonucci Mirko',         'RW', 25, 61, 'ITA'),
        makePlayer(pid(), 'Tronchin Riccardo',       'CM', 24, 60, 'ITA'),
        makePlayer(pid(), 'Salvi Michele',           'RB', 28, 59, 'ITA'),
        makePlayer(pid(), 'Carriero Andrea',         'CM', 26, 60, 'ITA'),
        makePlayer(pid(), 'Pitarello Alessio',       'ST', 24, 60, 'ITA'),
        makePlayer(pid(), 'Lores Varela',            'LW', 33, 61, 'POR'),
        makePlayer(pid(), 'Mastrantonio',            'GK', 32, 60, 'ITA'),
    ]},
    { id: 'cos', name: 'Cosenza',        short: 'COS', color: '#FF0000', colorAlt: '#003DA5', prestige: 50, budget: Math.round(Math.pow(Math.max(0,50-40),2)*45000), stadium: 'San Vito-Gigi Marulla',             capacity: 24603, squad: [
        makePlayer(pid(), 'Marson Michael',          'GK', 25, 61, 'ITA'),
        makePlayer(pid(), 'Micai Alessandro',        'GK', 31, 60, 'ITA'),
        makePlayer(pid(), 'Gyamfi Emmanuel',         'RB', 23, 60, 'GHA'),
        makePlayer(pid(), 'Meroni Caleb',            'CB', 24, 60, 'ITA'),
        makePlayer(pid(), 'Camporese Pietro',        'CB', 27, 61, 'ITA'),
        makePlayer(pid(), 'Falcone Mirko',           'LB', 26, 59, 'ITA'),
        makePlayer(pid(), 'Idda Alessandro',         'CB', 27, 59, 'ITA'),
        makePlayer(pid(), 'Rispoli Andrea',          'RB', 31, 59, 'ITA'),
        makePlayer(pid(), 'Brescianini Marco',       'CM', 23, 62, 'ITA'),
        makePlayer(pid(), 'Voca Gennaro',            'CDM',22, 60, 'ITA'),
        makePlayer(pid(), 'Florenzi Luca',           'CM', 28, 60, 'ITA'),
        makePlayer(pid(), 'Corsi Mirko',             'LW', 32, 61, 'ITA'),
        makePlayer(pid(), 'Zilli Francesco',         'LW', 22, 60, 'ITA'),
        makePlayer(pid(), 'Forte Francesco',         'ST', 30, 61, 'ITA'),
        makePlayer(pid(), 'Nasti Marco',             'ST', 21, 61, 'ITA'),
        makePlayer(pid(), 'Butic Mirko',             'ST', 32, 60, 'SVN'),
        makePlayer(pid(), 'Martino Gennaro',         'CM', 25, 59, 'ITA'),
    ]},
    { id: 'fsp', name: 'FeralpiSalo',    short: 'FSP', color: '#003DA5', colorAlt: '#FFFFFF', prestige: 48, budget: Math.round(Math.pow(Math.max(0,48-40),2)*45000), stadium: 'Lino Turina',                       capacity: 4500,  squad: [
        makePlayer(pid(), 'Pizzignacco Elia',        'GK', 26, 59, 'ITA'),
        makePlayer(pid(), 'Minelli Lorenzo',         'GK', 29, 57, 'ITA'),
        makePlayer(pid(), 'Bergonzi Filippo',        'RB', 25, 57, 'ITA'),
        makePlayer(pid(), 'Pilati Andrea',           'CB', 27, 57, 'ITA'),
        makePlayer(pid(), 'Grando Alessandro',       'CB', 24, 57, 'ITA'),
        makePlayer(pid(), 'Tonetto Leonardo',        'LB', 33, 57, 'ITA'),
        makePlayer(pid(), 'Petrow Diego',            'CDM',27, 58, 'ITA'),
        makePlayer(pid(), 'Lisi Riccardo',           'CM', 25, 59, 'ITA'),
        makePlayer(pid(), 'Siligardi Luca',          'LW', 32, 59, 'ITA'),
        makePlayer(pid(), 'Guerra Francesco',        'RW', 27, 57, 'ITA'),
        makePlayer(pid(), 'Buonaiuto Cristian',      'CM', 29, 58, 'ITA'),
        makePlayer(pid(), 'Sau Marco',               'ST', 34, 60, 'ITA'),
        makePlayer(pid(), 'Miracoli Federico',       'ST', 29, 60, 'ITA'),
        makePlayer(pid(), 'Kargbo Mamadou',          'ST', 22, 58, 'SLE'),
        makePlayer(pid(), 'Compagnon Yoann',         'LW', 27, 57, 'FRA'),
        makePlayer(pid(), 'Legati Matteo',           'CB', 26, 56, 'ITA'),
        makePlayer(pid(), 'Balestrero Luca',         'CM', 28, 56, 'ITA'),
    ]},
    { id: 'lcc', name: 'Lecco',          short: 'LCC', color: '#003DA5', colorAlt: '#FFFFFF', prestige: 47, budget: Math.round(Math.pow(Math.max(0,47-40),2)*45000), stadium: 'Mario Rigamonti replica',           capacity: 4500,  squad: [
        makePlayer(pid(), 'Stucchi Davide',          'GK', 28, 58, 'ITA'),
        makePlayer(pid(), 'Melgrati Martin',         'GK', 24, 56, 'ITA'),
        makePlayer(pid(), 'Lora Andrea',             'RB', 26, 56, 'ITA'),
        makePlayer(pid(), 'Celjak Josip',            'CB', 28, 57, 'CRO'),
        makePlayer(pid(), 'Battistini Federico',     'CB', 27, 57, 'ITA'),
        makePlayer(pid(), 'Giudici Paolo',           'LB', 25, 56, 'ITA'),
        makePlayer(pid(), 'Scarsella Alessio',       'CB', 30, 56, 'ITA'),
        makePlayer(pid(), 'Ierardi Matteo',          'CB', 24, 56, 'ITA'),
        makePlayer(pid(), 'Galli Francesco',         'CDM',28, 58, 'ITA'),
        makePlayer(pid(), 'Girotti Alessandro',      'CM', 26, 57, 'ITA'),
        makePlayer(pid(), 'Ionita Artur',            'CM', 33, 59, 'ROU'),
        makePlayer(pid(), 'Zambataro Matteo',        'LW', 26, 57, 'ITA'),
        makePlayer(pid(), 'Buso Davide',             'RW', 25, 57, 'ITA'),
        makePlayer(pid(), 'Enrici Filippo',          'CM', 24, 56, 'ITA'),
        makePlayer(pid(), 'Frigerio Daniele',        'RB', 27, 56, 'ITA'),
        makePlayer(pid(), 'Pinzauti Gianmarco',      'ST', 23, 58, 'ITA'),
        makePlayer(pid(), 'Sipos Antonio',           'ST', 24, 58, 'CRO'),
    ]},
    { id: 'sdt', name: 'Sudtirol',       short: 'SDT', color: '#CC0000', colorAlt: '#000000', prestige: 50, budget: Math.round(Math.pow(Math.max(0,50-40),2)*45000), stadium: 'Druso',                             capacity: 7500,  squad: [
        makePlayer(pid(), 'Poluzzi Eugenio',         'GK', 32, 61, 'ITA'),
        makePlayer(pid(), 'Drago Marco',             'GK', 27, 58, 'ITA'),
        makePlayer(pid(), 'Fabbri Luca',             'RB', 25, 59, 'ITA'),
        makePlayer(pid(), 'Masiello Andrea',         'CB', 36, 61, 'ITA'),
        makePlayer(pid(), 'Giorgini Alessandro',     'CB', 27, 60, 'ITA'),
        makePlayer(pid(), 'Berra Mirko',             'LB', 29, 60, 'ITA'),
        makePlayer(pid(), 'Kofler Robert',           'CB', 30, 59, 'AUT'),
        makePlayer(pid(), 'Tait Michael',            'CM', 26, 61, 'AUT'),
        makePlayer(pid(), 'Casiraghi Luca',          'CDM',28, 60, 'ITA'),
        makePlayer(pid(), 'Nicolussi Caviglia Hans', 'CM', 22, 61, 'ITA'),
        makePlayer(pid(), 'Molina Davide',           'CM', 28, 59, 'ARG'),
        makePlayer(pid(), 'Siega Lorenzo',           'CM', 25, 59, 'ITA'),
        makePlayer(pid(), 'Broh Solomon',            'CM', 27, 59, 'SWE'),
        makePlayer(pid(), 'Rover Luca',              'LW', 27, 61, 'ITA'),
        makePlayer(pid(), 'Mazzocchi Daniele',       'RW', 29, 60, 'ITA'),
        makePlayer(pid(), 'Odogwu Cedric',           'ST', 25, 61, 'NGA'),
        makePlayer(pid(), 'Marconi Umberto',         'ST', 31, 60, 'ITA'),
    ]},
    { id: 'ter', name: 'Ternana',        short: 'TER', color: '#CC0000', colorAlt: '#007A33', prestige: 49, budget: Math.round(Math.pow(Math.max(0,49-40),2)*45000), stadium: 'Libero Liberati',                   capacity: 17459, squad: [
        makePlayer(pid(), 'Iannarilli Andrea',       'GK', 31, 61, 'ITA'),
        makePlayer(pid(), 'Furlan Michele',          'GK', 25, 57, 'ITA'),
        makePlayer(pid(), 'Mammarella Luca',         'LB', 32, 60, 'ITA'),
        makePlayer(pid(), 'Capuano Giovanni',        'CB', 33, 60, 'ITA'),
        makePlayer(pid(), 'Boben Zan',               'CB', 30, 60, 'SVN'),
        makePlayer(pid(), 'Diakite Seydou',          'RB', 25, 58, 'FRA'),
        makePlayer(pid(), 'Celli Luca',              'LB', 23, 58, 'ITA'),
        makePlayer(pid(), 'Coulibaly Mamadou',       'CDM',24, 59, 'MLI'),
        makePlayer(pid(), 'Di Tacchio Francesco',    'CM', 31, 60, 'ITA'),
        makePlayer(pid(), 'Palumbo Antonio',         'CM', 26, 60, 'ITA'),
        makePlayer(pid(), 'Paghera Marco',           'CM', 27, 59, 'ITA'),
        makePlayer(pid(), 'Partipilo Ferrante',      'LW', 28, 61, 'ITA'),
        makePlayer(pid(), 'Cesar Falletti',          'CAM',29, 61, 'URU'),
        makePlayer(pid(), 'Donnarumma Alfredo',      'ST', 31, 60, 'ITA'),
        makePlayer(pid(), 'Favilli Andrea',          'ST', 27, 60, 'ITA'),
        makePlayer(pid(), 'Sorensen Sune',           'ST', 31, 61, 'DEN'),
        makePlayer(pid(), 'Agazzi Carmine',          'GK', 40, 59, 'ITA'),
    ]},
    { id: 'asc', name: 'Ascoli',         short: 'ASC', color: '#000000', colorAlt: '#FFFFFF', prestige: 48, budget: Math.round(Math.pow(Math.max(0,48-40),2)*45000), stadium: 'Cino e Lillo Del Duca',             capacity: 20389, squad: [
        makePlayer(pid(), 'Guarna Andrea',           'GK', 38, 60, 'ITA'),
        makePlayer(pid(), 'Bolletta Raffaele',       'GK', 26, 56, 'ITA'),
        makePlayer(pid(), 'Adjapong Christian',      'RB', 26, 59, 'ITA'),
        makePlayer(pid(), 'Bellusci Giuseppe',       'CB', 35, 60, 'ITA'),
        makePlayer(pid(), 'Botteghin Eric',          'CB', 33, 60, 'NED'),
        makePlayer(pid(), 'Quaranta Luca',           'LB', 25, 57, 'ITA'),
        makePlayer(pid(), 'Baschirotto Federico',    'CB', 27, 59, 'ITA'),
        makePlayer(pid(), 'Collocolo Luca',          'CM', 22, 61, 'ITA'),
        makePlayer(pid(), 'Caligara Davide',         'CM', 25, 60, 'ITA'),
        makePlayer(pid(), 'Eramo Marco',             'CM', 28, 59, 'ITA'),
        makePlayer(pid(), 'Buchel Martin',           'CM', 34, 59, 'LIE'),
        makePlayer(pid(), 'Bidaoui Abou',            'LW', 27, 60, 'MAR'),
        makePlayer(pid(), 'Mendes Giuseppe',         'RW', 23, 59, 'ITA'),
        makePlayer(pid(), 'Millico Vincenzo',        'LW', 24, 59, 'ITA'),
        makePlayer(pid(), 'Giovane Simone',          'RW', 24, 58, 'ITA'),
        makePlayer(pid(), 'Dionisi Cristian',        'ST', 29, 60, 'ITA'),
        makePlayer(pid(), 'Gondo Christian',         'ST', 27, 60, 'BUL'),
    ]},
];

SERIE_A_TEAMS.forEach(t => { ALL_TEAMS.push(t); TEAM_MAP[t.id] = t; });
SERIE_B_TEAMS.forEach(t => { ALL_TEAMS.push(t); TEAM_MAP[t.id] = t; });

LEAGUES['serie_a'] = {
    id: 'serie_a',
    name: 'Serie A',
    country: 'italy',
    tier: 1,
    teams: SERIE_A_TEAMS.map(t => t.id),
    relegationSpots: 3,
    promotionSpots: 0,
    promotionPlayoff: 0,
};

LEAGUES['serie_b'] = {
    id: 'serie_b',
    name: 'Serie B',
    country: 'italy',
    tier: 2,
    teams: SERIE_B_TEAMS.map(t => t.id),
    relegationSpots: 3,
    promotionSpots: 2,
    promotionPlayoff: 4,
};
