// Helper: convert array entries to makePlayer calls with computed potential
function generateSquad(arr) {
  return arr.map(([name, pos, age, ovr, nat]) => {
    const pot = age <= 21 ? Math.min(97, ovr + Math.floor(Math.random()*9) + 10)
              : age <= 25 ? Math.min(95, ovr + Math.floor(Math.random()*6) + 3)
              : ovr;
    return makePlayer(pid(), name, pos, age, ovr, nat);
  });
}

// dataLigaPortugal.js — Liga Portugal (div1 only)

const LIGA_PORTUGAL_TEAMS = [
    {
        id: 'ben', name: 'Benfica', short: 'BEN', color: '#CC0000', colorAlt: '#FFFFFF',
        prestige: 86, budget: Math.round(Math.pow(Math.max(0,86-40),2)*45000),
        stadium: 'Estadio da Luz', capacity: 64642,
        squad: generateSquad([
            ['Trubin',          'GK',  22, 84, 'UKR'],
            ['Vlachodimos',     'GK',  29, 81, 'GRE'],
            ['Bah',             'RB',  23, 80, 'SEN'],
            ['Gilberto',        'RB',  32, 76, 'BRA'],
            ['Otamendi',        'CB',  36, 83, 'ARG'],
            ['Antonio Silva',   'CB',  20, 83, 'POR'],
            ['Morato',          'CB',  23, 78, 'BRA'],
            ['Grimaldo',        'LB',  28, 84, 'ESP'],
            ['Alvaro Carreras', 'LB',  22, 76, 'ESP'],
            ['Florentino',      'CDM', 24, 80, 'POR'],
            ['Joao Neves',      'CM',  19, 82, 'POR'],
            ['Aursnes',         'CM',  28, 79, 'NOR'],
            ['Chiquinho',       'CM',  27, 75, 'POR'],
            ['Rafa Silva',      'RW',  31, 82, 'POR'],
            ['Di Maria',        'RW',  36, 81, 'ARG'],
            ['Aktürkoglu',      'LW',  25, 80, 'TUR'],
            ['Neres',           'LW',  27, 83, 'BRA'],
            ['Gonçalo Ramos',   'ST',  22, 84, 'POR'],
            ['Arthur Cabral',   'ST',  26, 79, 'BRA'],
        ])
    },
    {
        id: 'fcp', name: 'Porto', short: 'FCP', color: '#003DA5', colorAlt: '#FFFFFF',
        prestige: 85, budget: Math.round(Math.pow(Math.max(0,85-40),2)*45000),
        stadium: 'Estadio do Dragao', capacity: 50033,
        squad: generateSquad([
            ['Diogo Costa',   'GK',  24, 85, 'POR'],
            ['Claudio Ramos', 'GK',  31, 74, 'POR'],
            ['Joao Mario',    'RB',  31, 80, 'POR'],
            ['Wendell',       'LB',  31, 78, 'GER'],
            ['Pepe',          'CB',  41, 79, 'POR'],
            ['David Carmo',   'CB',  24, 78, 'POR'],
            ['Marcano',       'CB',  35, 77, 'ESP'],
            ['Uribe',         'CDM', 27, 79, 'COL'],
            ['Eustaquio',     'CDM', 27, 79, 'CAN'],
            ['Grujic',        'CM',  28, 77, 'SRB'],
            ['Fabio Vieira',  'CAM', 23, 79, 'POR'],
            ['Ivan Jaime',    'CM',  20, 73, 'ESP'],
            ['Galeno',        'LW',  26, 83, 'BRA'],
            ['Veron',         'LW',  24, 74, 'BRA'],
            ['Pepê',          'RW',  27, 81, 'BRA'],
            ['Danny Namaso',  'RW',  21, 75, 'FRA'],
            ['Evanilson',     'ST',  24, 82, 'BRA'],
            ['Toni Martinez', 'ST',  27, 77, 'ESP'],
        ])
    },
    {
        id: 'scp', name: 'Sporting CP', short: 'SCP', color: '#00952B', colorAlt: '#FFD700',
        prestige: 84, budget: Math.round(Math.pow(Math.max(0,84-40),2)*45000),
        stadium: 'Jose Alvalade', capacity: 50095,
        squad: generateSquad([
            ['Israel',          'GK',  35, 78, 'POR'],
            ['Kovacevic',       'GK',  25, 73, 'SRB'],
            ['Porro',           'RB',  24, 83, 'ESP'],
            ['Esgaio',          'RB',  30, 74, 'POR'],
            ['Inacio',          'CB',  22, 83, 'POR'],
            ['Coates',          'CB',  33, 82, 'URU'],
            ['St Juste',        'CB',  27, 80, 'NED'],
            ['Nuno Santos',     'LB',  27, 79, 'POR'],
            ['Matheus Reis',    'LB',  31, 77, 'BRA'],
            ['Hjulmand',        'CDM', 26, 82, 'DEN'],
            ['Morita',          'CDM', 26, 78, 'JPN'],
            ['Bragança',        'CM',  28, 76, 'CPV'],
            ['Goncalves',       'CM',  25, 78, 'POR'],
            ['Trincao',         'RW',  24, 80, 'POR'],
            ['Edwards',         'CAM', 25, 80, 'WAL'],
            ['Paulinho',        'LW',  28, 78, 'POR'],
            ['Gyokeres',        'ST',  26, 88, 'SWE'],
            ['Rodrigo Ribeiro', 'ST',  19, 73, 'POR'],
        ])
    },
    {
        id: 'brg', name: 'SC Braga', short: 'BRG', color: '#C62039', colorAlt: '#FFFFFF',
        prestige: 73, budget: Math.round(Math.pow(Math.max(0,73-40),2)*45000),
        stadium: 'Municipal de Braga', capacity: 30286,
        squad: generateSquad([
            ['Matheus',       'GK',  27, 79, 'BRA'],
            ['Tiago Sa',      'GK',  24, 74, 'POR'],
            ['Fabiano',       'RB',  25, 73, 'POR'],
            ['Gomez',         'RB',  23, 72, 'ARG'],
            ['Leite',         'CB',  26, 76, 'POR'],
            ['Carmo',         'CB',  24, 77, 'POR'],
            ['Gomez A',       'CB',  30, 75, 'ARG'],
            ['Rodrigues',     'LB',  27, 74, 'POR'],
            ['Sequeira',      'LB',  29, 74, 'POR'],
            ['Al-Musrati',    'CDM', 28, 77, 'LBA'],
            ['Horta',         'CM',  28, 78, 'POR'],
            ['Piazon',        'CM',  30, 74, 'BRA'],
            ['Pizzi',         'CM',  34, 75, 'POR'],
            ['Iuri Medeiros', 'RW',  29, 73, 'POR'],
            ['Wenderson',     'LW',  27, 77, 'CPV'],
            ['Simon Banza',   'ST',  27, 78, 'FRA'],
            ['Vitinha',       'ST',  24, 76, 'POR'],
            ['Castro',        'ST',  31, 75, 'URU'],
        ])
    },
    {
        id: 'vit', name: 'Vitoria SC', short: 'VIT', color: '#003DA5', colorAlt: '#FFFFFF',
        prestige: 67, budget: Math.round(Math.pow(Math.max(0,67-40),2)*45000),
        stadium: 'Estadio D. Afonso Henriques', capacity: 30029,
        squad: generateSquad([
            ['Varela',          'GK',  29, 76, 'POR'],
            ['Madu',            'GK',  25, 71, 'NGA'],
            ['Lado',            'RB',  27, 72, 'POR'],
            ['Bamba',           'RB',  22, 70, 'FRA'],
            ['Sulic',           'CB',  25, 73, 'SVN'],
            ['Jubal',           'CB',  28, 73, 'BRA'],
            ['Joao Ferreira',   'CB',  26, 72, 'POR'],
            ['Marques',         'LB',  24, 71, 'POR'],
            ['Nuno Moreira',    'LB',  27, 69, 'POR'],
            ['Alfa Semedo',     'CDM', 28, 73, 'GNB'],
            ['Tomas Handel',    'CM',  24, 74, 'POR'],
            ['Óscar Maciel',    'CM',  23, 72, 'POR'],
            ['Rúben Lameiras',  'CAM', 30, 73, 'POR'],
            ['Nélson da Cruz',  'RW',  24, 71, 'POR'],
            ['Rochinha',        'LW',  28, 70, 'POR'],
            ['Kaio César',      'ST',  24, 73, 'BRA'],
            ['Maga',            'LW',  26, 70, 'CPV'],
            ['Bueno',           'ST',  27, 68, 'BRA'],
        ])
    },
    {
        id: 'fam', name: 'Famalicao', short: 'FAM', color: '#003DA5', colorAlt: '#FFFFFF',
        prestige: 61, budget: Math.round(Math.pow(Math.max(0,61-40),2)*45000),
        stadium: 'Estadio Municipal de Famalicao', capacity: 5500,
        squad: generateSquad([
            ['Luiz Júnior',    'GK',  28, 65, 'BRA'],
            ['Defendi',        'GK',  33, 62, 'BRA'],
            ['Cláudio Falcão', 'RB',  26, 63, 'POR'],
            ['Toro',           'RB',  24, 61, 'ARG'],
            ['Roderick',       'CB',  29, 65, 'POR'],
            ['Tulipa',         'CB',  27, 63, 'POR'],
            ['Nélio',          'CB',  25, 62, 'POR'],
            ['Fábio Martins',  'LB',  28, 62, 'POR'],
            ['Diogo Figueiras','LB',  26, 61, 'POR'],
            ['Gustavo Assunção','CDM',25, 64, 'BRA'],
            ['Anderson',       'CM',  27, 63, 'BRA'],
            ['Ivo Rodrigues',  'CM',  24, 62, 'POR'],
            ['Iván Jaime',     'CAM', 22, 63, 'ESP'],
            ['Toni Martínez',  'RW',  26, 61, 'ESP'],
            ['Elves Baldé',    'LW',  27, 63, 'GNB'],
            ['Cádiz',          'LW',  24, 60, 'POR'],
            ['Nico González',  'ST',  23, 64, 'ESP'],
            ['Rivaldinho',     'ST',  28, 62, 'BRA'],
            ['Zé Carlos',      'ST',  30, 61, 'POR'],
        ])
    },
    {
        id: 'bav', name: 'Boavista', short: 'BAV', color: '#000000', colorAlt: '#FFFFFF',
        prestige: 62, budget: Math.round(Math.pow(Math.max(0,62-40),2)*45000),
        stadium: 'Estadio do Bessa', capacity: 28263,
        squad: generateSquad([
            ['Bracali',        'GK',  38, 66, 'BRA'],
            ['Mináč',          'GK',  27, 63, 'SVK'],
            ['Makouta',        'RB',  25, 63, 'CGO'],
            ['Hamache',        'RB',  24, 61, 'ALG'],
            ['Álex Quintanilla','CB', 29, 65, 'ESP'],
            ['Neris',          'CB',  27, 64, 'POR'],
            ['Chidozie',       'CB',  26, 63, 'NGA'],
            ['Bruno Onyemaechi','LB', 25, 63, 'NGA'],
            ['Caetano',        'LB',  28, 62, 'POR'],
            ['Makouta B',      'CDM', 27, 64, 'CGO'],
            ['Elis',           'CM',  29, 64, 'ALB'],
            ['Sauer',          'CM',  28, 63, 'GER'],
            ['Gamboa',         'CAM', 31, 62, 'CRI'],
            ['Mama Baldé',     'RW',  29, 65, 'GNB'],
            ['Muse',           'LW',  26, 62, 'NGA'],
            ['Yusupha Njie',   'LW',  24, 63, 'GAM'],
            ['Hamache F',      'ST',  25, 64, 'ALG'],
            ['Linton',         'ST',  27, 62, 'POR'],
            ['Morlaye',        'ST',  23, 61, 'GIN'],
        ])
    },
    {
        id: 'est', name: 'Estoril', short: 'EST', color: '#FFEE00', colorAlt: '#003DA5',
        prestige: 59, budget: Math.round(Math.pow(Math.max(0,59-40),2)*45000),
        stadium: 'Estadio Antonio Coimbra da Mota', capacity: 5500,
        squad: generateSquad([
            ['Dani Figueira',  'GK',  30, 63, 'POR'],
            ['Thiago Rodrigues','GK', 26, 60, 'BRA'],
            ['Joãozinho',      'RB',  25, 62, 'POR'],
            ['João Gamboa',    'RB',  28, 60, 'POR'],
            ['Bernardo Vital', 'CB',  27, 63, 'POR'],
            ['Joele',          'CB',  24, 62, 'ANG'],
            ['André Vidigal',  'CB',  29, 61, 'POR'],
            ['Joãozinho L',    'LB',  26, 60, 'POR'],
            ['Rosic',          'LB',  28, 62, 'SRB'],
            ['Edgar Costa',    'CDM', 30, 63, 'CPV'],
            ['Tiago Gouveia',  'CM',  22, 62, 'POR'],
            ['Gauld',          'CM',  28, 63, 'SCO'],
            ['Diogo Pinto',    'CAM', 25, 61, 'POR'],
            ['Traoré',         'RW',  24, 62, 'MLI'],
            ['Lucas Cunha',    'LW',  23, 61, 'BRA'],
            ['Dário Essugo',   'LW',  19, 62, 'POR'],
            ['Pedro Álvaro',   'ST',  26, 63, 'POR'],
            ['Sandro',         'ST',  29, 61, 'POR'],
            ['Boateng',        'ST',  27, 60, 'GHA'],
        ])
    },
    {
        id: 'mor', name: 'Moreirense', short: 'MOR', color: '#00952B', colorAlt: '#FFFFFF',
        prestige: 58, budget: Math.round(Math.pow(Math.max(0,58-40),2)*45000),
        stadium: 'Estadio Comendador Joaquim de Almeida Freitas', capacity: 6008,
        squad: generateSquad([
            ['Pasinato',       'GK',  34, 63, 'BRA'],
            ['Kewin',          'GK',  26, 60, 'BRA'],
            ['Ibrahima',       'RB',  25, 62, 'SEN'],
            ['Gregório',       'RB',  27, 60, 'POR'],
            ['Pedro Amador',   'CB',  26, 62, 'POR'],
            ['Mbaye',          'CB',  28, 63, 'SEN'],
            ['Gonçalo Ribeiro','CB',  25, 61, 'POR'],
            ['André Amaro',    'LB',  27, 61, 'POR'],
            ['Sori Mané',      'LB',  24, 60, 'GNB'],
            ['Fane',           'CDM', 27, 63, 'MLI'],
            ['Filipe Soares',  'CM',  29, 62, 'POR'],
            ['Nuno Rodrigues', 'CM',  26, 60, 'POR'],
            ['Afonso Freitas', 'CAM', 23, 61, 'POR'],
            ['Yan',            'RW',  26, 62, 'BRA'],
            ['André Luís',     'LW',  24, 61, 'POR'],
            ['Walterson',      'LW',  27, 62, 'BRA'],
            ['Ângelo Silva',   'ST',  25, 63, 'POR'],
            ['Derik Lacerda',  'ST',  27, 62, 'BRA'],
            ['Mateus',         'ST',  24, 60, 'BRA'],
        ])
    },
    {
        id: 'gil', name: 'Gil Vicente', short: 'GIL', color: '#003DA5', colorAlt: '#000000',
        prestige: 57, budget: Math.round(Math.pow(Math.max(0,57-40),2)*45000),
        stadium: 'Estadio Cidade de Barcelos', capacity: 12574,
        squad: generateSquad([
            ['Denis',          'GK',  31, 63, 'BRA'],
            ['Andrew',         'GK',  28, 60, 'POR'],
            ['Vítor Castro',   'RB',  26, 62, 'POR'],
            ['Samuel Dias',    'RB',  24, 60, 'POR'],
            ['Talocha',        'CB',  29, 62, 'POR'],
            ['Rúben Fernandes','CB',  28, 61, 'POR'],
            ['Zé Carlos',      'CB',  27, 62, 'POR'],
            ['Júlio Rodrigues','LB',  26, 60, 'POR'],
            ['Oliveira',       'LB',  30, 61, 'POR'],
            ['Óscar Gill',     'CDM', 28, 62, 'ESP'],
            ['João Vieira',    'CM',  25, 61, 'POR'],
            ['Samuel',         'CM',  27, 60, 'POR'],
            ['Pedrinho',       'CAM', 23, 62, 'BRA'],
            ['Fran Navarro',   'RW',  28, 63, 'ESP'],
            ['Alexandre Guedes','LW', 30, 62, 'POR'],
            ['Kayky',          'LW',  21, 62, 'BRA'],
            ['Coreano',        'ST',  27, 62, 'BRA'],
            ['Kanya Fujimoto', 'ST',  25, 61, 'JPN'],
            ['Henrique',       'ST',  26, 60, 'BRA'],
        ])
    },
    {
        id: 'aro', name: 'Arouca', short: 'ARO', color: '#FFEE00', colorAlt: '#003DA5',
        prestige: 56, budget: Math.round(Math.pow(Math.max(0,56-40),2)*45000),
        stadium: 'Estadio Municipal de Arouca', capacity: 3800,
        squad: generateSquad([
            ['Rui Tavares',    'GK',  30, 62, 'POR'],
            ['Marco Pereira',  'GK',  25, 59, 'POR'],
            ['Sema',           'RB',  26, 61, 'POR'],
            ['Moualé',         'RB',  24, 60, 'MLI'],
            ['Koffi',          'CB',  27, 62, 'CIV'],
            ['David Simão',    'CB',  28, 61, 'POR'],
            ['Alan Ruiz',      'CB',  29, 60, 'ARG'],
            ['Antunes',        'LB',  35, 62, 'POR'],
            ['Douglas',        'LB',  27, 60, 'BRA'],
            ['Zé Valente',     'CDM', 27, 62, 'POR'],
            ['Oday Dabbagh',   'CM',  24, 62, 'PLE'],
            ['Adilson Gomes',  'CM',  26, 60, 'CPV'],
            ['Arsénio',        'CAM', 25, 61, 'POR'],
            ['Bukia',          'RW',  23, 62, 'GEO'],
            ['Rúben Pita',     'LW',  27, 61, 'POR'],
            ['Rodríguez',      'LW',  26, 60, 'URU'],
            ['Sylla',          'ST',  26, 62, 'GIN'],
            ['Leandro Silva',  'ST',  28, 61, 'POR'],
            ['Batista',        'ST',  24, 60, 'CPV'],
        ])
    },
    {
        id: 'cpa', name: 'Casa Pia', short: 'CPA', color: '#003DA5', colorAlt: '#FFFFFF',
        prestige: 57, budget: Math.round(Math.pow(Math.max(0,57-40),2)*45000),
        stadium: 'Estadio do Restelo', capacity: 19856,
        squad: generateSquad([
            ['Celton Biai',    'GK',  29, 63, 'GNB'],
            ['Caio Secco',     'GK',  24, 60, 'BRA'],
            ['Koffi',          'RB',  26, 62, 'CIV'],
            ['Filippe Rodrigues','RB',27, 61, 'BRA'],
            ['Cairo',          'CB',  28, 62, 'BRA'],
            ['Tiago Almeida',  'CB',  25, 62, 'POR'],
            ['Adrián Rodríguez','CB', 27, 61, 'ESP'],
            ['Clayton',        'LB',  29, 62, 'BRA'],
            ['Nuno Lopes',     'LB',  26, 60, 'POR'],
            ['Romeu',          'CDM', 30, 63, 'POR'],
            ['Platiny',        'CM',  25, 62, 'BRA'],
            ['Arian',          'CM',  23, 61, 'POR'],
            ['Zolotic',        'CAM', 25, 62, 'CRO'],
            ['Godwin',         'RW',  24, 62, 'NGA'],
            ['Danielson',      'LW',  27, 62, 'CPV'],
            ['Crespo',         'LW',  26, 61, 'ARG'],
            ['Dani Mota',      'ST',  24, 63, 'POR'],
            ['Lucas Máris',    'ST',  26, 62, 'BRA'],
            ['Rúben Rodrigues','ST',  28, 61, 'POR'],
        ])
    },
    {
        id: 'chv', name: 'Chaves', short: 'CHV', color: '#003DA5', colorAlt: '#FFFF00',
        prestige: 55, budget: Math.round(Math.pow(Math.max(0,55-40),2)*45000),
        stadium: 'Estadio Municipal Eng. Manuel Branco Teixeira', capacity: 8000,
        squad: generateSquad([
            ['Cláudio Peinado','GK', 31, 62, 'ESP'],
            ['Ricardo Moura',  'GK',  27, 59, 'POR'],
            ['Rafael Vieira',  'RB',  25, 61, 'POR'],
            ['Bruno Paz',      'RB',  27, 59, 'POR'],
            ['Abdu Conte',     'CB',  28, 61, 'GNB'],
            ['William',        'CB',  26, 60, 'BRA'],
            ['Héctor Hernández','CB', 29, 61, 'ESP'],
            ['David Borja',    'LB',  27, 60, 'ESP'],
            ['Marchesín alt',  'LB',  26, 59, 'POR'],
            ['Denílson',       'CDM', 27, 61, 'BRA'],
            ['Pires',          'CM',  28, 60, 'POR'],
            ['Baldé',          'CM',  25, 59, 'GNB'],
            ['Riascos',        'CAM', 29, 60, 'COL'],
            ['Phete',          'RW',  25, 61, 'LES'],
            ['Juninho Quixadá','LW',  26, 60, 'BRA'],
            ['Eboue Kouassi',  'LW',  26, 61, 'CIV'],
            ['Filipe Oliveira','ST',  28, 61, 'POR'],
            ['Alhassane',      'ST',  26, 60, 'GIN'],
            ['Rúben Lima',     'ST',  30, 59, 'POR'],
        ])
    },
    {
        id: 'viz', name: 'Vizela', short: 'VIZ', color: '#CC0000', colorAlt: '#FFFFFF',
        prestige: 54, budget: Math.round(Math.pow(Math.max(0,54-40),2)*45000),
        stadium: 'Estadio do FC Vizela', capacity: 7000,
        squad: generateSquad([
            ['Buntic',         'GK',  28, 62, 'CRO'],
            ['Marafona',       'GK',  35, 60, 'POR'],
            ['Kalaica',        'RB',  27, 61, 'CRO'],
            ['Safira',         'RB',  25, 59, 'CPV'],
            ['Schettine',      'CB',  28, 61, 'BRA'],
            ['Kouassi',        'CB',  26, 60, 'CIV'],
            ['Henrique Araújo','CB',  24, 59, 'POR'],
            ['Sasso',          'LB',  29, 60, 'BRA'],
            ['Nuno Valério',   'LB',  26, 59, 'POR'],
            ['Cassiano',       'CDM', 26, 61, 'BRA'],
            ['Léo Borges',     'CM',  24, 60, 'BRA'],
            ['Pedro Silva',    'CM',  27, 59, 'POR'],
            ['Nélson Monte',   'CAM', 28, 60, 'POR'],
            ['Murilo',         'RW',  24, 61, 'BRA'],
            ['Samu',           'LW',  21, 61, 'ESP'],
            ['Alpha Diallo',   'LW',  25, 59, 'GIN'],
            ['Claudemir',      'ST',  28, 61, 'BRA'],
            ['Kazu',           'ST',  26, 60, 'BRA'],
            ['Dinis Pinto',    'ST',  23, 59, 'POR'],
        ])
    },
    {
        id: 'rva', name: 'Rio Ave', short: 'RVA', color: '#006400', colorAlt: '#FFFFFF',
        prestige: 56, budget: Math.round(Math.pow(Math.max(0,56-40),2)*45000),
        stadium: 'Estadio dos Arcos', capacity: 12815,
        squad: generateSquad([
            ['Jhonatan',       'GK',  28, 63, 'BRA'],
            ['Kaká',           'GK',  30, 60, 'POR'],
            ['Costinha',       'RB',  28, 62, 'POR'],
            ['Fábio Ronaldo',  'RB',  25, 60, 'POR'],
            ['Aderllan',       'CB',  32, 63, 'BRA'],
            ['Amine',          'CB',  27, 61, 'MAR'],
            ['Marcelo',        'CB',  26, 61, 'BRA'],
            ['Carles Planas',  'LB',  34, 62, 'ESP'],
            ['Boateng',        'LB',  25, 60, 'GHA'],
            ['Tarantini',      'CDM', 29, 62, 'POR'],
            ['Geraldes',       'CM',  28, 62, 'POR'],
            ['André Pereira',  'CM',  26, 60, 'POR'],
            ['Emre Demir',     'CAM', 22, 62, 'TUR'],
            ['Aziz',           'RW',  25, 62, 'SEN'],
            ['Lucas Piazon',   'LW',  30, 62, 'BRA'],
            ['Guga',           'LW',  24, 61, 'BRA'],
            ['Carlos Mané',    'ST',  30, 63, 'POR'],
            ['Cícero',         'ST',  28, 62, 'BRA'],
            ['Pelé Dias',      'ST',  24, 60, 'CPV'],
        ])
    },
    {
        id: 'far', name: 'Farense', short: 'FAR', color: '#CC0000', colorAlt: '#FFFFFF',
        prestige: 54, budget: Math.round(Math.pow(Math.max(0,54-40),2)*45000),
        stadium: 'Estadio de Sao Luis', capacity: 9000,
        squad: generateSquad([
            ['Rafael Defendi', 'GK',  34, 62, 'BRA'],
            ['António Filipe', 'GK',  27, 59, 'POR'],
            ['Marco Matias',   'RB',  34, 61, 'POR'],
            ['Diga',           'RB',  25, 59, 'POR'],
            ['Vasco Lopes',    'CB',  26, 61, 'POR'],
            ['Fali Candé',     'CB',  28, 60, 'GNB'],
            ['Thierry',        'CB',  27, 60, 'CMR'],
            ['André Castro',   'LB',  33, 61, 'POR'],
            ['Passos',         'LB',  25, 59, 'POR'],
            ['Vitor Carvalho', 'CDM', 27, 62, 'POR'],
            ['Licá',           'CM',  29, 61, 'ANG'],
            ['Tomas Martins',  'CM',  24, 60, 'POR'],
            ['Ryan Gauld',     'CAM', 28, 61, 'SCO'],
            ['Bilal',          'RW',  25, 61, 'MAR'],
            ['Éber Bessa',     'LW',  29, 61, 'BRA'],
            ['Mayambela',      'LW',  27, 60, 'MOZ'],
            ['Cláudio Falcão F','ST', 26, 62, 'POR'],
            ['Idrissa',        'ST',  25, 60, 'GNB'],
            ['Sérgio Araújo',  'ST',  31, 61, 'ARG'],
        ])
    },
    {
        id: 'sea', name: 'Estrela Amadora', short: 'SEA', color: '#CC0000', colorAlt: '#FFFFFF',
        prestige: 53, budget: Math.round(Math.pow(Math.max(0,53-40),2)*45000),
        stadium: 'Estadio Jose Gomes', capacity: 9000,
        squad: generateSquad([
            ['Caio',           'GK',  27, 61, 'BRA'],
            ['Kieszek',        'GK',  36, 59, 'POL'],
            ['Nuno Tavares alt','RB', 25, 60, 'POR'],
            ['Diogo Calila',   'RB',  28, 59, 'POR'],
            ['Marcelo Goiano', 'CB',  29, 61, 'BRA'],
            ['Gamboa alt',     'CB',  27, 60, 'CPV'],
            ['Gonçalo Cardoso','CB',  24, 60, 'POR'],
            ['Ibáñez',         'LB',  26, 60, 'ESP'],
            ['Mateus Costa',   'LB',  25, 59, 'POR'],
            ['Dani Faria',     'CDM', 28, 61, 'POR'],
            ['Ricardo Ferreira','CM', 27, 60, 'POR'],
            ['Silva Ramos',    'CM',  26, 59, 'POR'],
            ['Mikel Agu',      'CAM', 29, 60, 'NGA'],
            ['Manu Silva',     'RW',  25, 61, 'POR'],
            ['Kauê',           'LW',  23, 60, 'BRA'],
            ['Kiki',           'LW',  26, 59, 'ANG'],
            ['Zito Luvumbo',   'ST',  21, 62, 'ANG'],
            ['Rodrigo Martins','ST',  27, 61, 'POR'],
            ['Fati',           'ST',  25, 60, 'GNB'],
        ])
    },
    {
        id: 'por2', name: 'Portimonense', short: 'POR', color: '#003DA5', colorAlt: '#FFFFFF',
        prestige: 53, budget: Math.round(Math.pow(Math.max(0,53-40),2)*45000),
        stadium: 'Estadio Municipal de Portimao', capacity: 9000,
        squad: generateSquad([
            ['Samuel Portugal','GK', 30, 62, 'POR'],
            ['Leandro',        'GK',  26, 59, 'BRA'],
            ['Pedro Sá',       'RB',  25, 61, 'POR'],
            ['Lamine Faty',    'RB',  24, 60, 'SEN'],
            ['Willyan',        'CB',  28, 62, 'BRA'],
            ['Lucas Possignolo','CB', 26, 60, 'BRA'],
            ['Carlinhos',      'CB',  29, 61, 'BRA'],
            ['Paulo Vítor',    'LB',  27, 60, 'BRA'],
            ['João Brevett',   'LB',  26, 59, 'POR'],
            ['Ewerton',        'CDM', 30, 62, 'BRA'],
            ['Pablo',          'CM',  28, 61, 'BRA'],
            ['Fabrício',       'CM',  26, 60, 'BRA'],
            ['Henrique',       'CAM', 25, 61, 'BRA'],
            ['Pedro Rei',      'RW',  28, 62, 'POR'],
            ['Beto',           'LW',  25, 61, 'POR'],
            ['Lucas Fernandes','LW',  27, 60, 'BRA'],
            ['Anderson Tavares','ST', 26, 62, 'CPV'],
            ['Matchoi Djalo',  'ST',  28, 61, 'GNB'],
            ['Luquinhas',      'ST',  28, 60, 'BRA'],
        ])
    },
];

LIGA_PORTUGAL_TEAMS.forEach(t => { ALL_TEAMS.push(t); TEAM_MAP[t.id] = t; });

LEAGUES['liga_portugal'] = {
    id: 'liga_portugal',
    name: 'Liga Portugal',
    country: 'portugal',
    tier: 1,
    teams: LIGA_PORTUGAL_TEAMS.map(t => t.id),
    relegationSpots: 3,
    promotionSpots: 0,
    promotionPlayoff: 0,
};
