// dataBundesliga.js — Bundesliga + Bundesliga 2

const BUNDESLIGA_TEAMS = [
    { id: 'bay', name: 'Bayern Munich',         short: 'BAY', color: '#DC052D', colorAlt: '#FFFFFF', prestige: 97, budget: Math.round(Math.pow(Math.max(0,97-40),2)*45000), stadium: 'Allianz Arena',              capacity: 75024, squad: [
        makePlayer(pid(), 'Manuel Neuer',           'GK', 38, 88, 'GER'),
        makePlayer(pid(), 'Sven Ulreich',           'GK', 35, 75, 'GER'),
        makePlayer(pid(), 'Joshua Kimmich',         'RB', 29, 88, 'GER'),
        makePlayer(pid(), 'Noussair Mazraoui',      'RB', 26, 81, 'MAR'),
        makePlayer(pid(), 'Dayot Upamecano',        'CB', 25, 85, 'FRA'),
        makePlayer(pid(), 'Kim Min-jae',            'CB', 28, 86, 'KOR'),
        makePlayer(pid(), 'Matthijs de Ligt',       'CB', 24, 84, 'NED'),
        makePlayer(pid(), 'Alphonso Davies',        'LB', 23, 85, 'CAN'),
        makePlayer(pid(), 'Raphael Guerreiro',      'LB', 30, 81, 'POR'),
        makePlayer(pid(), 'Leon Goretzka',          'CM', 29, 83, 'GER'),
        makePlayer(pid(), 'Konrad Laimer',          'CM', 27, 81, 'AUT'),
        makePlayer(pid(), 'Jamal Musiala',          'LW', 21, 88, 'GER'),
        makePlayer(pid(), 'Leroy Sane',             'RW', 28, 85, 'GER'),
        makePlayer(pid(), 'Thomas Muller',          'CAM',34, 84, 'GER'),
        makePlayer(pid(), 'Eric Maxim Choupo-Moting','ST',35, 79, 'CMR'),
        makePlayer(pid(), 'Harry Kane',             'ST', 30, 91, 'ENG'),
        makePlayer(pid(), 'Serge Gnabry',           'RW', 29, 83, 'GER'),
        makePlayer(pid(), 'Ryan Gravenberch',       'CM', 22, 79, 'NED'),
        makePlayer(pid(), 'Mathys Tel',             'RW', 19, 77, 'FRA'),
    ]},
    { id: 'bvb', name: 'Borussia Dortmund',     short: 'BVB', color: '#FDE100', colorAlt: '#000000', prestige: 86, budget: Math.round(Math.pow(Math.max(0,86-40),2)*45000), stadium: 'Signal Iduna Park',          capacity: 81365, squad: [
        makePlayer(pid(), 'Gregor Kobel',           'GK', 26, 84, 'SUI'),
        makePlayer(pid(), 'Alexander Meyer',        'GK', 32, 73, 'GER'),
        makePlayer(pid(), 'Julian Ryerson',         'RB', 26, 77, 'USA'),
        makePlayer(pid(), 'Thomas Meunier',         'RB', 33, 78, 'BEL'),
        makePlayer(pid(), 'Mats Hummels',           'CB', 35, 82, 'GER'),
        makePlayer(pid(), 'Nico Schlotterbeck',     'CB', 24, 83, 'GER'),
        makePlayer(pid(), 'Niklas Sule',            'CB', 29, 83, 'GER'),
        makePlayer(pid(), 'Ian Maatsen',            'LB', 22, 79, 'NED'),
        makePlayer(pid(), 'Emre Can',               'CDM',30, 80, 'GER'),
        makePlayer(pid(), 'Julian Brandt',          'CM', 28, 81, 'GER'),
        makePlayer(pid(), 'Felix Nmecha',           'CM', 23, 77, 'GER'),
        makePlayer(pid(), 'Karim Adeyemi',          'LW', 22, 80, 'GER'),
        makePlayer(pid(), 'Donyell Malen',          'RW', 25, 81, 'NED'),
        makePlayer(pid(), 'Marco Reus',             'CAM',35, 83, 'GER'),
        makePlayer(pid(), 'Niclas Fullkrug',        'ST', 31, 82, 'GER'),
        makePlayer(pid(), 'Youssoufa Moukoko',      'ST', 19, 77, 'GER'),
        makePlayer(pid(), 'Jamie Bynoe-Gittens',    'LW', 20, 77, 'ENG'),
        makePlayer(pid(), 'Jadon Sancho',           'RW', 24, 81, 'ENG'),
        makePlayer(pid(), 'Marcel Sabitzer',        'CM', 30, 79, 'AUT'),
    ]},
    { id: 'b04', name: 'Bayer Leverkusen',      short: 'B04', color: '#E32221', colorAlt: '#000000', prestige: 85, budget: Math.round(Math.pow(Math.max(0,85-40),2)*45000), stadium: 'BayArena',                   capacity: 30210, squad: [
        makePlayer(pid(), 'Lukas Hradecky',         'GK', 34, 83, 'FIN'),
        makePlayer(pid(), 'Mark Flekken',           'GK', 30, 78, 'GER'),
        makePlayer(pid(), 'Jeremie Frimpong',       'RB', 23, 83, 'NED'),
        makePlayer(pid(), 'Jonathan Tah',           'CB', 28, 84, 'GER'),
        makePlayer(pid(), 'Piero Hincapie',         'CB', 22, 80, 'ECU'),
        makePlayer(pid(), 'Edmond Tapsoba',         'CB', 25, 82, 'BFA'),
        makePlayer(pid(), 'Alejandro Grimaldo',     'LB', 28, 84, 'ESP'),
        makePlayer(pid(), 'Granit Xhaka',           'CDM',31, 84, 'SUI'),
        makePlayer(pid(), 'Robert Andrich',         'CDM',29, 81, 'GER'),
        makePlayer(pid(), 'Exequiel Palacios',      'CM', 22, 79, 'ARG'),
        makePlayer(pid(), 'Florian Wirtz',          'CAM',21, 89, 'GER'),
        makePlayer(pid(), 'Jonas Hofmann',          'RW', 31, 81, 'GER'),
        makePlayer(pid(), 'Amine Adli',             'CM', 24, 78, 'FRA'),
        makePlayer(pid(), 'Moussa Diaby',           'LW', 27, 82, 'FRA'),
        makePlayer(pid(), 'Adam Hlozek',            'RW', 21, 76, 'CZE'),
        makePlayer(pid(), 'Victor Boniface',        'ST', 23, 83, 'NGA'),
        makePlayer(pid(), 'Patrik Schick',          'ST', 28, 82, 'CZE'),
        makePlayer(pid(), 'Martin Terrier',         'LW', 27, 80, 'FRA'),
        makePlayer(pid(), 'Odilon Kossounou',       'CB', 23, 78, 'CIV'),
    ]},
    { id: 'rbl', name: 'RB Leipzig',            short: 'RBL', color: '#CC0000', colorAlt: '#003DA5', prestige: 83, budget: Math.round(Math.pow(Math.max(0,83-40),2)*45000), stadium: 'Red Bull Arena',             capacity: 47069, squad: [
        makePlayer(pid(), 'Peter Gulacsi',          'GK', 33, 83, 'HUN'),
        makePlayer(pid(), 'Janis Blaswich',         'GK', 29, 75, 'GER'),
        makePlayer(pid(), 'Mohamed Simakan',        'RB', 23, 80, 'FRA'),
        makePlayer(pid(), 'Lukas Klostermann',      'RB', 28, 79, 'GER'),
        makePlayer(pid(), 'Willi Orban',            'CB', 31, 80, 'HUN'),
        makePlayer(pid(), 'Castello Lukeba',        'CB', 21, 80, 'FRA'),
        makePlayer(pid(), 'David Raum',             'LB', 26, 81, 'GER'),
        makePlayer(pid(), 'Xaver Schlager',         'CDM',27, 79, 'AUT'),
        makePlayer(pid(), 'Kevin Kampl',            'CDM',33, 78, 'SVN'),
        makePlayer(pid(), 'Timo Werner',            'LW', 28, 79, 'GER'),
        makePlayer(pid(), 'Christopher Nkunku',     'CAM',26, 85, 'FRA'),
        makePlayer(pid(), 'Dani Olmo',              'CAM',26, 85, 'ESP'),
        makePlayer(pid(), 'Dominik Szoboszlai',     'CM', 23, 84, 'HUN'),
        makePlayer(pid(), 'Lois Openda',            'ST', 24, 84, 'BEL'),
        makePlayer(pid(), 'Yussuf Poulsen',         'ST', 30, 76, 'DEN'),
        makePlayer(pid(), 'Nicolas Seiwald',        'CM', 23, 78, 'AUT'),
        makePlayer(pid(), 'Benjamin Henrichs',      'RB', 27, 78, 'GER'),
        makePlayer(pid(), 'Amadou Haidara',         'CM', 26, 79, 'MLI'),
    ]},
    { id: 'sge', name: 'Eintracht Frankfurt',   short: 'SGE', color: '#E1000F', colorAlt: '#000000', prestige: 75, budget: Math.round(Math.pow(Math.max(0,75-40),2)*45000), stadium: 'Deutsche Bank Park',         capacity: 51500, squad: [
        makePlayer(pid(), 'Kevin Trapp',            'GK', 33, 82, 'GER'),
        makePlayer(pid(), 'Kelle Roos',             'GK', 30, 72, 'NED'),
        makePlayer(pid(), 'Tuta',                   'CB', 25, 79, 'BRA'),
        makePlayer(pid(), 'Hrvoje Smolcic',         'CB', 22, 74, 'CRO'),
        makePlayer(pid(), 'Robin Koch',             'CB', 27, 79, 'GER'),
        makePlayer(pid(), 'Willian Pacho',          'CB', 22, 79, 'ECU'),
        makePlayer(pid(), 'Dodô',                   'RB', 25, 78, 'BRA'),
        makePlayer(pid(), 'Ansgar Knauff',          'RW', 23, 76, 'GER'),
        makePlayer(pid(), 'Kristijan Jakic',        'CDM',26, 76, 'AUT'),
        makePlayer(pid(), 'Djibril Sow',            'CDM',27, 78, 'SUI'),
        makePlayer(pid(), 'Mario Gotze',            'CAM',32, 79, 'GER'),
        makePlayer(pid(), 'Junior Dina Ebimbe',     'CM', 22, 76, 'FRA'),
        makePlayer(pid(), 'Daichi Kamada',          'CM', 27, 79, 'JPN'),
        makePlayer(pid(), 'Omar Marmoush',          'ST', 25, 80, 'EGY'),
        makePlayer(pid(), 'Randal Kolo Muani',      'ST', 25, 82, 'FRA'),
        makePlayer(pid(), 'Rafael Borre',           'ST', 28, 78, 'COL'),
        makePlayer(pid(), 'Lucas Alario',           'ST', 32, 74, 'ARG'),
        makePlayer(pid(), 'Niels Nkounkou',         'LB', 23, 74, 'FRA'),
    ]},
    { id: 'vfb', name: 'VfB Stuttgart',         short: 'VFB', color: '#E12216', colorAlt: '#FFFFFF', prestige: 74, budget: Math.round(Math.pow(Math.max(0,74-40),2)*45000), stadium: 'Mercedes-Benz Arena',        capacity: 60449, squad: [
        makePlayer(pid(), 'Alexander Nubel',        'GK', 27, 79, 'GER'),
        makePlayer(pid(), 'Florian Muller',         'GK', 26, 74, 'GER'),
        makePlayer(pid(), 'Hiroki Ito',             'LB', 24, 77, 'JPN'),
        makePlayer(pid(), 'Waldemar Anton',         'CB', 27, 78, 'GER'),
        makePlayer(pid(), 'Dan-Axel Zagadou',       'CB', 25, 77, 'FRA'),
        makePlayer(pid(), 'Konstantinos Mavropanos','CB', 26, 77, 'GRE'),
        makePlayer(pid(), 'Pascal Stenzel',         'RB', 27, 74, 'GER'),
        makePlayer(pid(), 'Maximilian Mittelstadt', 'LB', 26, 75, 'GER'),
        makePlayer(pid(), 'Chris Fuhrich',          'LW', 25, 77, 'GER'),
        makePlayer(pid(), 'Serhou Guirassy',        'ST', 27, 81, 'GUI'),
        makePlayer(pid(), 'Wataru Endo',            'CDM',30, 80, 'JPN'),
        makePlayer(pid(), 'Angelo Stiller',         'CM', 23, 76, 'GER'),
        makePlayer(pid(), 'Silas Katompa',          'RW', 24, 76, 'COD'),
        makePlayer(pid(), 'Deniz Undav',            'ST', 27, 78, 'GER'),
        makePlayer(pid(), 'Tiago Tomas',            'LW', 22, 74, 'POR'),
        makePlayer(pid(), 'Enzo Millot',            'CM', 22, 74, 'FRA'),
        makePlayer(pid(), 'Fabian Rieder',          'CM', 22, 74, 'SUI'),
        makePlayer(pid(), 'Luca Pfeiffer',          'ST', 26, 72, 'GER'),
    ]},
    { id: 'bsc', name: 'Union Berlin',          short: 'BSC', color: '#CC0000', colorAlt: '#FFFFFF', prestige: 72, budget: Math.round(Math.pow(Math.max(0,72-40),2)*45000), stadium: 'An der Alten Forsterei',     capacity: 22012, squad: [
        makePlayer(pid(), 'Frederik Ronnow',        'GK', 31, 78, 'DEN'),
        makePlayer(pid(), 'Lennart Grill',          'GK', 25, 68, 'GER'),
        makePlayer(pid(), 'Julian Ryerson',         'RB', 27, 73, 'NOR'),
        makePlayer(pid(), 'Diogo Leite',            'CB', 24, 76, 'POR'),
        makePlayer(pid(), 'Danilho Doekhi',         'CB', 25, 76, 'NED'),
        makePlayer(pid(), 'Timo Baumgartl',         'CB', 27, 75, 'GER'),
        makePlayer(pid(), 'Niko Giesselmann',       'LB', 30, 73, 'GER'),
        makePlayer(pid(), 'Christopher Trimmel',    'RB', 36, 74, 'AUT'),
        makePlayer(pid(), 'Rani Khedira',           'CDM',29, 76, 'GER'),
        makePlayer(pid(), 'Andras Schafer',         'CM', 24, 74, 'HUN'),
        makePlayer(pid(), 'Aissa Laidouni',         'CM', 27, 74, 'TUN'),
        makePlayer(pid(), 'Sheraldo Becker',        'LW', 29, 76, 'SUR'),
        makePlayer(pid(), 'Kevin Volland',          'ST', 32, 76, 'GER'),
        makePlayer(pid(), 'Yorbe Vertessen',        'RW', 22, 72, 'BEL'),
        makePlayer(pid(), 'Jordan Siebatcheu',      'ST', 28, 75, 'USA'),
        makePlayer(pid(), 'Janik Haberer',          'CM', 29, 74, 'GER'),
        makePlayer(pid(), 'Milos Pantovic',         'CM', 27, 72, 'SRB'),
        makePlayer(pid(), 'Morten Thorsby',         'CM', 27, 72, 'NOR'),
    ]},
    { id: 'scf', name: 'SC Freiburg',           short: 'SCF', color: '#CC0000', colorAlt: '#000000', prestige: 71, budget: Math.round(Math.pow(Math.max(0,71-40),2)*45000), stadium: 'Europa-Park Stadion',        capacity: 34700, squad: [
        makePlayer(pid(), 'Mark Flekken',           'GK', 30, 78, 'NED'),
        makePlayer(pid(), 'Benjamin Uphoff',        'GK', 29, 70, 'GER'),
        makePlayer(pid(), 'Kiliann Sildillia',      'RB', 21, 74, 'FRA'),
        makePlayer(pid(), 'Philipp Lienhart',       'CB', 28, 77, 'AUT'),
        makePlayer(pid(), 'Manuel Gulde',           'CB', 31, 74, 'GER'),
        makePlayer(pid(), 'Matthias Ginter',        'CB', 29, 79, 'GER'),
        makePlayer(pid(), 'Christian Gunter',       'LB', 31, 76, 'GER'),
        makePlayer(pid(), 'Nicolas Hofler',         'CDM',27, 76, 'GER'),
        makePlayer(pid(), 'Maximilian Eggestein',   'CM', 26, 75, 'GER'),
        makePlayer(pid(), 'Ritsu Doan',             'RW', 25, 77, 'JPN'),
        makePlayer(pid(), 'Vincenzo Grifo',         'LW', 30, 78, 'GER'),
        makePlayer(pid(), 'Roland Sallai',          'RW', 26, 77, 'HUN'),
        makePlayer(pid(), 'Lucas Holer',            'ST', 28, 74, 'GER'),
        makePlayer(pid(), 'Kevin Schade',           'LW', 22, 75, 'GER'),
        makePlayer(pid(), 'Michael Gregoritsch',    'ST', 29, 76, 'AUT'),
        makePlayer(pid(), 'Nils Petersen',          'ST', 34, 74, 'GER'),
        makePlayer(pid(), 'Jordy Makengo',          'CM', 22, 72, 'FRA'),
        makePlayer(pid(), 'Noah Weisshaupt',        'RW', 22, 73, 'GER'),
    ]},
    { id: 'wob', name: 'Wolfsburg',             short: 'WOB', color: '#65B32E', colorAlt: '#000000', prestige: 71, budget: Math.round(Math.pow(Math.max(0,71-40),2)*45000), stadium: 'Volkswagen Arena',           capacity: 30000, squad: [
        makePlayer(pid(), 'Koen Casteels',          'GK', 32, 82, 'BEL'),
        makePlayer(pid(), 'Kamil Grabara',          'GK', 26, 75, 'POL'),
        makePlayer(pid(), 'Kevin Mbabu',            'RB', 28, 76, 'SUI'),
        makePlayer(pid(), 'Ridle Baku',             'RB', 26, 79, 'GEO'),
        makePlayer(pid(), 'John Anthony Brooks',    'CB', 31, 79, 'USA'),
        makePlayer(pid(), 'Sebastiaan Bornauw',     'CB', 25, 78, 'BEL'),
        makePlayer(pid(), 'Luca van den Berg',      'CB', 22, 77, 'NED'),
        makePlayer(pid(), 'Yannick Gerhardt',       'LB', 29, 77, 'GER'),
        makePlayer(pid(), 'Jerome Roussillon',      'LB', 28, 77, 'FRA'),
        makePlayer(pid(), 'Josuha Guilavogui',      'CDM',34, 77, 'GUI'),
        makePlayer(pid(), 'Maximilian Arnold',      'CDM',29, 79, 'GER'),
        makePlayer(pid(), 'Mattias Svanberg',       'CM', 25, 75, 'SWE'),
        makePlayer(pid(), 'Max Kruse',              'CAM',36, 76, 'GER'),
        makePlayer(pid(), 'Patrick Wimmer',         'CM', 24, 76, 'AUT'),
        makePlayer(pid(), 'Lukas Nmecha',           'ST', 25, 79, 'GER'),
        makePlayer(pid(), 'Jonas Wind',             'ST', 25, 76, 'DEN'),
        makePlayer(pid(), 'Dodi Lukebakio',         'RW', 27, 78, 'BEL'),
        makePlayer(pid(), 'Kamil Jozwiak',          'RW', 27, 74, 'POL'),
    ]},
    { id: 'bmg', name: 'B. Monchengladbach',    short: 'BMG', color: '#000000', colorAlt: '#FFFFFF', prestige: 70, budget: Math.round(Math.pow(Math.max(0,70-40),2)*45000), stadium: 'Borussia-Park',              capacity: 54042, squad: [
        makePlayer(pid(), 'Jonas Omlin',            'GK', 30, 78, 'SUI'),
        makePlayer(pid(), 'Jan Olschowsky',         'GK', 22, 68, 'GER'),
        makePlayer(pid(), 'Stefan Lainer',          'RB', 31, 77, 'AUT'),
        makePlayer(pid(), 'Nico Elvedi',            'CB', 27, 79, 'SUI'),
        makePlayer(pid(), 'Ko Itakura',             'CB', 27, 76, 'JPN'),
        makePlayer(pid(), 'Marvin Friedrich',       'CB', 28, 74, 'GER'),
        makePlayer(pid(), 'Ramy Bensebaini',        'LB', 28, 78, 'ALG'),
        makePlayer(pid(), 'Christoph Kramer',       'CDM',32, 76, 'GER'),
        makePlayer(pid(), 'Florian Neuhaus',        'CM', 26, 77, 'GER'),
        makePlayer(pid(), 'Kouadio Kone',           'CM', 22, 75, 'FRA'),
        makePlayer(pid(), 'Hannes Wolf',            'CM', 24, 74, 'AUT'),
        makePlayer(pid(), 'Alassane Plea',          'ST', 30, 78, 'FRA'),
        makePlayer(pid(), 'Marcus Thuram',          'ST', 26, 81, 'FRA'),
        makePlayer(pid(), 'Jonas Hofmann',          'RW', 31, 78, 'GER'),
        makePlayer('Nathan N\'Goumou',       'LW', 22, 72, 'CMR', 78),
        makePlayer(pid(), 'Joe Scally',             'RB', 21, 73, 'USA'),
        makePlayer(pid(), 'Luca Netz',              'LB', 21, 74, 'GER'),
        makePlayer(pid(), 'Lars Stindl',            'CAM',35, 77, 'GER'),
    ]},
    { id: 'tsg', name: 'Hoffenheim',            short: 'TSG', color: '#1369AC', colorAlt: '#FFFFFF', prestige: 69, budget: Math.round(Math.pow(Math.max(0,69-40),2)*45000), stadium: 'PreZero Arena',              capacity: 30150, squad: [
        makePlayer(pid(), 'Oliver Baumann',         'GK', 33, 78, 'GER'),
        makePlayer(pid(), 'Luca Philipp',           'GK', 24, 67, 'GER'),
        makePlayer(pid(), 'Pavel Kaderabek',        'RB', 31, 75, 'CZE'),
        makePlayer(pid(), 'Kevin Akpoguma',         'CB', 28, 75, 'GER'),
        makePlayer(pid(), 'Ozan Kabak',             'CB', 24, 75, 'TUR'),
        makePlayer(pid(), 'Ermin Bicakcic',         'CB', 33, 72, 'BIH'),
        makePlayer(pid(), 'David Raum',             'LB', 25, 78, 'GER'),
        makePlayer(pid(), 'Florian Grillitsch',     'CM', 28, 76, 'AUT'),
        makePlayer(pid(), 'Christoph Baumgartner',  'CM', 24, 76, 'AUT'),
        makePlayer(pid(), 'Robert Skov',            'RW', 27, 74, 'DEN'),
        makePlayer(pid(), 'Georginio Rutter',       'ST', 22, 76, 'FRA'),
        makePlayer(pid(), 'Jacob Bruun Larsen',     'LW', 25, 73, 'DEN'),
        makePlayer(pid(), 'Munas Dabbur',           'ST', 31, 74, 'ISR'),
        makePlayer(pid(), 'Andrej Kramaric',        'ST', 32, 80, 'CRO'),
        makePlayer(pid(), 'Tom Bischof',            'CM', 19, 72, 'GER'),
        makePlayer('Stanley N\'Soki',        'LB', 27, 71, 'FRA', 73),
        makePlayer(pid(), 'Grischa Promel',         'CM', 29, 74, 'GER'),
        makePlayer(pid(), 'Angelo Stiller',         'CDM',23, 74, 'GER'),
    ]},
    { id: 'svw', name: 'Werder Bremen',         short: 'SVW', color: '#009F4D', colorAlt: '#FFFFFF', prestige: 68, budget: Math.round(Math.pow(Math.max(0,68-40),2)*45000), stadium: 'Weser-Stadion',              capacity: 42100, squad: [
        makePlayer(pid(), 'Jiri Pavlenka',          'GK', 31, 77, 'CZE'),
        makePlayer(pid(), 'Michael Zetterer',       'GK', 28, 70, 'GER'),
        makePlayer(pid(), 'Mitchell Weiser',        'RB', 29, 73, 'GER'),
        makePlayer(pid(), 'Felix Agu',              'RB', 23, 72, 'GER'),
        makePlayer(pid(), 'Milos Veljkovic',        'CB', 28, 75, 'SRB'),
        makePlayer(pid(), 'Omer Toprak',            'CB', 33, 74, 'GER'),
        makePlayer(pid(), 'Niklas Stark',           'CB', 28, 76, 'GER'),
        makePlayer(pid(), 'Anthony Jung',           'LB', 31, 73, 'GER'),
        makePlayer(pid(), 'Ilia Gruev',             'CDM',22, 73, 'BUL'),
        makePlayer(pid(), 'Davy Klaassen',          'CM', 30, 77, 'NED'),
        makePlayer(pid(), 'Romano Schmid',          'CM', 23, 74, 'AUT'),
        makePlayer(pid(), 'Marvin Ducksch',         'ST', 29, 77, 'GER'),
        makePlayer(pid(), 'Oliver Burke',           'RW', 26, 72, 'SCO'),
        makePlayer(pid(), 'Niclas Fullkrug',        'ST', 30, 79, 'GER'),
        makePlayer(pid(), 'Justin Njinmah',         'LW', 21, 72, 'GER'),
        makePlayer(pid(), 'Eren Dinkci',            'ST', 21, 70, 'GER'),
        makePlayer(pid(), 'Jens Stage',             'CM', 27, 72, 'DEN'),
        makePlayer(pid(), 'Christian Groß',         'CDM',34, 73, 'GER'),
    ]},
    { id: 'm05', name: 'Mainz',                 short: 'M05', color: '#C8102E', colorAlt: '#FFFFFF', prestige: 65, budget: Math.round(Math.pow(Math.max(0,65-40),2)*45000), stadium: 'Mewa Arena',                 capacity: 34034, squad: [
        makePlayer(pid(), 'Robin Zentner',          'GK', 29, 76, 'GER'),
        makePlayer(pid(), 'Finn Dahmen',            'GK', 26, 69, 'GER'),
        makePlayer(pid(), 'Stefan Bell',            'CB', 32, 76, 'GER'),
        makePlayer(pid(), 'Maxim Leitsch',          'CB', 25, 74, 'GER'),
        makePlayer(pid(), 'Moussa Niakhate',        'CB', 27, 75, 'SEN'),
        makePlayer(pid(), 'Silvan Widmer',          'RB', 30, 75, 'SUI'),
        makePlayer(pid(), 'Phillipp Mwene',         'LB', 29, 73, 'AUT'),
        makePlayer(pid(), 'Leandro Barreiro',       'CDM',23, 73, 'LUX'),
        makePlayer(pid(), 'Dominik Kohr',           'CM', 29, 73, 'GER'),
        makePlayer(pid(), 'Aymen Barkok',           'CM', 25, 72, 'MAR'),
        makePlayer(pid(), 'Jonathan Burkardt',      'ST', 23, 74, 'GER'),
        makePlayer(pid(), 'Ludovic Ajorque',        'ST', 30, 75, 'FRA'),
        makePlayer(pid(), 'Karim Onisiwo',          'RW', 31, 72, 'AUT'),
        makePlayer(pid(), 'Anthony Caci',           'RB', 25, 71, 'FRA'),
        makePlayer(pid(), 'Nelson Weiper',          'ST', 18, 68, 'GER'),
        makePlayer(pid(), 'Edimilson Fernandes',    'CM', 27, 72, 'SUI'),
        makePlayer(pid(), 'Marcus Ingvartsen',      'ST', 27, 72, 'DEN'),
        makePlayer(pid(), 'Lee Jae-sung',           'CM', 31, 74, 'KOR'),
    ]},
    { id: 'koe', name: 'Koln',                  short: 'KOE', color: '#E10710', colorAlt: '#FFFFFF', prestige: 65, budget: Math.round(Math.pow(Math.max(0,65-40),2)*45000), stadium: 'RheinEnergieStadion',        capacity: 50000, squad: [
        makePlayer(pid(), 'Marvin Schwabe',         'GK', 28, 76, 'GER'),
        makePlayer(pid(), 'Thomas Kessler',         'GK', 37, 68, 'GER'),
        makePlayer(pid(), 'Benno Schmitz',          'RB', 29, 73, 'GER'),
        makePlayer(pid(), 'Timo Hubers',            'CB', 26, 73, 'GER'),
        makePlayer(pid(), 'Luca Kilian',            'CB', 24, 73, 'GER'),
        makePlayer(pid(), 'Jeff Chabot',            'CB', 25, 73, 'FRA'),
        makePlayer(pid(), 'Jonas Hector',           'LB', 33, 76, 'GER'),
        makePlayer(pid(), 'Salih Ozcan',            'CDM',26, 74, 'GER'),
        makePlayer(pid(), 'Florian Kainz',          'LW', 30, 76, 'AUT'),
        makePlayer(pid(), 'Ondrej Duda',            'CM', 28, 73, 'SVK'),
        makePlayer(pid(), 'Dejan Ljubicic',         'CM', 25, 72, 'AUT'),
        makePlayer(pid(), 'Eric Martel',            'CM', 21, 72, 'GER'),
        makePlayer(pid(), 'Mark Uth',               'ST', 32, 73, 'GER'),
        makePlayer(pid(), 'Tim Lemperle',           'ST', 21, 71, 'GER'),
        makePlayer(pid(), 'Davie Selke',            'ST', 28, 73, 'GER'),
        makePlayer(pid(), 'Florian Dietz',          'ST', 24, 71, 'GER'),
        makePlayer(pid(), 'Sargis Adamyan',         'LW', 30, 71, 'ARM'),
        makePlayer(pid(), 'Kingsley Schindler',     'RW', 29, 71, 'GER'),
    ]},
    { id: 'boc', name: 'Bochum',                short: 'BOC', color: '#003DA5', colorAlt: '#FFFFFF', prestige: 63, budget: Math.round(Math.pow(Math.max(0,63-40),2)*45000), stadium: 'Vonovia Ruhrstadion',        capacity: 27599, squad: [
        makePlayer(pid(), 'Manuel Riemann',         'GK', 33, 74, 'GER'),
        makePlayer(pid(), 'Michael Esser',          'GK', 36, 67, 'GER'),
        makePlayer(pid(), 'Cristian Gamboa',        'RB', 34, 71, 'CRC'),
        makePlayer(pid(), 'Ivan Ordets',            'CB', 29, 72, 'UKR'),
        makePlayer(pid(), 'Erhan Masovic',          'CB', 24, 72, 'GER'),
        makePlayer(pid(), 'Dominique Heintz',       'CB', 30, 71, 'GER'),
        makePlayer(pid(), 'Danilo Soares',          'LB', 32, 71, 'BRA'),
        makePlayer(pid(), 'Anthony Losilla',        'CDM',36, 72, 'FRA'),
        makePlayer(pid(), 'Patrick Osterhage',      'CM', 24, 71, 'GER'),
        makePlayer(pid(), 'Kevin Stoger',           'CM', 29, 72, 'AUT'),
        makePlayer(pid(), 'Tom Weilandt',           'CM', 32, 70, 'GER'),
        makePlayer(pid(), 'Philipp Hofmann',        'ST', 30, 73, 'GER'),
        makePlayer(pid(), 'Simon Zoller',           'ST', 32, 71, 'GER'),
        makePlayer(pid(), 'Jordi Osei-Tutu',        'RB', 25, 71, 'GHA'),
        makePlayer(pid(), 'Takuma Asano',           'RW', 29, 71, 'JPN'),
        makePlayer(pid(), 'Moritz Broschinski',     'LW', 22, 69, 'GER'),
        makePlayer(pid(), 'Christopher Antwi-Adjei','RW', 29, 71, 'GHA'),
        makePlayer(pid(), 'Soma Novothny',          'ST', 27, 69, 'HUN'),
    ]},
    { id: 'fca', name: 'Augsburg',              short: 'FCA', color: '#BA3535', colorAlt: '#007A33', prestige: 63, budget: Math.round(Math.pow(Math.max(0,63-40),2)*45000), stadium: 'WWK Arena',                  capacity: 30660, squad: [
        makePlayer(pid(), 'Rafal Gikiewicz',        'GK', 36, 74, 'POL'),
        makePlayer(pid(), 'Tomas Koubek',           'GK', 31, 70, 'CZE'),
        makePlayer(pid(), 'Robert Gumny',           'RB', 25, 72, 'POL'),
        makePlayer(pid(), 'Felix Uduokhai',         'CB', 26, 74, 'GER'),
        makePlayer(pid(), 'Jeffrey Gouweleeuw',     'CB', 32, 75, 'NED'),
        makePlayer(pid(), 'Reece Oxford',           'CB', 25, 73, 'ENG'),
        makePlayer(pid(), 'Iago',                   'LB', 28, 73, 'ESP'),
        makePlayer(pid(), 'Mads Pedersen',          'LB', 27, 74, 'DEN'),
        makePlayer(pid(), 'Carlos Gruezo',          'CDM',28, 72, 'ECU'),
        makePlayer(pid(), 'Elvis Rexhbecaj',        'CM', 25, 72, 'GER'),
        makePlayer(pid(), 'Ruben Vargas',           'LW', 25, 74, 'SUI'),
        makePlayer(pid(), 'Ermedin Demirovic',      'ST', 25, 73, 'BIH'),
        makePlayer(pid(), 'Andre Hahn',             'RW', 32, 72, 'GER'),
        makePlayer(pid(), 'Arne Engels',            'CM', 21, 72, 'BEL'),
        makePlayer(pid(), 'Frederic Jensen',        'RW', 27, 71, 'DEN'),
        makePlayer(pid(), 'Tobias Strobl',          'CDM',33, 72, 'GER'),
        makePlayer(pid(), 'Alfred Finnbogason',     'ST', 33, 72, 'ISL'),
        makePlayer(pid(), 'Michael Gregoritsch',    'ST', 29, 74, 'AUT'),
    ]},
    { id: 'fcH', name: 'Heidenheim',            short: 'FCH', color: '#CC0000', colorAlt: '#FFFFFF', prestige: 59, budget: Math.round(Math.pow(Math.max(0,59-40),2)*45000), stadium: 'Voith Arena',                capacity: 15000, squad: [
        makePlayer(pid(), 'Kevin Muller',           'GK', 31, 72, 'GER'),
        makePlayer(pid(), 'Vitus Eichler',          'GK', 25, 64, 'GER'),
        makePlayer(pid(), 'Patrick Mainka',         'CB', 28, 71, 'GER'),
        makePlayer(pid(), 'Jan Schoppner',          'CB', 29, 70, 'GER'),
        makePlayer(pid(), 'Oliver Husing',          'CB', 29, 70, 'GER'),
        makePlayer(pid(), 'Marnon Busch',           'RB', 28, 69, 'GER'),
        makePlayer(pid(), 'Jonas Fohrenbach',       'LB', 26, 69, 'GER'),
        makePlayer(pid(), 'Norman Theuerkauf',      'LB', 31, 68, 'GER'),
        makePlayer(pid(), 'Andreas Geipl',          'CDM',32, 69, 'GER'),
        makePlayer(pid(), 'Niklas Dorsch',          'CM', 26, 71, 'GER'),
        makePlayer(pid(), 'Lennard Maloney',        'CM', 23, 70, 'USA'),
        makePlayer(pid(), 'Tobias Mohr',            'LW', 27, 70, 'GER'),
        makePlayer(pid(), 'Denis Thomalla',         'RW', 28, 69, 'GER'),
        makePlayer(pid(), 'Jan-Niklas Beste',       'LW', 25, 72, 'GER'),
        makePlayer(pid(), 'Robert Glatzel',         'ST', 29, 73, 'GER'),
        makePlayer(pid(), 'Tim Kleindienst',        'ST', 27, 71, 'GER'),
        makePlayer(pid(), 'Stefan Schimmer',        'ST', 30, 69, 'GER'),
        makePlayer(pid(), 'Kevin Sessa',            'CM', 27, 69, 'GER'),
    ]},
    { id: 'd98', name: 'Darmstadt',             short: 'D98', color: '#003DA5', colorAlt: '#FFFFFF', prestige: 57, budget: Math.round(Math.pow(Math.max(0,57-40),2)*45000), stadium: 'Jonathan Heimes-Stadion',    capacity: 17000, squad: [
        makePlayer(pid(), 'Marcel Schuhen',         'GK', 30, 70, 'GER'),
        makePlayer(pid(), 'Florian Stritzel',       'GK', 26, 64, 'GER'),
        makePlayer(pid(), 'Patric Pfeiffer',        'CB', 24, 68, 'GER'),
        makePlayer(pid(), 'Clemens Riedel',         'CB', 29, 68, 'GER'),
        makePlayer(pid(), 'Fabian Schnellhardt',    'CB', 28, 68, 'GER'),
        makePlayer(pid(), 'Bartol Franjic',         'CB', 25, 67, 'CRO'),
        makePlayer(pid(), 'Bernd Holzenbein',       'LB', 28, 67, 'GER'),
        makePlayer(pid(), 'Frank Ronstadt',         'RB', 27, 67, 'GER'),
        makePlayer(pid(), 'Klaus Gjasula',          'CDM',31, 69, 'ALB'),
        makePlayer(pid(), 'Tobias Kempe',           'CM', 33, 70, 'GER'),
        makePlayer(pid(), 'Emir Karic',             'CM', 25, 67, 'BIH'),
        makePlayer(pid(), 'Mathias Honsak',         'LW', 27, 69, 'NOR'),
        makePlayer(pid(), 'Tim Skarke',             'LW', 26, 68, 'GER'),
        makePlayer(pid(), 'Braydon Manu',           'RW', 26, 68, 'GHA'),
        makePlayer(pid(), 'Luca Pfeiffer',          'ST', 26, 70, 'GER'),
        makePlayer(pid(), 'Aaron Seydel',           'ST', 29, 68, 'GER'),
        makePlayer(pid(), 'Fraser Hornby',          'ST', 24, 67, 'SCO'),
        makePlayer(pid(), 'Oscar Vilhelmsson',      'ST', 21, 66, 'SWE'),
    ]},
];

const BUNDESLIGA2_TEAMS = [
    { id: 'hsv',  name: 'Hamburg SV',           short: 'HSV', color: '#009EE0', colorAlt: '#FFFFFF', prestige: 65, budget: Math.round(Math.pow(Math.max(0,65-40),2)*45000), stadium: 'Volksparkstadion',          capacity: 57000, squad: [
        makePlayer(pid(), 'Daniel Heuer Fernandes', 'GK', 27, 74, 'GER'),
        makePlayer(pid(), 'Sven Schumann',          'GK', 26, 66, 'GER'),
        makePlayer(pid(), 'Josha Vagnoman',         'RB', 23, 73, 'GER'),
        makePlayer(pid(), 'Sebastian Schonlau',     'CB', 29, 72, 'GER'),
        makePlayer(pid(), 'Guilherme Ramos',        'CB', 24, 71, 'BRA'),
        makePlayer(pid(), 'Jonas David',            'CB', 23, 70, 'GER'),
        makePlayer(pid(), 'Miro Muheim',            'LB', 23, 71, 'SUI'),
        makePlayer(pid(), 'Jonas Meffert',          'CDM',29, 72, 'GER'),
        makePlayer(pid(), 'Sonny Kittel',           'CM', 29, 73, 'GER'),
        makePlayer(pid(), 'Ludovit Reis',           'CM', 23, 72, 'NED'),
        makePlayer(pid(), 'Laszlo Benes',           'CM', 26, 72, 'SVK'),
        makePlayer(pid(), 'Ransford Konigsdorffer', 'LW', 22, 72, 'GHA'),
        makePlayer(pid(), 'Robert Glatzel',         'ST', 29, 73, 'GER'),
        makePlayer(pid(), 'Levin Oztunali',         'RW', 27, 71, 'GER'),
        makePlayer(pid(), 'Jean-Luc Dompe',         'LW', 27, 71, 'FRA'),
        makePlayer(pid(), 'Bakery Jatta',           'RW', 25, 70, 'GAM'),
        makePlayer(pid(), 'Davie Selke',            'ST', 28, 71, 'GER'),
    ]},
    { id: 's04',  name: 'Schalke',              short: 'S04', color: '#004B9A', colorAlt: '#FFFFFF', prestige: 65, budget: Math.round(Math.pow(Math.max(0,65-40),2)*45000), stadium: 'Veltins-Arena',             capacity: 62271, squad: [
        makePlayer(pid(), 'Ralf Fahrmann',          'GK', 34, 73, 'GER'),
        makePlayer(pid(), 'Alexander Schwolow',     'GK', 31, 72, 'GER'),
        makePlayer(pid(), 'Henning Matriciani',     'RB', 23, 71, 'GER'),
        makePlayer(pid(), 'Moritz Jenz',            'CB', 24, 73, 'GER'),
        makePlayer(pid(), 'Leo Greiml',             'CB', 23, 71, 'AUT'),
        makePlayer(pid(), 'Thomas Ouwejan',         'LB', 26, 71, 'NED'),
        makePlayer(pid(), 'Luca Matriciani',        'LB', 23, 70, 'GER'),
        makePlayer(pid(), 'Martin Wasinski',        'CDM',22, 71, 'POL'),
        makePlayer(pid(), 'Tom Krauss',             'CM', 22, 72, 'GER'),
        makePlayer(pid(), 'Florent Mollet',         'CM', 31, 72, 'FRA'),
        makePlayer(pid(), 'Rodrigo Zalazar',        'CM', 24, 71, 'URU'),
        makePlayer(pid(), 'Danny Latza',            'CDM',33, 72, 'GER'),
        makePlayer(pid(), 'Tobias Mohr',            'LW', 27, 70, 'GER'),
        makePlayer(pid(), 'Marius Bulter',          'LW', 30, 71, 'GER'),
        makePlayer(pid(), 'Simon Terodde',          'ST', 35, 74, 'GER'),
        makePlayer(pid(), 'Kenan Karaman',          'ST', 29, 73, 'GER'),
        makePlayer(pid(), 'Justin Heekeren',        'GK', 23, 70, 'GER'),
    ]},
    { id: 'hbt',  name: 'Hertha Berlin',        short: 'HBT', color: '#003DA5', colorAlt: '#FFFFFF', prestige: 64, budget: Math.round(Math.pow(Math.max(0,64-40),2)*45000), stadium: 'Olympiastadion',            capacity: 74475, squad: [
        makePlayer(pid(), 'Oliver Christensen',     'GK', 23, 72, 'DEN'),
        makePlayer(pid(), 'Marcel Lotka',           'GK', 21, 68, 'GER'),
        makePlayer(pid(), 'Jonjoe Kenny',           'RB', 26, 72, 'ENG'),
        makePlayer(pid(), 'Marc Oliver Kempf',      'CB', 28, 73, 'GER'),
        makePlayer(pid(), 'Dedryck Boyata',         'CB', 33, 73, 'BEL'),
        makePlayer(pid(), 'Agustin Rogel',          'CB', 25, 71, 'URU'),
        makePlayer(pid(), 'Marvin Plattenhardt',    'LB', 31, 73, 'GER'),
        makePlayer(pid(), 'Lucas Tousart',          'CDM',27, 73, 'FRA'),
        makePlayer(pid(), 'Suat Serdar',            'CM', 26, 73, 'GER'),
        makePlayer(pid(), 'Jean-Paul Boetius',      'CM', 29, 72, 'NED'),
        makePlayer(pid(), 'Dodi Lukebakio',         'LW', 26, 73, 'BEL'),
        makePlayer(pid(), 'Marco Richter',          'RW', 25, 72, 'GER'),
        makePlayer(pid(), 'Jessic Ngankam',         'LW', 22, 71, 'GER'),
        makePlayer(pid(), 'Chidera Ejuke',          'LW', 25, 70, 'NGA'),
        makePlayer(pid(), 'Wilfried Kanga',         'ST', 24, 71, 'SUI'),
        makePlayer(pid(), 'Davie Selke',            'ST', 28, 72, 'GER'),
        makePlayer(pid(), 'Kevin-Prince Boateng',   'CM', 36, 71, 'GHA'),
    ]},
    { id: 'stp',  name: 'FC St. Pauli',         short: 'STP', color: '#964B00', colorAlt: '#FFFFFF', prestige: 63, budget: Math.round(Math.pow(Math.max(0,63-40),2)*45000), stadium: 'Millerntor-Stadion',        capacity: 29546, squad: [
        makePlayer(pid(), 'Nikola Vasilj',          'GK', 27, 71, 'BIH'),
        makePlayer(pid(), 'Dennis Smarsch',         'GK', 25, 65, 'GER'),
        makePlayer(pid(), 'Manolis Saliakas',       'RB', 26, 69, 'GRE'),
        makePlayer(pid(), 'Leart Paqarada',         'LB', 28, 70, 'GER'),
        makePlayer(pid(), 'Jakov Medic',            'CB', 24, 69, 'CRO'),
        makePlayer(pid(), 'Adam Dzwigala',          'CB', 27, 68, 'POL'),
        makePlayer(pid(), 'Eric Smith',             'CB', 26, 68, 'SWE'),
        makePlayer(pid(), 'Johannes Eggestein',     'CM', 25, 70, 'GER'),
        makePlayer(pid(), 'Jackson Irvine',         'CM', 30, 71, 'AUS'),
        makePlayer(pid(), 'Morgan Guilavogui',      'CDM',29, 70, 'GNB'),
        makePlayer(pid(), 'Marcel Hartel',          'CM', 26, 71, 'GER'),
        makePlayer(pid(), 'Oladapo Afolabi',        'LW', 21, 68, 'GER'),
        makePlayer(pid(), 'Elias Saad',             'LW', 25, 70, 'LIB'),
        makePlayer(pid(), 'Omar Sahiti',            'RW', 23, 68, 'MKD'),
        makePlayer(pid(), 'Igor Matanovic',         'ST', 21, 70, 'GER'),
        makePlayer(pid(), 'Simon Makienok',         'ST', 33, 70, 'DEN'),
        makePlayer(pid(), 'David Otto',             'CM', 22, 67, 'GER'),
    ]},
    { id: 'f95',  name: 'Fortuna Dusseldorf',   short: 'F95', color: '#E10710', colorAlt: '#FFFFFF', prestige: 60, budget: Math.round(Math.pow(Math.max(0,60-40),2)*45000), stadium: 'Merkur Spiel-Arena',        capacity: 54600, squad: [
        makePlayer(pid(), 'Florian Kastenmeier',    'GK', 26, 70, 'GER'),
        makePlayer(pid(), 'Raphael Wolf',           'GK', 34, 66, 'GER'),
        makePlayer(pid(), 'Matthias Zimmermann',    'RB', 31, 71, 'GER'),
        makePlayer(pid(), 'Andre Hoffmann',         'CB', 30, 71, 'GER'),
        makePlayer(pid(), 'Jamil Siebert',          'CB', 25, 69, 'GER'),
        makePlayer(pid(), 'Leonardo Koutris',       'LB', 28, 68, 'GRE'),
        makePlayer(pid(), 'Kristoffer Peterson',    'LW', 28, 70, 'SWE'),
        makePlayer(pid(), 'Marcel Sobottka',        'CDM',29, 70, 'GER'),
        makePlayer(pid(), 'Shinta Appelkamp',       'CM', 23, 70, 'GER'),
        makePlayer(pid(), 'Ao Tanaka',              'CM', 24, 70, 'JPN'),
        makePlayer(pid(), 'Tim Oberdorf',           'CDM',21, 70, 'GER'),
        makePlayer(pid(), 'Christos Tzolis',        'LW', 22, 70, 'GRE'),
        makePlayer(pid(), 'Emmanuel Iyoha',         'RW', 26, 68, 'GER'),
        makePlayer(pid(), 'Nana Ampomah',           'LW', 27, 68, 'GHA'),
        makePlayer(pid(), 'Felix Klaus',            'RW', 29, 68, 'GER'),
        makePlayer(pid(), 'Rouven Hennings',        'ST', 35, 70, 'GER'),
        makePlayer(pid(), 'Dawid Kownacki',         'ST', 26, 70, 'POL'),
    ]},
    { id: 'h96',  name: 'Hannover 96',          short: 'H96', color: '#009B2A', colorAlt: '#000000', prestige: 62, budget: Math.round(Math.pow(Math.max(0,62-40),2)*45000), stadium: 'Heinz von Heiden Arena',    capacity: 49000, squad: [
        makePlayer(pid(), 'Ron-Robert Zieler',      'GK', 34, 72, 'GER'),
        makePlayer(pid(), 'Martin Hansen',          'GK', 33, 68, 'DEN'),
        makePlayer(pid(), 'Nico Neidhart',          'RB', 21, 68, 'GER'),
        makePlayer(pid(), 'Marcel Halstenberg',     'LB', 32, 72, 'GER'),
        makePlayer(pid(), 'Derrick Kohn',           'LB', 22, 70, 'GER'),
        makePlayer(pid(), 'Bright Arrey-Mbi',       'CB', 21, 70, 'GER'),
        makePlayer(pid(), 'Lars Lacroix',           'CB', 25, 69, 'GER'),
        makePlayer(pid(), 'Jannik Dehm',            'RB', 27, 69, 'GER'),
        makePlayer(pid(), 'Fabian Kunze',           'CM', 25, 69, 'GER'),
        makePlayer(pid(), 'Sei Muroya',             'RB', 27, 70, 'JPN'),
        makePlayer(pid(), 'Dzenis Burnic',          'CM', 26, 69, 'GER'),
        makePlayer(pid(), 'Cedric Teuchert',        'LW', 26, 70, 'GER'),
        makePlayer(pid(), 'Niklas Hult',            'LB', 31, 70, 'SWE'),
        makePlayer(pid(), 'Maximilian Beier',       'ST', 21, 71, 'GER'),
        makePlayer(pid(), 'Nicolo Tresoldi',        'ST', 21, 69, 'GER'),
        makePlayer(pid(), 'Enrico Valentini',       'RB', 32, 69, 'GER'),
        makePlayer(pid(), 'Trevor Treinen',         'CM', 21, 68, 'USA'),
    ]},
    { id: 'kil',  name: 'Holstein Kiel',        short: 'KIL', color: '#CC0000', colorAlt: '#003DA5', prestige: 59, budget: Math.round(Math.pow(Math.max(0,59-40),2)*45000), stadium: 'Holstein-Stadion',          capacity: 15034, squad: [
        makePlayer(pid(), 'Thomas Dahne',           'GK', 32, 69, 'GER'),
        makePlayer(pid(), 'Timon Weiner',           'GK', 23, 64, 'GER'),
        makePlayer(pid(), 'Julian Korb',            'RB', 30, 68, 'GER'),
        makePlayer(pid(), 'Marco Komenda',          'CB', 26, 68, 'GER'),
        makePlayer(pid(), 'Stefan Thesker',         'CB', 32, 68, 'GER'),
        makePlayer(pid(), 'Hauke Wahl',             'CB', 30, 67, 'GER'),
        makePlayer(pid(), 'Tom Rothe',              'LB', 19, 69, 'GER'),
        makePlayer(pid(), 'Aleksandar Ignjovski',   'LB', 35, 67, 'SRB'),
        makePlayer(pid(), 'Lewis Holtby',           'CM', 32, 69, 'GER'),
        makePlayer(pid(), 'Finn Porath',            'CM', 27, 69, 'GER'),
        makePlayer(pid(), 'Patrick Erras',          'CDM',29, 67, 'GER'),
        makePlayer(pid(), 'Phil Neumann',           'RB', 27, 66, 'GER'),
        makePlayer(pid(), 'Fabian Reese',           'LW', 25, 70, 'GER'),
        makePlayer(pid(), 'Mikkel Kirkegaard',      'RW', 27, 68, 'DEN'),
        makePlayer(pid(), 'Steven Skrzybski',       'LW', 30, 67, 'GER'),
        makePlayer(pid(), 'Shuto Machino',          'ST', 24, 70, 'JPN'),
        makePlayer(pid(), 'Benedikt Pichler',       'ST', 25, 67, 'AUT'),
    ]},
    { id: 'fcn',  name: 'Nurnberg',             short: 'FCN', color: '#CC0000', colorAlt: '#FFFFFF', prestige: 59, budget: Math.round(Math.pow(Math.max(0,59-40),2)*45000), stadium: 'Max-Morlock-Stadion',       capacity: 50000, squad: [
        makePlayer(pid(), 'Christian Mathenia',     'GK', 31, 69, 'GER'),
        makePlayer(pid(), 'Carl Klaus',             'GK', 24, 63, 'GER'),
        makePlayer(pid(), 'Enrico Valentini',       'RB', 32, 68, 'GER'),
        makePlayer(pid(), 'Tim Handwerker',         'LB', 25, 68, 'GER'),
        makePlayer(pid(), 'Christopher Schindler',  'CB', 33, 69, 'GER'),
        makePlayer(pid(), 'Asger Sorensen',         'CB', 27, 68, 'DEN'),
        makePlayer(pid(), 'Florian Hubner',         'CB', 31, 67, 'GER'),
        makePlayer(pid(), 'Taylan Antalyali',       'CDM',24, 68, 'GER'),
        makePlayer(pid(), 'Tom Krauss',             'CM', 22, 70, 'GER'),
        makePlayer(pid(), 'Nikola Dovedan',         'CM', 29, 68, 'GER'),
        makePlayer(pid(), 'Ondrej Petrak',          'CM', 30, 67, 'CZE'),
        makePlayer(pid(), 'Dennis Borkowski',       'RW', 21, 67, 'GER'),
        makePlayer(pid(), 'Lino Tempel',            'LW', 22, 67, 'GER'),
        makePlayer(pid(), 'Kwadwo Duah',            'RW', 26, 68, 'SUI'),
        makePlayer(pid(), 'Felix Lohkemper',        'ST', 28, 68, 'GER'),
        makePlayer(pid(), 'Erik Shuranov',          'ST', 22, 66, 'GER'),
        makePlayer(pid(), 'Lukas Schleimer',        'ST', 25, 65, 'GER'),
    ]},
    { id: 'ksl',  name: 'Kaiserslautern',       short: 'KSL', color: '#CC0000', colorAlt: '#FFFFFF', prestige: 58, budget: Math.round(Math.pow(Math.max(0,58-40),2)*45000), stadium: 'Fritz Walter Stadion',      capacity: 49850, squad: [
        makePlayer(pid(), 'Andreas Luthe',          'GK', 36, 67, 'GER'),
        makePlayer(pid(), 'Julian Krahl',           'GK', 24, 63, 'GER'),
        makePlayer(pid(), 'Jean Zimmer',            'RB', 29, 67, 'GER'),
        makePlayer(pid(), 'Kevin Kraus',            'CB', 30, 67, 'GER'),
        makePlayer(pid(), 'Boris Tomiak',           'CB', 25, 67, 'GER'),
        makePlayer(pid(), 'Anas Bakhat',            'CB', 23, 65, 'MAR'),
        makePlayer(pid(), 'Dominik Schad',          'LB', 29, 66, 'GER'),
        makePlayer(pid(), 'Finn Stermann',          'CDM',21, 65, 'GER'),
        makePlayer(pid(), 'Marlon Ritter',          'CM', 27, 67, 'GER'),
        makePlayer(pid(), 'Philipp Klement',        'CM', 31, 68, 'GER'),
        makePlayer(pid(), 'Christoph Hemlein',      'CM', 26, 65, 'GER'),
        makePlayer(pid(), 'Hendrick Zuck',          'LW', 30, 68, 'GER'),
        makePlayer(pid(), 'Kenny Redondo',          'LW', 28, 67, 'ESP'),
        makePlayer(pid(), 'Jannik Mause',           'RW', 26, 67, 'GER'),
        makePlayer(pid(), 'Mathias Honsak',         'LW', 27, 67, 'NOR'),
        makePlayer(pid(), 'Terrence Boyd',          'ST', 32, 67, 'USA'),
        makePlayer(pid(), 'Ragnar Ache',            'ST', 25, 67, 'GER'),
    ]},
    { id: 'pad',  name: 'Paderborn',            short: 'SCP', color: '#003DA5', colorAlt: '#FFFFFF', prestige: 57, budget: Math.round(Math.pow(Math.max(0,57-40),2)*45000), stadium: 'Benteler Arena',            capacity: 15000, squad: [
        makePlayer(pid(), 'Lukas Kwasniok',         'GK', 30, 67, 'GER'),
        makePlayer(pid(), 'Leopold Zingerle',       'GK', 28, 65, 'AUT'),
        makePlayer(pid(), 'Marcel Correia',         'LB', 28, 65, 'POR'),
        makePlayer(pid(), 'Kai Klefisch',           'LB', 23, 64, 'GER'),
        makePlayer(pid(), 'Jannis Heuer',           'CB', 24, 66, 'GER'),
        makePlayer(pid(), 'Uwe Hunemeier',          'CB', 36, 66, 'GER'),
        makePlayer(pid(), 'Julian Brown',           'CB', 25, 65, 'GER'),
        makePlayer(pid(), 'Thilo Leugers',          'CB', 29, 64, 'GER'),
        makePlayer(pid(), 'Klaus Gjasula',          'CDM',31, 66, 'ALB'),
        makePlayer(pid(), 'Ron Schallenberg',       'CM', 23, 66, 'GER'),
        makePlayer(pid(), 'Christoph Hemlein',      'CM', 26, 65, 'GER'),
        makePlayer(pid(), 'Maximilian Thalhammer',  'CM', 26, 65, 'GER'),
        makePlayer(pid(), 'Florent Muslija',        'RW', 24, 67, 'KVX'),
        makePlayer(pid(), 'Sirlord Conteh',         'LW', 27, 65, 'GER'),
        makePlayer(pid(), 'Jesper Verlaat',         'CB', 28, 65, 'NED'),
        makePlayer(pid(), 'Felix Platte',           'ST', 27, 67, 'GER'),
        makePlayer(pid(), 'Sven Michel',            'ST', 33, 67, 'GER'),
    ]},
    { id: 'ksc',  name: 'Karlsruher SC',        short: 'KSC', color: '#003DA5', colorAlt: '#FFFFFF', prestige: 57, budget: Math.round(Math.pow(Math.max(0,57-40),2)*45000), stadium: 'BBBank Wildpark',           capacity: 34301, squad: [
        makePlayer(pid(), 'Marius Gersbeck',        'GK', 29, 67, 'GER'),
        makePlayer(pid(), 'Benjamin Uphoff',        'GK', 29, 66, 'GER'),
        makePlayer(pid(), 'Sebastian Jung',         'RB', 32, 65, 'GER'),
        makePlayer('Daniel O\'Shaughnessy', 'CB', 27, 66, 'FIN', 67),
        makePlayer(pid(), 'Florian Ballas',         'CB', 28, 65, 'GER'),
        makePlayer(pid(), 'Philip Heise',           'LB', 30, 65, 'GER'),
        makePlayer(pid(), 'Dirk Carlson',           'LB', 26, 66, 'LUX'),
        makePlayer(pid(), 'Jerome Gondorf',         'CM', 34, 66, 'GER'),
        makePlayer(pid(), 'Marvin Wanitzek',        'CM', 28, 68, 'GER'),
        makePlayer(pid(), 'Paul Nebel',             'CM', 21, 66, 'GER'),
        makePlayer(pid(), 'Luca Bolay',             'CM', 23, 64, 'GER'),
        makePlayer(pid(), 'Kyoung-rok Choi',        'LW', 24, 65, 'KOR'),
        makePlayer(pid(), 'Fabio Kaufmann',         'LW', 25, 65, 'GER'),
        makePlayer(pid(), 'Sven Froehling',         'RW', 28, 65, 'GER'),
        makePlayer(pid(), 'Malik Batmaz',           'RW', 22, 65, 'GER'),
        makePlayer(pid(), 'Mikkel Kaufmann',        'ST', 22, 67, 'DEN'),
        makePlayer(pid(), 'Simone Rapp',            'ST', 30, 65, 'SUI'),
    ]},
    { id: 'fcm',  name: 'Magdeburg',            short: 'FCM', color: '#0066CC', colorAlt: '#FFFFFF', prestige: 55, budget: Math.round(Math.pow(Math.max(0,55-40),2)*45000), stadium: 'MDCC-Arena',                capacity: 27000, squad: [
        makePlayer(pid(), 'Dominik Reimann',        'GK', 25, 66, 'GER'),
        makePlayer(pid(), 'Eike Bansen',            'GK', 25, 62, 'GER'),
        makePlayer(pid(), 'Connor Krempicki',       'RB', 26, 64, 'GER'),
        makePlayer(pid(), 'Herbert Bockhorn',       'RB', 28, 64, 'GER'),
        makePlayer(pid(), 'Silas Gnaka',            'CB', 22, 64, 'CIV'),
        makePlayer(pid(), 'Tobias Muller',          'CB', 28, 64, 'GER'),
        makePlayer(pid(), 'Alexander Bittroff',     'CB', 31, 63, 'GER'),
        makePlayer(pid(), 'Tatsuya Ito',            'LW', 27, 67, 'JPN'),
        makePlayer(pid(), 'Baris Atik',             'CM', 28, 66, 'GER'),
        makePlayer(pid(), 'Amara Conde',            'CM', 22, 65, 'GER'),
        makePlayer(pid(), 'Nico Hammann',           'CM', 27, 64, 'GER'),
        makePlayer(pid(), 'Andreas Muller',         'CM', 26, 63, 'GER'),
        makePlayer(pid(), 'Daniel Meyer',           'CDM',29, 63, 'GER'),
        makePlayer(pid(), 'Maximilian Franzke',     'RW', 26, 65, 'GER'),
        makePlayer(pid(), 'Tobias Schwede',         'RW', 30, 63, 'GER'),
        makePlayer(pid(), 'Luca Schuler',           'ST', 24, 65, 'GER'),
        makePlayer(pid(), 'Marvin Ingvartsen',      'ST', 27, 65, 'DEN'),
    ]},
    { id: 'enb',  name: 'Braunschweig',         short: 'ENB', color: '#FFFF00', colorAlt: '#003DA5', prestige: 54, budget: Math.round(Math.pow(Math.max(0,54-40),2)*45000), stadium: 'Eintracht-Stadion',         capacity: 25000, squad: [
        makePlayer(pid(), 'Patrick Drewes',         'GK', 30, 65, 'GER'),
        makePlayer(pid(), 'Jasmin Fejzic',          'GK', 35, 62, 'BIH'),
        makePlayer(pid(), 'Jan Lohmannsroben',      'RB', 26, 62, 'GER'),
        makePlayer(pid(), 'Lasse Schluter',         'CB', 24, 63, 'GER'),
        makePlayer(pid(), 'Daniele Ghilardi',       'CB', 23, 64, 'ITA'),
        makePlayer(pid(), 'Brian Behrendt',         'LB', 30, 62, 'GER'),
        makePlayer(pid(), 'Anton Donkor',           'LB', 25, 63, 'GER'),
        makePlayer(pid(), 'Jannis Nikolaou',        'CDM',24, 63, 'GER'),
        makePlayer(pid(), 'Immanuel Pherai',        'CM', 22, 64, 'NED'),
        makePlayer(pid(), 'Marc Pfitzner',          'CM', 28, 62, 'GER'),
        makePlayer(pid(), 'Martin Kobylanski',      'CM', 30, 63, 'POL'),
        makePlayer(pid(), 'Robin Krausse',          'CM', 28, 62, 'GER'),
        makePlayer(pid(), 'Enrique Pentzke',        'LW', 22, 62, 'GER'),
        makePlayer(pid(), 'Fabio Kaufmann',         'LW', 25, 62, 'GER'),
        makePlayer(pid(), 'Philipp Strompf',        'ST', 26, 63, 'GER'),
        makePlayer(pid(), 'Rayan Philippe',         'ST', 24, 63, 'FRA'),
        makePlayer(pid(), 'Mikkel Kaufmann',        'ST', 22, 64, 'DEN'),
    ]},
    { id: 'jah',  name: 'Regensburg',           short: 'JAH', color: '#CC0000', colorAlt: '#FFFFFF', prestige: 53, budget: Math.round(Math.pow(Math.max(0,53-40),2)*45000), stadium: 'Continental Arena',         capacity: 15255, squad: [
        makePlayer(pid(), 'Alexander Meyer',        'GK', 31, 65, 'GER'),
        makePlayer(pid(), 'Philipp Pentke',         'GK', 35, 62, 'GER'),
        makePlayer(pid(), 'Jonathan Meier',         'RB', 26, 62, 'GER'),
        makePlayer(pid(), 'Benedikt Gimber',        'CB', 27, 63, 'GER'),
        makePlayer(pid(), 'Florian Ballas',         'CB', 28, 63, 'GER'),
        makePlayer(pid(), 'Niklas Kastenhofer',     'LB', 25, 61, 'GER'),
        makePlayer(pid(), 'Tobias Janicke',         'LB', 26, 61, 'GER'),
        makePlayer(pid(), 'Scott Kennedy',          'CDM',28, 62, 'SCO'),
        makePlayer(pid(), 'Max Besuschkow',         'CM', 27, 62, 'GER'),
        makePlayer(pid(), 'Conrad Hilse',           'CM', 25, 61, 'GER'),
        makePlayer(pid(), 'Baris Atik',             'CM', 28, 63, 'GER'),
        makePlayer(pid(), 'Fridolin Wagner',        'RW', 23, 61, 'GER'),
        makePlayer(pid(), 'Christian Kuhlwetter',   'LW', 27, 62, 'GER'),
        makePlayer(pid(), 'Noel Futkeu',            'ST', 22, 63, 'GER'),
        makePlayer(pid(), 'Oskar Zawada',           'ST', 26, 62, 'GER'),
        makePlayer(pid(), 'Andreas Albers',         'ST', 33, 63, 'DEN'),
        makePlayer(pid(), 'Marco Gruttner',         'ST', 35, 63, 'GER'),
    ]},
    { id: 'els',  name: 'Elversberg',           short: 'ELS', color: '#003DA5', colorAlt: '#FFFFFF', prestige: 52, budget: Math.round(Math.pow(Math.max(0,52-40),2)*45000), stadium: 'Ursapharm Arena',           capacity: 12000, squad: [
        makePlayer(pid(), 'Nicolas Kristof',        'GK', 27, 63, 'LUX'),
        makePlayer(pid(), 'Luca Unbehaun',          'GK', 23, 61, 'GER'),
        makePlayer(pid(), 'Ole Klitten',            'RB', 24, 61, 'DEN'),
        makePlayer(pid(), 'Kevin Conrad',           'CB', 29, 62, 'GER'),
        makePlayer(pid(), 'Jannik Rochelt',         'CB', 26, 62, 'GER'),
        makePlayer(pid(), 'Luca Schnellbacher',     'CB', 26, 62, 'GER'),
        makePlayer(pid(), 'Luca Durholtz',          'LB', 24, 60, 'GER'),
        makePlayer(pid(), 'Robin Fellhauer',        'LB', 25, 60, 'GER'),
        makePlayer(pid(), 'Kevin Koffi',            'CDM',24, 62, 'CIV'),
        makePlayer(pid(), 'Jan Kirchhoff',          'CDM',32, 62, 'GER'),
        makePlayer(pid(), 'Semih Sahin',            'CM', 32, 62, 'GER'),
        makePlayer(pid(), 'Luis Coordes',           'CM', 23, 61, 'GER'),
        makePlayer(pid(), 'Eros Dacaj',             'LW', 21, 61, 'KVX'),
        makePlayer(pid(), 'Benjamin Kessel',        'RW', 27, 60, 'GER'),
        makePlayer(pid(), 'Luca Schnellbacher',     'RW', 25, 61, 'GER'),
        makePlayer(pid(), 'Noel Futkeu',            'ST', 22, 62, 'GER'),
        makePlayer(pid(), 'Philipp Strompf',        'ST', 27, 61, 'GER'),
    ]},
    { id: 'svw2', name: 'Wiesbaden',            short: 'SVW', color: '#003DA5', colorAlt: '#FFFFFF', prestige: 52, budget: Math.round(Math.pow(Math.max(0,52-40),2)*45000), stadium: 'BRITA-Arena',               capacity: 13000, squad: [
        makePlayer(pid(), 'Florian Stritzel',       'GK', 26, 63, 'GER'),
        makePlayer(pid(), 'Ralph Schaffler',        'GK', 27, 60, 'GER'),
        makePlayer(pid(), 'Maximilian Meisel',      'RB', 24, 61, 'GER'),
        makePlayer(pid(), 'Niklas Tauer',           'CB', 23, 63, 'GER'),
        makePlayer(pid(), 'Max Reinthaler',         'CB', 26, 62, 'AUT'),
        makePlayer(pid(), 'Bjarke Jacobsen',        'LB', 24, 61, 'DEN'),
        makePlayer(pid(), 'Manuel Stiefler',        'CDM',32, 62, 'GER'),
        makePlayer(pid(), 'John Patrick Strauss',   'CM', 25, 62, 'GER'),
        makePlayer(pid(), 'Tim Korzuschek',         'CM', 24, 61, 'GER'),
        makePlayer(pid(), 'Felix Muller',           'CM', 26, 61, 'GER'),
        makePlayer(pid(), 'Lukas Kunze',            'CM', 25, 60, 'GER'),
        makePlayer(pid(), 'Emre Demir',             'CM', 23, 60, 'GER'),
        makePlayer(pid(), 'Fabian Greilinger',      'LW', 22, 62, 'GER'),
        makePlayer(pid(), 'Hyun-Seok Hong',         'LW', 28, 61, 'KOR'),
        makePlayer(pid(), 'Marco Muller',           'RW', 28, 61, 'GER'),
        makePlayer(pid(), 'Ivan Prtajin',           'ST', 26, 63, 'CRO'),
        makePlayer(pid(), 'Sascha Mockenhaupt',     'CDM',32, 61, 'GER'),
    ]},
    { id: 'hnr',  name: 'Rostock',              short: 'HNR', color: '#003DA5', colorAlt: '#FFFFFF', prestige: 51, budget: Math.round(Math.pow(Math.max(0,51-40),2)*45000), stadium: 'Ostseestadion',             capacity: 29000, squad: [
        makePlayer(pid(), 'Markus Kolke',           'GK', 31, 63, 'GER'),
        makePlayer(pid(), 'Kevin Broll',            'GK', 29, 60, 'GER'),
        makePlayer(pid(), 'Ryan Malone',            'RB', 23, 61, 'GER'),
        makePlayer(pid(), 'Nils Froling',           'CB', 26, 61, 'GER'),
        makePlayer(pid(), 'Nico Neidhart',          'CB', 21, 62, 'GER'),
        makePlayer(pid(), 'Damian Rossbach',        'LB', 30, 61, 'GER'),
        makePlayer(pid(), 'Thomas Meissner',        'LB', 26, 61, 'GER'),
        makePlayer(pid(), 'Lukas Frode',            'CDM',28, 62, 'GER'),
        makePlayer(pid(), 'Dennis Dressel',         'CM', 25, 62, 'GER'),
        makePlayer(pid(), 'Svante Ingelsson',       'CM', 25, 61, 'SWE'),
        makePlayer(pid(), 'Thore Jacobsen',         'CM', 23, 60, 'GER'),
        makePlayer(pid(), 'Simon Rhein',            'LW', 23, 61, 'GER'),
        makePlayer(pid(), 'Nik Omladic',            'LW', 28, 61, 'SVN'),
        makePlayer(pid(), 'Kai Proger',             'RW', 30, 62, 'GER'),
        makePlayer(pid(), 'Bjorn Rother',           'RW', 27, 60, 'GER'),
        makePlayer(pid(), 'John Verhoek',           'ST', 34, 62, 'NED'),
        makePlayer(pid(), 'Mirnes Pepic',           'ST', 29, 61, 'BIH'),
    ]},
    { id: 'vfl',  name: 'Osnabruck',            short: 'VFL', color: '#000080', colorAlt: '#FFFFFF', prestige: 50, budget: Math.round(Math.pow(Math.max(0,50-40),2)*45000), stadium: 'Bremer Brucke',             capacity: 16068, squad: [
        makePlayer(pid(), 'Philipp Kuhn',           'GK', 28, 62, 'GER'),
        makePlayer(pid(), 'Stefan Zingerle',        'GK', 27, 59, 'AUT'),
        makePlayer(pid(), 'Roberto Massimo',        'RB', 23, 61, 'GER'),
        makePlayer(pid(), 'Timo Beermann',          'CB', 31, 62, 'GER'),
        makePlayer(pid(), 'Bashir Humphreys',       'CB', 21, 61, 'ENG'),
        makePlayer(pid(), 'Leandro Putaro',         'LB', 25, 61, 'AUT'),
        makePlayer(pid(), 'Jonas Kuhn',             'CDM',24, 60, 'GER'),
        makePlayer(pid(), 'Erik Engelhardt',        'CM', 27, 60, 'GER'),
        makePlayer(pid(), 'Raphael Obermair',       'CM', 26, 60, 'GER'),
        makePlayer(pid(), 'Ben Bobzien',            'CM', 23, 60, 'GER'),
        makePlayer(pid(), 'Soren Bertram',          'LW', 30, 62, 'GER'),
        makePlayer(pid(), 'Etienne Amenyido',       'LW', 24, 61, 'GER'),
        makePlayer(pid(), 'Christian Conteh',       'LW', 22, 61, 'GER'),
        makePlayer(pid(), 'Lino Tempel',            'LW', 22, 61, 'GER'),
        makePlayer(pid(), 'Nils Quaschner',         'RW', 29, 61, 'GER'),
        makePlayer(pid(), 'Marc Heider',            'ST', 34, 62, 'GER'),
        makePlayer(pid(), 'Kevin Friesenbichler',   'ST', 27, 61, 'AUT'),
    ]},
];

BUNDESLIGA_TEAMS.forEach(t => { ALL_TEAMS.push(t); TEAM_MAP[t.id] = t; });
BUNDESLIGA2_TEAMS.forEach(t => { ALL_TEAMS.push(t); TEAM_MAP[t.id] = t; });

LEAGUES['bundesliga'] = {
    id: 'bundesliga',
    name: 'Bundesliga',
    country: 'germany',
    tier: 1,
    teams: BUNDESLIGA_TEAMS.map(t => t.id),
    relegationSpots: 3,
    promotionSpots: 0,
    promotionPlayoff: 0,
};

LEAGUES['bundesliga2'] = {
    id: 'bundesliga2',
    name: 'Bundesliga 2',
    country: 'germany',
    tier: 2,
    teams: BUNDESLIGA2_TEAMS.map(t => t.id),
    relegationSpots: 4,
    promotionSpots: 2,
    promotionPlayoff: 4,
};
