// dataLaLiga.js — La Liga + La Liga 2

const LA_LIGA_TEAMS = [
    { id: 'rma', name: 'Real Madrid',       short: 'RMA', color: '#FEBE10', colorAlt: '#FFFFFF', prestige: 97, budget: Math.round(Math.pow(Math.max(0,97-40),2)*45000), stadium: 'Santiago Bernabéu',                    capacity: 81044, squad: [
        makePlayer(pid(), 'Thibaut Courtois',    'GK', 32, 90, 'BEL'),
        makePlayer(pid(), 'Andriy Lunin',        'GK', 25, 80, 'UKR'),
        makePlayer(pid(), 'Dani Carvajal',       'RB', 32, 85, 'ESP'),
        makePlayer(pid(), 'Lucas Vazquez',       'RB', 33, 81, 'ESP'),
        makePlayer(pid(), 'Eder Militao',        'CB', 26, 86, 'BRA'),
        makePlayer(pid(), 'Antonio Rudiger',     'CB', 31, 85, 'GER'),
        makePlayer(pid(), 'David Alaba',         'CB', 32, 84, 'AUT'),
        makePlayer(pid(), 'Nacho Fernandez',     'CB', 34, 82, 'ESP'),
        makePlayer(pid(), 'Ferland Mendy',       'LB', 29, 84, 'FRA'),
        makePlayer(pid(), 'Eduardo Camavinga',   'CM', 21, 83, 'FRA'),
        makePlayer(pid(), 'Federico Valverde',   'CM', 25, 87, 'URU'),
        makePlayer(pid(), 'Aurelien Tchouameni', 'CDM',24, 84, 'FRA'),
        makePlayer(pid(), 'Luka Modric',         'CM', 38, 84, 'CRO'),
        makePlayer(pid(), 'Jude Bellingham',     'CAM',20, 91, 'ENG'),
        makePlayer(pid(), 'Vinicius Junior',     'LW', 23, 91, 'BRA'),
        makePlayer(pid(), 'Rodrygo Goes',        'RW', 23, 85, 'BRA'),
        makePlayer(pid(), 'Joselu',              'ST', 34, 78, 'ESP'),
        makePlayer(pid(), 'Brahim Diaz',         'CAM',25, 79, 'ESP'),
        makePlayer(pid(), 'Dani Ceballos',       'CM', 28, 78, 'ESP'),
    ]},
    { id: 'fcb', name: 'Barcelona',          short: 'FCB', color: '#A50044', colorAlt: '#004D98', prestige: 96, budget: Math.round(Math.pow(Math.max(0,96-40),2)*45000), stadium: 'Camp Nou',                              capacity: 99354, squad: [
        makePlayer(pid(), 'Marc-Andre ter Stegen', 'GK', 32, 89, 'GER'),
        makePlayer(pid(), 'Inaki Pena',            'GK', 25, 74, 'ESP'),
        makePlayer(pid(), 'Jules Kounde',          'RB', 25, 85, 'FRA'),
        makePlayer(pid(), 'Ronald Araujo',         'CB', 25, 86, 'URU'),
        makePlayer(pid(), 'Andreas Christensen',   'CB', 28, 83, 'DEN'),
        makePlayer(pid(), 'Inigo Martinez',        'CB', 22, 82, 'ESP'),
        makePlayer(pid(), 'Alejandro Balde',       'LB', 20, 82, 'ESP'),
        makePlayer(pid(), 'Joao Cancelo',          'RB', 30, 83, 'POR'),
        makePlayer(pid(), 'Pedri',                 'CM', 21, 88, 'ESP'),
        makePlayer(pid(), 'Gavi',                  'CM', 20, 87, 'ESP'),
        makePlayer(pid(), 'Frenkie de Jong',       'CDM',27, 87, 'NED'),
        makePlayer(pid(), 'Oriol Romeu',           'CDM',33, 76, 'ESP'),
        makePlayer(pid(), 'Lamine Yamal',          'RW', 17, 87, 'ESP'),
        makePlayer(pid(), 'Raphinha',              'RW', 27, 84, 'BRA'),
        makePlayer(pid(), 'Robert Lewandowski',    'ST', 36, 87, 'POL'),
        makePlayer(pid(), 'Ferran Torres',         'ST', 24, 80, 'ESP'),
        makePlayer(pid(), 'Ferran Torres',         'LW', 24, 80, 'ESP'),
        makePlayer(pid(), 'Dani Olmo',             'CAM',26, 84, 'ESP'),
    ]},
    { id: 'atm', name: 'Atletico Madrid',    short: 'ATM', color: '#CB3524', colorAlt: '#FFFFFF', prestige: 88, budget: Math.round(Math.pow(Math.max(0,88-40),2)*45000), stadium: 'Wanda Metropolitano',                   capacity: 68456, squad: [
        makePlayer(pid(), 'Jan Oblak',           'GK', 31, 90, 'SVN'),
        makePlayer(pid(), 'Ivo Grbic',           'GK', 28, 75, 'SVN'),
        makePlayer(pid(), 'Nahuel Molina',       'RB', 26, 82, 'ARG'),
        makePlayer(pid(), 'Marcos Llorente',     'RB', 30, 81, 'ESP'),
        makePlayer(pid(), 'Stefan Savic',        'CB', 33, 83, 'MNE'),
        makePlayer(pid(), 'Jose Maria Gimenez',  'CB', 29, 84, 'URU'),
        makePlayer(pid(), 'Axel Witsel',         'CDM',35, 80, 'BEL'),
        makePlayer(pid(), 'Reinildo Mandava',    'LB', 30, 79, 'MOZ'),
        makePlayer(pid(), 'Mario Hermoso',       'CB', 34, 81, 'ESP'),
        makePlayer(pid(), 'Koke',                'CM', 32, 82, 'ESP'),
        makePlayer(pid(), 'Pablo Barrios',       'CDM',24, 79, 'COL'),
        makePlayer(pid(), 'Rodrigo De Paul',     'CM', 30, 83, 'ARG'),
        makePlayer(pid(), 'Saul Niguez',         'CM', 29, 77, 'ESP'),
        makePlayer(pid(), 'Antoine Griezmann',   'CAM',33, 87, 'FRA'),
        makePlayer(pid(), 'Alvaro Morata',       'ST', 31, 82, 'ESP'),
        makePlayer(pid(), 'Angel Correa',        'ST', 29, 79, 'ARG'),
        makePlayer(pid(), 'Samuel Lino',         'LW', 24, 79, 'ESP'),
        makePlayer(pid(), 'Thomas Lemar',        'LW', 28, 78, 'FRA'),
        makePlayer(pid(), 'Rodrigo Riquelme',    'RW', 24, 77, 'ESP'),
    ]},
    { id: 'sev', name: 'Sevilla',            short: 'SEV', color: '#D4011D', colorAlt: '#FFFFFF', prestige: 78, budget: Math.round(Math.pow(Math.max(0,78-40),2)*45000), stadium: 'Ramon Sanchez-Pizjuan',                 capacity: 43883, squad: [
        makePlayer(pid(), 'Ørjan Nyland',        'GK', 33, 76, 'NOR'),
        makePlayer(pid(), 'Marko Dmitrovic',     'GK', 30, 75, 'SRB'),
        makePlayer(pid(), 'Jesus Navas',         'RB', 38, 79, 'CRC'),
        makePlayer(pid(), 'Gonzalo Montiel',     'RB', 27, 78, 'ARG'),
        makePlayer(pid(), 'Nianzou Kouassi',     'CB', 22, 77, 'FRA'),
        makePlayer(pid(), 'Nemanja Gudelj',      'CDM',33, 78, 'SRB'),
        makePlayer(pid(), 'Ivan Rakitic',        'CM', 36, 79, 'CRO'),
        makePlayer(pid(), 'Suso',                'RW', 30, 77, 'ESP'),
        makePlayer(pid(), 'Lucas Ocampos',       'LW', 30, 80, 'ARG'),
        makePlayer(pid(), 'Youssef En-Nesyri',   'ST', 26, 80, 'MAR'),
        makePlayer(pid(), 'Bryan Gil',           'RW', 22, 76, 'ESP'),
        makePlayer(pid(), 'Marcos Acuna',        'LB', 26, 74, 'ESP'),
        makePlayer(pid(), 'Loic Bade',           'CB', 24, 78, 'FRA'),
        makePlayer(pid(), 'Tanguy Nianzou',      'CB', 25, 75, 'CHI'),
        makePlayer(pid(), 'Dodi Lukebakio',      'RW', 26, 78, 'BEL'),
        makePlayer(pid(), 'Juanlu Sanchez',      'RB', 21, 74, 'ESP'),
        makePlayer(pid(), 'Lucien Agoume',       'CM', 22, 74, 'FRA'),
    ]},
    { id: 'rso', name: 'Real Sociedad',      short: 'RSO', color: '#0070B8', colorAlt: '#FFFFFF', prestige: 73, budget: Math.round(Math.pow(Math.max(0,73-40),2)*45000), stadium: 'Reale Arena',                          capacity: 39500, squad: [
        makePlayer(pid(), 'Alex Remiro',         'GK', 28, 82, 'ESP'),
        makePlayer(pid(), 'Andrei Pacheco',      'GK', 26, 73, 'ESP'),
        makePlayer(pid(), 'Martin Zubimendi',    'CDM',25, 83, 'ESP'),
        makePlayer(pid(), 'Mikel Merino',        'CM', 28, 80, 'ESP'),
        makePlayer(pid(), 'Brais Mendez',        'CM', 27, 78, 'ESP'),
        makePlayer(pid(), 'Mikel Oyarzabal',     'CAM',27, 82, 'ESP'),
        makePlayer(pid(), 'Ander Barrenetxea',   'LW', 22, 78, 'ESP'),
        makePlayer(pid(), 'Takefusa Kubo',       'RW', 23, 81, 'JPN'),
        makePlayer(pid(), 'Alexander Sorloth',   'ST', 28, 80, 'NOR'),
        makePlayer(pid(), 'Aihen Munoz',         'LW', 25, 74, 'ESP'),
        makePlayer(pid(), 'Nayef Aguerd',        'CB', 28, 78, 'MAR'),
        makePlayer(pid(), 'Aritz Elustondo',     'CB', 33, 76, 'ESP'),
        makePlayer(pid(), 'Jon Aramburu',        'RB', 21, 74, 'ESP'),
        makePlayer(pid(), 'Mohamed Traoré',      'RW', 24, 75, 'GUI'),
        makePlayer(pid(), 'Luka Sucic',          'CM', 22, 76, 'CRO'),
        makePlayer(pid(), 'Robin Le Normand',    'CB', 27, 81, 'FRA'),
    ]},
    { id: 'bet', name: 'Real Betis',         short: 'BET', color: '#00A650', colorAlt: '#FFFFFF', prestige: 72, budget: Math.round(Math.pow(Math.max(0,72-40),2)*45000), stadium: 'Estadio Benito Villamarin',             capacity: 60721, squad: [
        makePlayer(pid(), 'Rui Silva',           'GK', 31, 79, 'POR'),
        makePlayer(pid(), 'Claudio Bravo',       'GK', 29, 74, 'ESP'),
        makePlayer(pid(), 'Hector Bellerin',     'RB', 34, 76, 'ESP'),
        makePlayer(pid(), 'Youssouf Sabaly',     'RB', 31, 77, 'SEN'),
        makePlayer(pid(), 'Marc Bartra',         'CB', 33, 77, 'ESP'),
        makePlayer(pid(), 'German Pezzella',     'CB', 33, 76, 'ARG'),
        makePlayer(pid(), 'Juan Miranda',        'LB', 24, 76, 'ESP'),
        makePlayer(pid(), 'William Carvalho',    'CDM',22, 77, 'POR'),
        makePlayer(pid(), 'Andres Guardado',     'CM', 38, 74, 'MEX'),
        makePlayer(pid(), 'Nabil Fekir',         'CAM',31, 81, 'FRA'),
        makePlayer(pid(), 'Borja Iglesias',      'ST', 32, 80, 'ESP'),
        makePlayer(pid(), 'Willian Jose',        'ST', 32, 76, 'BRA'),
        makePlayer(pid(), 'Juanmi',              'LW', 31, 75, 'ESP'),
        makePlayer(pid(), 'Aitor Ruibal',        'RW', 27, 74, 'ESP'),
        makePlayer(pid(), 'Pablo Fornals',       'CM', 28, 78, 'ESP'),
        makePlayer(pid(), 'Ez Abde',             'CAM',22, 75, 'ESP'),
        makePlayer(pid(), 'Johnny Cardoso',      'CM', 26, 74, 'ESP'),
    ]},
    { id: 'vil', name: 'Villarreal',         short: 'VIL', color: '#FFE400', colorAlt: '#009EDA', prestige: 71, budget: Math.round(Math.pow(Math.max(0,71-40),2)*45000), stadium: 'Estadio de la Cerámica',               capacity: 23500, squad: [
        makePlayer(pid(), 'Pepe Reina',          'GK', 42, 74, 'ESP'),
        makePlayer(pid(), 'Filip Jorgensen',     'GK', 27, 75, 'DEN'),
        makePlayer(pid(), 'Juan Foyth',          'RB', 26, 78, 'ARG'),
        makePlayer(pid(), 'Pau Torres',          'CB', 27, 82, 'ESP'),
        makePlayer(pid(), 'Raul Albiol',         'CB', 38, 78, 'ESP'),
        makePlayer(pid(), 'Alex Baena',          'CM', 22, 78, 'ESP'),
        makePlayer(pid(), 'Dani Parejo',         'CM', 35, 81, 'ESP'),
        makePlayer(pid(), 'Jose Comesana',       'CDM',26, 74, 'ESP'),
        makePlayer(pid(), 'Jose Luis Morales',   'RW', 32, 75, 'ESP'),
        makePlayer(pid(), 'Samuel Chukwueze',    'RW', 25, 79, 'NGA'),
        makePlayer(pid(), 'Arnaut Danjuma',      'LW', 27, 78, 'NED'),
        makePlayer(pid(), 'Nicolas Jackson',     'ST', 22, 80, 'SEN'),
        makePlayer(pid(), 'Alexander Sorloth',   'ST', 29, 78, 'NOR'),
        makePlayer(pid(), 'Manu Trigueros',      'CM', 32, 75, 'ESP'),
        makePlayer(pid(), 'Marc Terrats',        'CM', 25, 74, 'ESP'),
    ]},
    { id: 'ath', name: 'Athletic Bilbao',    short: 'ATH', color: '#EE2523', colorAlt: '#FFFFFF', prestige: 71, budget: Math.round(Math.pow(Math.max(0,71-40),2)*45000), stadium: 'San Mames',                            capacity: 53289, squad: [
        makePlayer(pid(), 'Julen Agirrezabala',  'GK', 24, 77, 'ESP'),
        makePlayer(pid(), 'Unai Simon',          'GK', 27, 81, 'ESP'),
        makePlayer(pid(), 'Oscar de Marcos',     'RB', 35, 76, 'ESP'),
        makePlayer(pid(), 'Jon Gorosabel',       'RB', 26, 75, 'ESP'),
        makePlayer(pid(), 'Yeray Alvarez',       'CB', 27, 80, 'ESP'),
        makePlayer(pid(), 'Dani Vivian',         'CB', 25, 79, 'ESP'),
        makePlayer(pid(), 'Yuri Berchiche',      'LB', 33, 76, 'ESP'),
        makePlayer(pid(), 'Mikel Lekue',         'LB', 32, 74, 'ESP'),
        makePlayer(pid(), 'Unai Vencedor',       'CDM',24, 78, 'ESP'),
        makePlayer(pid(), 'Oier Zarraga',        'CM', 22, 76, 'ESP'),
        makePlayer(pid(), 'Dani Garcia',         'CDM',34, 78, 'ESP'),
        makePlayer(pid(), 'Mikel Vesga',         'CM', 30, 77, 'ESP'),
        makePlayer(pid(), 'Nico Williams',       'LW', 21, 82, 'GHA'),
        makePlayer(pid(), 'Nico Williams',       'RW', 22, 80, 'ESP'),
        makePlayer(pid(), 'Gorka Guruzeta',      'ST', 25, 78, 'ESP'),
        makePlayer(pid(), 'Oihan Sancet',        'CAM',23, 80, 'ESP'),
        makePlayer(pid(), 'Inaki Williams',      'ST', 30, 82, 'GHA'),
    ]},
    { id: 'val', name: 'Valencia',           short: 'VAL', color: '#FF6900', colorAlt: '#000000', prestige: 68, budget: Math.round(Math.pow(Math.max(0,68-40),2)*45000), stadium: 'Mestalla',                             capacity: 55000, squad: [
        makePlayer(pid(), 'Giorgi Mamardashvili', 'GK', 23, 81, 'GEO'),
        makePlayer(pid(), 'Domenech',            'GK', 32, 72, 'ESP'),
        makePlayer(pid(), 'Thierry Correia',     'RB', 27, 74, 'CPV'),
        makePlayer(pid(), 'Cristhian Mosquera',  'CB', 21, 76, 'COL'),
        makePlayer(pid(), 'Hugo Guillamon',      'CDM',23, 75, 'ESP'),
        makePlayer(pid(), 'Cenk Ozkacar',        'CB', 30, 77, 'BRA'),
        makePlayer(pid(), 'Jose Gaya',           'LB', 29, 79, 'ESP'),
        makePlayer(pid(), 'Pepelu',              'CM', 25, 77, 'ESP'),
        makePlayer(pid(), 'Andre Almeida',       'CM', 22, 75, 'POR'),
        makePlayer(pid(), 'Fran Perez',          'RW', 22, 73, 'ESP'),
        makePlayer(pid(), 'Javier Canos',        'RW', 27, 74, 'ESP'),
        makePlayer(pid(), 'Hugo Duro',           'ST', 25, 77, 'ESP'),
        makePlayer(pid(), 'Marcos Andre',        'ST', 27, 75, 'ESP'),
        makePlayer(pid(), 'Edinson Cavani',      'CM', 26, 72, 'ESP'),
        makePlayer(pid(), 'Justin Kluivert',     'LW', 25, 73, 'ESP'),
        makePlayer(pid(), 'Mouctar Diakhaby',    'CB', 27, 74, 'GUI'),
    ]},
    { id: 'osa', name: 'Osasuna',            short: 'OSA', color: '#DA0010', colorAlt: '#003DA5', prestige: 62, budget: Math.round(Math.pow(Math.max(0,62-40),2)*45000), stadium: 'El Sadar',                             capacity: 23517, squad: [
        makePlayer(pid(), 'Sergio Herrera',      'GK', 30, 71, 'ESP'),
        makePlayer(pid(), 'Iker Munoz',          'GK', 25, 63, 'ESP'),
        makePlayer(pid(), 'Nacho Vidal',         'RB', 31, 69, 'ESP'),
        makePlayer(pid(), 'David Garcia',        'CB', 30, 72, 'ESP'),
        makePlayer(pid(), 'Unai Garcia',         'CB', 28, 68, 'ESP'),
        makePlayer(pid(), 'Juan Cruz',           'LB', 28, 68, 'ESP'),
        makePlayer(pid(), 'Moi Gomez',           'RW', 29, 70, 'ESP'),
        makePlayer(pid(), 'Lucas Torro',         'CDM',29, 68, 'ESP'),
        makePlayer(pid(), 'Jon Moncayola',       'CM', 25, 69, 'ESP'),
        makePlayer(pid(), 'Ante Budimir',        'ST', 31, 71, 'CRO'),
        makePlayer(pid(), 'Roberto Torres',      'CM', 33, 69, 'ESP'),
        makePlayer(pid(), 'Ruben Garcia',        'CM', 28, 69, 'ESP'),
        makePlayer(pid(), 'Kike Garcia',         'ST', 33, 67, 'ESP'),
        makePlayer(pid(), 'Ezequiel Avila',      'LW', 27, 68, 'ARG'),
        makePlayer(pid(), 'Ivan Martinez',       'CB', 27, 66, 'ESP'),
        makePlayer(pid(), 'Brian Zaragoza',      'RW', 23, 68, 'ESP'),
        makePlayer(pid(), 'Aimar Oroz',          'CM', 22, 68, 'ESP'),
    ]},
    { id: 'get', name: 'Getafe',             short: 'GET', color: '#0065BD', colorAlt: '#FFFFFF', prestige: 61, budget: Math.round(Math.pow(Math.max(0,61-40),2)*45000), stadium: 'Coliseum Alfonso Perez',               capacity: 17700, squad: [
        makePlayer(pid(), 'David Soria',         'GK', 30, 71, 'ESP'),
        makePlayer(pid(), 'Chema Rodriguez',     'GK', 28, 63, 'ESP'),
        makePlayer(pid(), 'Damian Suarez',       'RB', 35, 69, 'URU'),
        makePlayer(pid(), 'Djene Dakonam',       'CB', 31, 70, 'TOG'),
        makePlayer(pid(), 'Erick Cabaco',        'CB', 28, 67, 'URU'),
        makePlayer(pid(), 'Florian Lejeune',     'LB', 32, 68, 'FRA'),
        makePlayer(pid(), 'Mauro Arambarri',     'CDM',27, 71, 'URU'),
        makePlayer(pid(), 'Nemanja Maksimovic',  'CDM',28, 69, 'SRB'),
        makePlayer(pid(), 'Carles Alena',        'CM', 25, 68, 'ESP'),
        makePlayer(pid(), 'Jaime Mata',          'ST', 35, 68, 'ESP'),
        makePlayer(pid(), 'Borja Mayoral',       'ST', 26, 68, 'ESP'),
        makePlayer(pid(), 'Mason Greenwood',     'RW', 22, 71, 'ENG'),
        makePlayer(pid(), 'Enes Unal',           'ST', 26, 69, 'TUR'),
        makePlayer(pid(), 'Gaston Alvarez',      'RB', 24, 66, 'URU'),
        makePlayer(pid(), 'Sandro Ramirez',      'LW', 28, 65, 'ESP'),
        makePlayer(pid(), 'Luis Milla',          'CM', 27, 67, 'ESP'),
        makePlayer(pid(), 'Oscar Rodriguez',     'CM', 25, 68, 'ESP'),
    ]},
    { id: 'cel', name: 'Celta Vigo',         short: 'CEL', color: '#6CBDE9', colorAlt: '#FFFFFF', prestige: 62, budget: Math.round(Math.pow(Math.max(0,62-40),2)*45000), stadium: 'Abanca-Balaídos',                      capacity: 29000, squad: [
        makePlayer(pid(), 'Ruben Blanco',        'GK', 30, 71, 'ESP'),
        makePlayer(pid(), 'Ivan Villar',         'GK', 24, 69, 'ESP'),
        makePlayer(pid(), 'Kevin Vazquez',       'RB', 27, 67, 'ESP'),
        makePlayer(pid(), 'Joseph Aidoo',        'CB', 28, 70, 'GHA'),
        makePlayer(pid(), 'Nestor Araujo',       'CB', 32, 68, 'MEX'),
        makePlayer(pid(), 'Hugo Mallo',          'RB', 33, 67, 'ESP'),
        makePlayer(pid(), 'Jailson',             'LB', 31, 67, 'BRA'),
        makePlayer(pid(), 'Fran Beltran',        'CDM',25, 70, 'ESP'),
        makePlayer(pid(), 'Renato Tapia',        'CDM',29, 69, 'PER'),
        makePlayer(pid(), 'Denis Suarez',        'CM', 29, 69, 'ESP'),
        makePlayer(pid(), 'Luca de la Torre',    'CM', 26, 67, 'USA'),
        makePlayer(pid(), 'Jonathan Bamba',      'LW', 27, 68, 'FRA'),
        makePlayer(pid(), 'Williot Swedberg',    'ST', 20, 66, 'SWE'),
        makePlayer(pid(), 'Iago Aspas',          'ST', 36, 76, 'ESP'),
        makePlayer(pid(), 'Goncalo Paciencia',   'ST', 29, 68, 'POR'),
        makePlayer(pid(), 'Anastasios Douvikas', 'ST', 24, 67, 'GRE'),
        makePlayer(pid(), 'Carles Perez',        'RW', 25, 68, 'ESP'),
    ]},
    { id: 'ray', name: 'Rayo Vallecano',     short: 'RAY', color: '#CC1221', colorAlt: '#FFFFFF', prestige: 59, budget: Math.round(Math.pow(Math.max(0,59-40),2)*45000), stadium: 'Campo de Futbol de Vallecas',          capacity: 14708, squad: [
        makePlayer(pid(), 'Stole Dimitrievski',  'GK', 31, 69, 'MKD'),
        makePlayer(pid(), 'Teodoro Boubacar',    'GK', 26, 60, 'ESP'),
        makePlayer(pid(), 'Ivan Balliu',         'RB', 31, 66, 'ALB'),
        makePlayer(pid(), 'Florian Lejeune',     'CB', 32, 68, 'FRA'),
        makePlayer(pid(), 'Esteban Saveljich',   'CB', 31, 67, 'MNE'),
        makePlayer(pid(), 'Fran Garcia',         'LB', 23, 68, 'ESP'),
        makePlayer(pid(), 'Alberto Garcia',      'LB', 28, 65, 'ESP'),
        makePlayer(pid(), 'Oscar Trejo',         'CM', 35, 68, 'ARG'),
        makePlayer(pid(), 'Unai Lopez',          'CM', 28, 67, 'ESP'),
        makePlayer(pid(), 'Santi Comesana',      'CDM',24, 66, 'ESP'),
        makePlayer(pid(), 'Pathe Ciss',          'CM', 30, 66, 'SEN'),
        makePlayer(pid(), 'Alvaro Garcia',       'RW', 30, 68, 'ESP'),
        makePlayer(pid(), 'Jorge de Frutos',     'LW', 26, 67, 'ESP'),
        makePlayer(pid(), 'Isi Palazon',         'RW', 30, 68, 'ESP'),
        makePlayer(pid(), 'Sergio Camello',      'ST', 22, 66, 'ESP'),
        makePlayer(pid(), 'Randy Nteka',         'ST', 25, 65, 'FRA'),
        makePlayer(pid(), 'Diego Lopez',         'RB', 21, 63, 'ESP'),
    ]},
    { id: 'gir', name: 'Girona',             short: 'GIR', color: '#CD1B2F', colorAlt: '#FFFFFF', prestige: 64, budget: Math.round(Math.pow(Math.max(0,64-40),2)*45000), stadium: 'Estadi Municipal de Montilivi',        capacity: 13500, squad: [
        makePlayer(pid(), 'Paulo Gazzaniga',     'GK', 31, 71, 'ARG'),
        makePlayer(pid(), 'Juan Carlos',         'GK', 33, 68, 'ESP'),
        makePlayer(pid(), 'Miguel Gutierrez',    'LB', 22, 71, 'ESP'),
        makePlayer(pid(), 'Arnau Martinez',      'RB', 20, 70, 'ESP'),
        makePlayer(pid(), 'David Lopez',         'CB', 32, 70, 'ESP'),
        makePlayer(pid(), 'Eric Garcia',         'CB', 22, 72, 'ESP'),
        makePlayer(pid(), 'Santi Bueno',         'CB', 26, 69, 'URU'),
        makePlayer(pid(), 'Aleix Garcia',        'CDM',25, 72, 'ESP'),
        makePlayer(pid(), 'Oriol Romeu',         'CDM',31, 70, 'ESP'),
        makePlayer(pid(), 'Ivan Martin',         'CM', 22, 69, 'ESP'),
        makePlayer(pid(), 'Viktor Tsyhankov',    'LW', 27, 70, 'UKR'),
        makePlayer(pid(), 'Savinho',             'RW', 19, 72, 'BRA'),
        makePlayer(pid(), 'Taty Castellanos',    'ST', 24, 72, 'ARG'),
        makePlayer(pid(), 'Cristhian Stuani',    'ST', 37, 69, 'URU'),
        makePlayer(pid(), 'Portu',               'RW', 31, 68, 'ESP'),
        makePlayer(pid(), 'Yangel Herrera',      'CM', 25, 71, 'VEN'),
        makePlayer(pid(), 'Jhon Solis',          'CM', 22, 65, 'COL'),
    ]},
    { id: 'lpa', name: 'Las Palmas',         short: 'LPA', color: '#FFED00', colorAlt: '#003DA5', prestige: 57, budget: Math.round(Math.pow(Math.max(0,57-40),2)*45000), stadium: 'Gran Canaria Stadium',                 capacity: 32788, squad: [
        makePlayer(pid(), 'Alvaro Valles',       'GK', 28, 67, 'ESP'),
        makePlayer(pid(), 'Jesus Fernandez',     'GK', 24, 58, 'ESP'),
        makePlayer(pid(), 'Sergi Cardona',       'LB', 23, 65, 'ESP'),
        makePlayer(pid(), 'Matheus Mastriani',   'RB', 27, 64, 'BRA'),
        makePlayer(pid(), 'Florentino Luis',     'CB', 24, 67, 'GNB'),
        makePlayer(pid(), 'Coco',                'CB', 27, 65, 'ESP'),
        makePlayer(pid(), 'Mika Marmol',         'CB', 23, 65, 'ESP'),
        makePlayer(pid(), 'Fabio Silva',         'LW', 21, 67, 'POR'),
        makePlayer(pid(), 'Kirian Rodriguez',    'CDM',28, 67, 'ESP'),
        makePlayer(pid(), 'Clint Yow',           'CM', 25, 63, 'USA'),
        makePlayer(pid(), 'Jonathan Viera',      'CM', 33, 67, 'ESP'),
        makePlayer(pid(), 'Sory Kaba',           'RW', 22, 65, 'ESP'),
        makePlayer(pid(), 'Sandro Ramirez',      'ST', 28, 65, 'ESP'),
        makePlayer(pid(), 'Alberto Moleiro',     'CM', 20, 67, 'ESP'),
        makePlayer(pid(), 'Benjamin Loiodice',   'CM', 27, 63, 'ITA'),
        makePlayer(pid(), 'Munir El Haddadi',    'RW', 28, 68, 'ESP'),
        makePlayer(pid(), 'Anthony Lozano',      'ST', 30, 65, 'HON'),
    ]},
    { id: 'rcd', name: 'Mallorca',           short: 'RCD', color: '#C8102E', colorAlt: '#000000', prestige: 58, budget: Math.round(Math.pow(Math.max(0,58-40),2)*45000), stadium: 'Son Moix',                             capacity: 23142, squad: [
        makePlayer(pid(), 'Predrag Rajkovic',    'GK', 29, 70, 'SRB'),
        makePlayer(pid(), 'Leo Roman',           'GK', 22, 61, 'ESP'),
        makePlayer(pid(), 'Pablo Maffeo',        'RB', 27, 70, 'ESP'),
        makePlayer(pid(), 'Martin Valjent',      'CB', 27, 69, 'SVK'),
        makePlayer(pid(), 'Antonio Raillo',      'CB', 31, 68, 'ESP'),
        makePlayer(pid(), 'Matija Nastasic',     'CB', 31, 68, 'SRB'),
        makePlayer(pid(), 'Jaume Costa',         'LB', 35, 65, 'ESP'),
        makePlayer(pid(), 'Ruben Insua',         'LB', 26, 66, 'ARG'),
        makePlayer(pid(), 'Omar Mascarell',      'CDM',30, 67, 'ESP'),
        makePlayer(pid(), 'Iddrisu Baba',        'CDM',26, 67, 'GHA'),
        makePlayer(pid(), 'Dani Rodriguez',      'CM', 32, 67, 'ESP'),
        makePlayer(pid(), 'Abdon Prats',         'ST', 31, 67, 'ESP'),
        makePlayer(pid(), 'Vedat Muriqi',        'ST', 29, 69, 'KVX'),
        makePlayer(pid(), 'Cyle Larin',          'ST', 28, 68, 'CAN'),
        makePlayer(pid(), 'Sergi Darder',        'CM', 28, 69, 'ESP'),
        makePlayer(pid(), 'Dani Munoz',          'RB', 26, 67, 'ESP'),
        makePlayer(pid(), 'Giovanni Gonzalez',   'LW', 23, 65, 'ARG'),
    ]},
    { id: 'ala', name: 'Alaves',             short: 'ALA', color: '#003B88', colorAlt: '#FFFFFF', prestige: 56, budget: Math.round(Math.pow(Math.max(0,56-40),2)*45000), stadium: 'Mendizorroza',                         capacity: 19840, squad: [
        makePlayer(pid(), 'Antonio Sivera',      'GK', 28, 67, 'ESP'),
        makePlayer(pid(), 'Miguel Fernandez',    'GK', 25, 58, 'ESP'),
        makePlayer(pid(), 'Nahuel Tenaglia',     'RB', 27, 66, 'ARG'),
        makePlayer(pid(), 'Victor Laguardia',    'CB', 31, 68, 'ESP'),
        makePlayer(pid(), 'Florian Lejeune',     'CB', 32, 67, 'FRA'),
        makePlayer(pid(), 'Ion Karrikaburu',     'CB', 25, 63, 'ESP'),
        makePlayer(pid(), 'Ruben Duarte',        'LB', 27, 66, 'ESP'),
        makePlayer(pid(), 'Toni Moya',           'CDM',24, 66, 'ESP'),
        makePlayer(pid(), 'Bruno Gonzalez',      'CDM',25, 65, 'ESP'),
        makePlayer(pid(), 'Mamadou Sylla',       'CM', 27, 64, 'SEN'),
        makePlayer(pid(), 'Luis Rioja',          'LW', 29, 67, 'ESP'),
        makePlayer(pid(), 'Jon Guridi',          'CM', 25, 65, 'ESP'),
        makePlayer(pid(), 'Carlos Vicente',      'RW', 27, 65, 'ESP'),
        makePlayer(pid(), 'Kike Garcia',         'ST', 33, 66, 'ESP'),
        makePlayer(pid(), 'Iñaki Pena',          'ST', 25, 63, 'MNE'),
        makePlayer(pid(), 'Gonzalo Escalante',   'CM', 30, 65, 'ARG'),
        makePlayer(pid(), 'Theo Zidane',         'LB', 24, 65, 'ESP'),
    ]},
    { id: 'cad', name: 'Cadiz',              short: 'CAD', color: '#F0E800', colorAlt: '#003DA5', prestige: 55, budget: Math.round(Math.pow(Math.max(0,55-40),2)*45000), stadium: 'Estadio Ramon de Carranza',            capacity: 20724, squad: [
        makePlayer(pid(), 'Jeremias Ledesma',    'GK', 30, 67, 'ARG'),
        makePlayer(pid(), 'David Gil',           'GK', 29, 61, 'ESP'),
        makePlayer(pid(), 'Joseba Zaldua',       'RB', 30, 64, 'ESP'),
        makePlayer(pid(), 'Fali',                'CB', 30, 66, 'ESP'),
        makePlayer(pid(), 'Marcos Mauro',        'CB', 34, 65, 'ARG'),
        makePlayer(pid(), 'Theo Bongonda',       'LW', 28, 66, 'BEL'),
        makePlayer(pid(), 'Jose Mari',           'LB', 25, 63, 'ESP'),
        makePlayer(pid(), 'Alejo Aviles',        'CDM',24, 63, 'ESP'),
        makePlayer(pid(), 'Fede San Emeterio',   'CM', 32, 65, 'ESP'),
        makePlayer(pid(), 'Tomas Alarcon',       'CM', 26, 65, 'CHI'),
        makePlayer(pid(), 'Brian Ocampo',        'RW', 23, 66, 'URU'),
        makePlayer(pid(), 'Chris Ramos',         'ST', 23, 65, 'ECU'),
        makePlayer(pid(), 'Ruben Sobrino',       'ST', 32, 63, 'ESP'),
        makePlayer(pid(), 'Lucas Perez',         'ST', 35, 65, 'ESP'),
        makePlayer(pid(), 'Jon Ander Garrido',   'CM', 27, 63, 'ESP'),
        makePlayer(pid(), 'Alvaro Gimenez',      'ST', 31, 65, 'ESP'),
        makePlayer(pid(), 'Victor Chust',        'CB', 23, 62, 'ESP'),
    ]},
    { id: 'gra', name: 'Granada',            short: 'GRA', color: '#C8102E', colorAlt: '#FFFFFF', prestige: 53, budget: Math.round(Math.pow(Math.max(0,53-40),2)*45000), stadium: 'Nuevo Los Carmenes',                   capacity: 19336, squad: [
        makePlayer(pid(), 'Luis Maximiano',      'GK', 24, 67, 'POR'),
        makePlayer(pid(), 'Rui Silva',           'GK', 30, 66, 'POR'),
        makePlayer(pid(), 'Ricard Sanchez',      'RB', 25, 61, 'ESP'),
        makePlayer(pid(), 'Carlos Neva',         'LB', 27, 63, 'ESP'),
        makePlayer(pid(), 'Victor Diaz',         'CB', 32, 64, 'ESP'),
        makePlayer(pid(), 'German Sanchez',      'CB', 34, 65, 'ESP'),
        makePlayer(pid(), 'Ignasi Miquel',       'CB', 31, 63, 'ESP'),
        makePlayer(pid(), 'Luis Milla',          'CM', 27, 65, 'ESP'),
        makePlayer(pid(), 'Nicolas Melamed',     'RW', 23, 64, 'ESP'),
        makePlayer(pid(), 'Jorge Molina',        'ST', 41, 65, 'ESP'),
        makePlayer(pid(), 'Bryan Zaragoza',      'LW', 22, 66, 'ESP'),
        makePlayer(pid(), 'Antonio Puertas',     'CM', 27, 65, 'ESP'),
        makePlayer(pid(), 'Milot Rashica',       'LW', 27, 65, 'ALB'),
        makePlayer(pid(), 'Alvaro Djalo',        'ST', 24, 63, 'ESP'),
        makePlayer(pid(), 'Sergio Ruiz',         'CM', 25, 62, 'ESP'),
        makePlayer(pid(), 'Oscar Melendo',       'CM', 27, 63, 'ESP'),
        makePlayer(pid(), 'Uzuni',               'ST', 27, 64, 'ALB'),
    ]},
    { id: 'alm', name: 'Almeria',            short: 'ALM', color: '#E8001C', colorAlt: '#FFFFFF', prestige: 52, budget: Math.round(Math.pow(Math.max(0,52-40),2)*45000), stadium: 'Estadio de los Juegos Mediterraneos',  capacity: 15000, squad: [
        makePlayer(pid(), 'Fernando Martinez',   'GK', 29, 65, 'ESP'),
        makePlayer(pid(), 'Maracin',             'GK', 25, 58, 'ESP'),
        makePlayer(pid(), 'Arnau Puigmal',       'RB', 22, 62, 'ESP'),
        makePlayer(pid(), 'Rodrigo Ely',         'CB', 29, 65, 'BRA'),
        makePlayer(pid(), 'Edgar Gonzalez',      'CB', 27, 63, 'ESP'),
        makePlayer(pid(), 'Kaiky',               'CB', 20, 64, 'BRA'),
        makePlayer(pid(), 'Leo Baptistao',       'LW', 31, 65, 'BRA'),
        makePlayer(pid(), 'Alejandro Pozo',      'RB', 24, 63, 'ESP'),
        makePlayer(pid(), 'Eguaras',             'CDM',30, 63, 'ESP'),
        makePlayer(pid(), 'Lazaro',              'LB', 26, 63, 'BRA'),
        makePlayer(pid(), 'El Bilal Toure',      'ST', 22, 66, 'MLI'),
        makePlayer(pid(), 'Largie Ramazani',     'LW', 21, 64, 'BEL'),
        makePlayer(pid(), 'Umar Sadiq',          'ST', 26, 65, 'NGA'),
        makePlayer(pid(), 'Dylan Batubinsika',   'CB', 24, 61, 'FRA'),
        makePlayer(pid(), 'Emilio Jose Mateu',   'ST', 27, 61, 'ESP'),
        makePlayer(pid(), 'Sergio Akieme',       'LB', 24, 61, 'ESP'),
        makePlayer(pid(), 'Pablo Fernandez',     'CM', 30, 63, 'ESP'),
    ]},
];

const LA_LIGA2_TEAMS = [
    { id: 'eib',  name: 'Eibar',             short: 'EIB', color: '#CF0000', colorAlt: '#003DA5', prestige: 53, budget: Math.round(Math.pow(Math.max(0,53-40),2)*45000), stadium: 'Estadio Municipal de Ipurua',                       capacity: 7083,  squad: [
        makePlayer(pid(), 'Asier Riesgo',        'GK', 37, 68, 'ESP'),
        makePlayer(pid(), 'Giorgi Kadaria',      'GK', 26, 62, 'GEO'),
        makePlayer(pid(), 'Recio',               'CDM',32, 68, 'ESP'),
        makePlayer(pid(), 'Quique Gonzalez',     'RB', 29, 67, 'ESP'),
        makePlayer(pid(), 'Paulo Oliveira',      'CB', 32, 68, 'POR'),
        makePlayer(pid(), 'Sergio Alvarez',      'CB', 30, 66, 'ESP'),
        makePlayer(pid(), 'Edu Exposito',        'CM', 25, 70, 'ESP'),
        makePlayer(pid(), 'Jon Guridi',          'CDM',24, 68, 'ESP'),
        makePlayer(pid(), 'Stoichkov',           'LW', 25, 67, 'BUL'),
        makePlayer(pid(), 'Anaitz Arbilla',      'RB', 35, 66, 'ESP'),
        makePlayer(pid(), 'Pape Diop',           'CDM',33, 67, 'SEN'),
        makePlayer(pid(), 'Kike Perez',          'CM', 30, 66, 'ESP'),
        makePlayer(pid(), 'Sergio Enrich',       'ST', 32, 68, 'ESP'),
        makePlayer(pid(), 'Kevin Presa',         'RW', 26, 66, 'ESP'),
        makePlayer(pid(), 'Dani Garcia',         'ST', 28, 65, 'ESP'),
        makePlayer(pid(), 'Inui',                'LW', 34, 68, 'JPN'),
        makePlayer(pid(), 'Pablo Muniz',         'LB', 24, 64, 'ESP'),
    ]},
    { id: 'lev',  name: 'Levante',            short: 'LEV', color: '#002FA6', colorAlt: '#CC0000', prestige: 55, budget: Math.round(Math.pow(Math.max(0,55-40),2)*45000), stadium: 'Estadi Ciutat de Valencia',                         capacity: 25354, squad: [
        makePlayer(pid(), 'Aitor Fernandez',     'GK', 32, 74, 'ESP'),
        makePlayer(pid(), 'Dani Cardenas',       'GK', 25, 67, 'ESP'),
        makePlayer(pid(), 'Ruben Vezo',          'CB', 31, 71, 'POR'),
        makePlayer(pid(), 'Michal Pospichal',    'RB', 26, 68, 'CZE'),
        makePlayer(pid(), 'Nikola Vukcevic',     'CDM',27, 70, 'MNE'),
        makePlayer(pid(), 'Jorge de Frutos',     'LW', 25, 71, 'ESP'),
        makePlayer(pid(), 'Gonzalo Melero',      'CM', 28, 71, 'ESP'),
        makePlayer(pid(), 'Roberto Soldado',     'ST', 38, 70, 'ESP'),
        makePlayer(pid(), 'Jose Campana',        'CM', 29, 72, 'ESP'),
        makePlayer(pid(), 'Bonatini',            'ST', 30, 69, 'BRA'),
        makePlayer(pid(), 'Pepelu',              'CM', 24, 72, 'ESP'),
        makePlayer(pid(), 'Sergio Leon',         'ST', 33, 69, 'ESP'),
        makePlayer(pid(), 'Enis Bardhi',         'CM', 27, 71, 'MKD'),
        makePlayer(pid(), 'Coke',                'RB', 36, 66, 'ESP'),
        makePlayer(pid(), 'Miquel Llambrich',    'LB', 23, 65, 'ESP'),
        makePlayer(pid(), 'Son',                 'LW', 27, 68, 'KOR'),
        makePlayer(pid(), 'Tono',                'LB', 34, 66, 'ESP'),
    ]},
    { id: 'vll',  name: 'Valladolid',         short: 'VLL', color: '#480070', colorAlt: '#FFFFFF', prestige: 56, budget: Math.round(Math.pow(Math.max(0,56-40),2)*45000), stadium: 'Estadio Jose Zorrilla',                             capacity: 26512, squad: [
        makePlayer(pid(), 'Jordi Masip',         'GK', 35, 72, 'ESP'),
        makePlayer(pid(), 'Jesus Ruiz',          'GK', 27, 64, 'ESP'),
        makePlayer(pid(), 'Luis Perez',          'RB', 27, 68, 'ESP'),
        makePlayer(pid(), 'Joaquin Fernandez',   'CB', 28, 70, 'ESP'),
        makePlayer(pid(), 'Javi Sanchez',        'CB', 27, 70, 'ESP'),
        makePlayer(pid(), 'Ivan Fresneda',       'RB', 19, 70, 'ESP'),
        makePlayer(pid(), 'Roque Mesa',          'CM', 33, 69, 'ESP'),
        makePlayer(pid(), 'Kike Perez',          'CM', 30, 68, 'ESP'),
        makePlayer(pid(), 'Anuar Mohamed',       'RW', 23, 69, 'MAR'),
        makePlayer(pid(), 'Toni Villa',          'RW', 25, 69, 'ESP'),
        makePlayer(pid(), 'Marcos Andre',        'ST', 27, 71, 'BRA'),
        makePlayer(pid(), 'Cyle Larin',          'ST', 28, 70, 'CAN'),
        makePlayer(pid(), 'Sergi Guardiola',     'ST', 31, 68, 'ESP'),
        makePlayer(pid(), 'Plano',               'CM', 30, 67, 'ESP'),
        makePlayer(pid(), 'Olaf Koback',         'LB', 22, 66, 'NOR'),
        makePlayer(pid(), 'Sergio Moran',        'CDM',26, 67, 'ESP'),
        makePlayer(pid(), 'Meseguer',            'CM', 26, 67, 'ESP'),
    ]},
    { id: 'leg',  name: 'Leganes',            short: 'LEG', color: '#1A3E89', colorAlt: '#FFFFFF', prestige: 52, budget: Math.round(Math.pow(Math.max(0,52-40),2)*45000), stadium: 'Estadio Municipal de Butarque',                     capacity: 12454, squad: [
        makePlayer(pid(), 'Ivan Cuellar',        'GK', 38, 67, 'ESP'),
        makePlayer(pid(), 'Marko Dmitrovic',     'GK', 31, 72, 'SRB'),
        makePlayer(pid(), 'Jonathan Silva',      'LB', 29, 67, 'ARG'),
        makePlayer(pid(), 'Alexander Szymanowski','RW',29, 68, 'POL'),
        makePlayer(pid(), 'Kevin Rodrigues',     'LB', 28, 67, 'FRA'),
        makePlayer(pid(), 'Unai Bustinza',       'CB', 30, 68, 'ESP'),
        makePlayer(pid(), 'Dimitri Foulquier',   'RB', 31, 68, 'FRA'),
        makePlayer(pid(), 'Recio',               'CDM',31, 67, 'ESP'),
        makePlayer(pid(), 'Ruben Perez',         'CM', 34, 66, 'ESP'),
        makePlayer(pid(), 'Martin Braithwaite',  'ST', 33, 70, 'DEN'),
        makePlayer(pid(), 'Javi Galan',          'LB', 27, 68, 'ESP'),
        makePlayer(pid(), 'Oscar Rodriguez',     'CM', 25, 70, 'ESP'),
        makePlayer(pid(), 'Roger Assale',        'LW', 29, 67, 'CIV'),
        makePlayer(pid(), 'Enes Unal',           'ST', 26, 70, 'TUR'),
        makePlayer(pid(), 'Youssouf Diop',       'CB', 27, 65, 'SEN'),
        makePlayer(pid(), 'Pedro Diaz',          'CM', 22, 65, 'ESP'),
        makePlayer(pid(), 'Kenan Kodro',         'ST', 29, 65, 'BIH'),
    ]},
    { id: 'rac',  name: 'Racing Santander',   short: 'RAC', color: '#003280', colorAlt: '#FFFFFF', prestige: 50, budget: Math.round(Math.pow(Math.max(0,50-40),2)*45000), stadium: 'El Sardinero',                                      capacity: 22222, squad: [
        makePlayer(pid(), 'Iago Abraido',        'GK', 31, 65, 'ESP'),
        makePlayer(pid(), 'Carlos Abad',         'GK', 27, 62, 'ESP'),
        makePlayer(pid(), 'Adri Castellano',     'RB', 26, 63, 'ESP'),
        makePlayer(pid(), 'Diego Caceres',       'CB', 25, 64, 'PAR'),
        makePlayer(pid(), 'Mario Bilbao',        'CB', 28, 63, 'ESP'),
        makePlayer(pid(), 'Ale Munoz',           'LB', 24, 63, 'ESP'),
        makePlayer(pid(), 'Fede Vico',           'CM', 29, 65, 'ESP'),
        makePlayer(pid(), 'Pablo Torre',         'CM', 21, 67, 'ESP'),
        makePlayer(pid(), 'Aritz Ondarra',       'CM', 24, 63, 'ESP'),
        makePlayer(pid(), 'Ekaitz Jimenez',      'ST', 23, 63, 'ESP'),
        makePlayer(pid(), 'Higinio',             'LW', 22, 64, 'ESP'),
        makePlayer(pid(), 'Edu Exposito',        'CM', 25, 67, 'ESP'),
        makePlayer(pid(), 'Alvaro Raton',        'RW', 24, 62, 'ESP'),
        makePlayer(pid(), 'Fer Nino',            'ST', 23, 63, 'ESP'),
        makePlayer(pid(), 'Javi Cueto',          'CM', 27, 62, 'ESP'),
        makePlayer(pid(), 'Ruben Castro',        'ST', 41, 65, 'ESP'),
        makePlayer(pid(), 'Jairo Izquierdo',     'LW', 25, 62, 'ECU'),
    ]},
    { id: 'rea',  name: 'Zaragoza',           short: 'ZAR', color: '#00529F', colorAlt: '#FFFFFF', prestige: 53, budget: Math.round(Math.pow(Math.max(0,53-40),2)*45000), stadium: 'La Romareda',                                       capacity: 34596, squad: [
        makePlayer(pid(), 'Cristian Alvarez',    'GK', 31, 68, 'ARG'),
        makePlayer(pid(), 'Raton',               'GK', 26, 62, 'ESP'),
        makePlayer(pid(), 'Jair',                'RB', 27, 66, 'ESP'),
        makePlayer(pid(), 'Frances',             'CB', 22, 66, 'ESP'),
        makePlayer(pid(), 'Alejandro Franquesa', 'CB', 30, 66, 'ESP'),
        makePlayer(pid(), 'Juan Gracia',         'LB', 26, 65, 'ESP'),
        makePlayer(pid(), 'Guti',                'CM', 23, 66, 'ESP'),
        makePlayer(pid(), 'Victor Mollejo',      'RW', 24, 66, 'ESP'),
        makePlayer(pid(), 'Sergio Bermejo',      'LW', 31, 66, 'ESP'),
        makePlayer(pid(), 'Luis Suarez',         'ST', 34, 69, 'ESP'),
        makePlayer(pid(), 'Alberto Zapater',     'CM', 36, 66, 'ESP'),
        makePlayer(pid(), 'Nieto',               'LB', 28, 64, 'ESP'),
        makePlayer(pid(), 'Borja Valle',         'LW', 31, 65, 'ESP'),
        makePlayer(pid(), 'Martin Bermudo',      'ST', 24, 64, 'ESP'),
        makePlayer(pid(), 'Aribo',               'CM', 27, 65, 'NGA'),
        makePlayer(pid(), 'Bermejo',             'CM', 31, 63, 'ESP'),
        makePlayer(pid(), 'Tomas Exposito',      'CM', 26, 65, 'ESP'),
    ]},
    { id: 'spo',  name: 'Sporting Gijon',     short: 'SPO', color: '#D0021B', colorAlt: '#FFFFFF', prestige: 51, budget: Math.round(Math.pow(Math.max(0,51-40),2)*45000), stadium: 'El Molinon',                                        capacity: 29029, squad: [
        makePlayer(pid(), 'Diego Marino',        'GK', 30, 65, 'ESP'),
        makePlayer(pid(), 'Ivan Cuellar',        'GK', 38, 64, 'ESP'),
        makePlayer(pid(), 'Pedro Diaz',          'RB', 27, 63, 'ESP'),
        makePlayer(pid(), 'Pablo Garcia',        'CB', 29, 64, 'ESP'),
        makePlayer(pid(), 'Jose Fontao',         'CB', 26, 62, 'ESP'),
        makePlayer(pid(), 'Guille Rosas',        'LB', 25, 62, 'ESP'),
        makePlayer(pid(), 'Gaspar Campos',       'CDM',27, 63, 'ESP'),
        makePlayer(pid(), 'Enric Gallego',       'ST', 34, 66, 'ESP'),
        makePlayer(pid(), 'Pablo Perez',         'CM', 28, 62, 'ESP'),
        makePlayer(pid(), 'Sergi Enrich',        'ST', 32, 65, 'ESP'),
        makePlayer(pid(), 'Jordan',              'CM', 29, 64, 'ESP'),
        makePlayer(pid(), 'Javi Rodriguez',      'RW', 25, 62, 'ESP'),
        makePlayer(pid(), 'Cristian Salvador',   'LW', 27, 62, 'ESP'),
        makePlayer(pid(), 'Camus',               'RB', 26, 63, 'ESP'),
        makePlayer(pid(), 'Djuka',               'ST', 29, 65, 'SRB'),
        makePlayer(pid(), 'Zarfino',             'CM', 28, 61, 'ESP'),
        makePlayer(pid(), 'Queijeiro',           'CM', 23, 61, 'ESP'),
    ]},
    { id: 'hue',  name: 'Huesca',             short: 'HUE', color: '#003087', colorAlt: '#FFFFFF', prestige: 50, budget: Math.round(Math.pow(Math.max(0,50-40),2)*45000), stadium: 'El Alcoraz',                                        capacity: 8000,  squad: [
        makePlayer(pid(), 'Alex Dominguez',      'GK', 29, 65, 'ESP'),
        makePlayer(pid(), 'Herrero',             'GK', 26, 61, 'ESP'),
        makePlayer(pid(), 'Pablo Maffeo',        'RB', 27, 70, 'ESP'),
        makePlayer(pid(), 'Carlos Neva',         'LB', 27, 65, 'ESP'),
        makePlayer(pid(), 'Jorge Pulido',        'CB', 31, 65, 'ESP'),
        makePlayer(pid(), 'Pedro Lopez',         'CB', 27, 63, 'ESP'),
        makePlayer(pid(), 'Blasco',              'LB', 25, 62, 'ESP'),
        makePlayer(pid(), 'Gaston Silva',        'CM', 30, 64, 'URU'),
        makePlayer(pid(), 'Dani Torres',         'CDM',27, 64, 'ESP'),
        makePlayer(pid(), 'Marc Cardona',        'ST', 27, 65, 'ESP'),
        makePlayer(pid(), 'Seoane',              'CM', 27, 63, 'ESP'),
        makePlayer(pid(), 'Okazaki',             'ST', 37, 64, 'JPN'),
        makePlayer(pid(), 'Vallejo',             'CB', 26, 64, 'ESP'),
        makePlayer(pid(), 'Lozano',              'RW', 24, 62, 'ESP'),
        makePlayer(pid(), 'Mouane',              'LW', 22, 62, 'SEN'),
        makePlayer(pid(), 'Juan Carlos',         'CM', 33, 63, 'ESP'),
        makePlayer(pid(), 'Escriche',            'ST', 25, 63, 'ESP'),
    ]},
    { id: 'ten',  name: 'Tenerife',           short: 'TEN', color: '#003180', colorAlt: '#FFFFFF', prestige: 51, budget: Math.round(Math.pow(Math.max(0,51-40),2)*45000), stadium: 'Heliodoro Rodriguez Lopez',                         capacity: 21892, squad: [
        makePlayer(pid(), 'Carlos Marin',        'GK', 30, 65, 'ESP'),
        makePlayer(pid(), 'Dani Hernandez',      'GK', 35, 64, 'ESP'),
        makePlayer(pid(), 'Aitor Sanz',          'CM', 32, 65, 'ESP'),
        makePlayer(pid(), 'Hector Moran',        'RB', 27, 63, 'ESP'),
        makePlayer(pid(), 'Alejandro Iturbe',    'CB', 29, 63, 'ESP'),
        makePlayer(pid(), 'Sergio Gonzalez',     'CB', 25, 62, 'ESP'),
        makePlayer(pid(), 'Javi Alonso',         'LB', 28, 63, 'ESP'),
        makePlayer(pid(), 'Shashoua',            'CM', 24, 64, 'ENG'),
        makePlayer(pid(), 'Ramon Folch',         'CDM',30, 64, 'ESP'),
        makePlayer(pid(), 'Elady',               'LW', 28, 66, 'ESP'),
        makePlayer(pid(), 'Larrea',              'CM', 27, 63, 'ESP'),
        makePlayer(pid(), 'Enric Gallego',       'ST', 33, 65, 'ESP'),
        makePlayer(pid(), 'Luismi',              'RW', 26, 63, 'ESP'),
        makePlayer(pid(), 'Juan Soriano',        'GK', 27, 64, 'ESP'),
        makePlayer(pid(), 'Ruiz de Galarreta',   'CM', 27, 64, 'ESP'),
        makePlayer(pid(), 'Carlos Bermejo',      'LW', 29, 63, 'ESP'),
        makePlayer(pid(), 'Jose Leon',           'LB', 26, 62, 'ESP'),
    ]},
    { id: 'mal',  name: 'Malaga',             short: 'MAL', color: '#003A6D', colorAlt: '#FFFFFF', prestige: 50, budget: Math.round(Math.pow(Math.max(0,50-40),2)*45000), stadium: 'La Rosaleda',                                       capacity: 30044, squad: [
        makePlayer(pid(), 'Dani Barrio',         'GK', 31, 65, 'ESP'),
        makePlayer(pid(), 'Alfonso Herrero',     'GK', 27, 62, 'ESP'),
        makePlayer(pid(), 'Pablo Chavarria',     'ST', 32, 65, 'ARG'),
        makePlayer(pid(), 'Juande',              'RB', 29, 63, 'ESP'),
        makePlayer(pid(), 'Juankar',             'LB', 32, 64, 'ESP'),
        makePlayer(pid(), 'Lomban',              'CB', 33, 63, 'ESP'),
        makePlayer(pid(), 'Luis Hernandez',      'CB', 37, 63, 'ESP'),
        makePlayer(pid(), 'Esteban Burgos',      'CM', 28, 63, 'ARG'),
        makePlayer(pid(), 'Alberto Escassi',     'CM', 29, 63, 'ESP'),
        makePlayer(pid(), 'Jairo',               'LW', 32, 63, 'ESP'),
        makePlayer(pid(), 'Roberto',             'CM', 33, 62, 'ESP'),
        makePlayer(pid(), 'Larrea',              'RW', 26, 63, 'ESP'),
        makePlayer(pid(), 'Benkhemassa',         'LW', 28, 63, 'MAR'),
        makePlayer(pid(), 'Genaro',              'ST', 30, 62, 'ARG'),
        makePlayer(pid(), 'Julio Gracia',        'LB', 34, 62, 'ESP'),
        makePlayer(pid(), 'Manu Molina',         'CM', 22, 63, 'ESP'),
        makePlayer(pid(), 'Jorge Villafana',     'LB', 32, 61, 'MEX'),
    ]},
    { id: 'alb',  name: 'Albacete',           short: 'ALB', color: '#FFD700', colorAlt: '#003DA5', prestige: 48, budget: Math.round(Math.pow(Math.max(0,48-40),2)*45000), stadium: 'Carlos Belmonte',                                   capacity: 17000, squad: [
        makePlayer(pid(), 'Bernabe Barragan',    'GK', 28, 62, 'ESP'),
        makePlayer(pid(), 'Tomeu Nadal',         'GK', 34, 61, 'ESP'),
        makePlayer(pid(), 'Quiles',              'RB', 27, 60, 'ESP'),
        makePlayer(pid(), 'Ruben Fuentes',       'CB', 29, 60, 'ESP'),
        makePlayer(pid(), 'Pere Milla',          'LW', 28, 62, 'ESP'),
        makePlayer(pid(), 'Boyomo',              'CB', 27, 60, 'CMR'),
        makePlayer(pid(), 'Jose Villar',         'LB', 26, 59, 'ESP'),
        makePlayer(pid(), 'Acuna',               'CM', 31, 61, 'ESP'),
        makePlayer(pid(), 'Javi Ros',            'CDM',29, 61, 'ESP'),
        makePlayer(pid(), 'Djetei',              'RB', 25, 60, 'GUI'),
        makePlayer(pid(), 'Zozulia',             'ST', 34, 62, 'UKR'),
        makePlayer(pid(), 'Fuster',              'CM', 28, 60, 'ESP'),
        makePlayer(pid(), 'Dani Ojeda',          'LW', 29, 61, 'ESP'),
        makePlayer(pid(), 'Rober Ibanez',        'ST', 27, 60, 'ESP'),
        makePlayer(pid(), 'Inaki',               'CM', 24, 59, 'ESP'),
        makePlayer(pid(), 'Tano Bonmaison',      'LB', 26, 58, 'ARG'),
        makePlayer(pid(), 'Hector Hernandez',    'ST', 25, 59, 'ESP'),
    ]},
    { id: 'bur',  name: 'Burgos',             short: 'BUR', color: '#CC0000', colorAlt: '#FFFFFF', prestige: 47, budget: Math.round(Math.pow(Math.max(0,47-40),2)*45000), stadium: 'El Plantio',                                        capacity: 9000,  squad: [
        makePlayer(pid(), 'Mario Ortega',        'GK', 29, 61, 'ESP'),
        makePlayer(pid(), 'Cifuentes',           'GK', 25, 58, 'ESP'),
        makePlayer(pid(), 'Eneko',               'RB', 27, 60, 'ESP'),
        makePlayer(pid(), 'Raul Garcia',         'CB', 28, 60, 'ESP'),
        makePlayer(pid(), 'Javi Bonilla',        'CB', 29, 59, 'ESP'),
        makePlayer(pid(), 'Pep Biel',            'LW', 27, 62, 'ESP'),
        makePlayer(pid(), 'Guillermo',           'LB', 26, 59, 'ESP'),
        makePlayer(pid(), 'David Vecino',        'CDM',28, 60, 'ESP'),
        makePlayer(pid(), 'Curro Sanchez',       'CM', 30, 59, 'ESP'),
        makePlayer(pid(), 'Manu Garcia',         'RW', 27, 60, 'ESP'),
        makePlayer(pid(), 'Nonon',               'ST', 29, 61, 'ESP'),
        makePlayer(pid(), 'Cristian Carracedo',  'LW', 26, 59, 'ESP'),
        makePlayer(pid(), 'Aaron Sanabria',      'ST', 24, 59, 'ESP'),
        makePlayer(pid(), 'Pedro Alcala',        'CB', 31, 59, 'ESP'),
        makePlayer(pid(), 'Alberto Benito',      'CM', 26, 58, 'ESP'),
        makePlayer(pid(), 'Rolivi',              'CM', 28, 58, 'ESP'),
        makePlayer(pid(), 'Borja Gonzalez',      'ST', 26, 58, 'ESP'),
    ]},
    { id: 'mir',  name: 'Mirandes',           short: 'MIR', color: '#B22222', colorAlt: '#FFFFFF', prestige: 47, budget: Math.round(Math.pow(Math.max(0,47-40),2)*45000), stadium: 'Estadio Municipal de Anduva',                       capacity: 5800,  squad: [
        makePlayer(pid(), 'Oier Olazabal',       'GK', 31, 61, 'ESP'),
        makePlayer(pid(), 'Sergio Garcia',       'GK', 26, 57, 'ESP'),
        makePlayer(pid(), 'Unai Dufur',          'RB', 25, 59, 'ESP'),
        makePlayer(pid(), 'Sergio Herrero',      'CB', 28, 59, 'ESP'),
        makePlayer(pid(), 'Pablo Campos',        'CB', 27, 58, 'ESP'),
        makePlayer(pid(), 'Eric Lopez',          'LB', 25, 58, 'ESP'),
        makePlayer(pid(), 'Ander Robles',        'CM', 24, 61, 'ESP'),
        makePlayer(pid(), 'Borja Diaz',          'CDM',28, 59, 'ESP'),
        makePlayer(pid(), 'Inigo Vicente',       'CM', 25, 63, 'ESP'),
        makePlayer(pid(), 'Joseba Garcia',       'LW', 26, 59, 'ESP'),
        makePlayer(pid(), 'Cayo Quintana',       'ST', 24, 61, 'ESP'),
        makePlayer(pid(), 'Alex Larrea',         'RW', 23, 59, 'ESP'),
        makePlayer(pid(), 'Mikel Merino',        'CB', 30, 58, 'ESP'),
        makePlayer(pid(), 'Samu Saiz',           'CM', 32, 61, 'ESP'),
        makePlayer(pid(), 'Alvaro Melendez',     'ST', 25, 58, 'ESP'),
        makePlayer(pid(), 'Lope Gurdiel',        'LB', 26, 57, 'ESP'),
        makePlayer(pid(), 'Iker Alegre',         'CM', 21, 58, 'ESP'),
    ]},
    { id: 'car',  name: 'Cartagena',          short: 'CAR', color: '#C8102E', colorAlt: '#FFFFFF', prestige: 48, budget: Math.round(Math.pow(Math.max(0,48-40),2)*45000), stadium: 'Estadio Cartagonova',                               capacity: 13000, squad: [
        makePlayer(pid(), 'Marc Martinez',       'GK', 29, 62, 'ESP'),
        makePlayer(pid(), 'Andres Prieto',       'GK', 35, 61, 'ESP'),
        makePlayer(pid(), 'Jose Rueda',          'RB', 27, 60, 'ESP'),
        makePlayer(pid(), 'Chema Nunez',         'CB', 29, 61, 'ESP'),
        makePlayer(pid(), 'Datkali',             'CB', 26, 60, 'GNB'),
        makePlayer(pid(), 'Gaston Alvarez',      'LB', 24, 60, 'URU'),
        makePlayer(pid(), 'Alfredo Ortuno',      'ST', 33, 62, 'ESP'),
        makePlayer(pid(), 'Elady',               'LW', 28, 62, 'ESP'),
        makePlayer(pid(), 'Damian',              'CM', 28, 60, 'ESP'),
        makePlayer(pid(), 'Casto',               'GK', 37, 60, 'ESP'),
        makePlayer(pid(), 'Carlos David',        'CDM',29, 60, 'ESP'),
        makePlayer(pid(), 'Lemi',                'CM', 27, 59, 'SEN'),
        makePlayer(pid(), 'Albarran',            'LB', 25, 59, 'ESP'),
        makePlayer(pid(), 'Pablo De Blasis',     'CM', 33, 61, 'ARG'),
        makePlayer(pid(), 'Owusu',               'LW', 26, 60, 'GHA'),
        makePlayer(pid(), 'Ruben Cruz',          'ST', 28, 59, 'ESP'),
        makePlayer(pid(), 'Sillero',             'RW', 23, 58, 'ESP'),
    ]},
    { id: 'elc',  name: 'Elche',              short: 'ELC', color: '#006400', colorAlt: '#FFFFFF', prestige: 50, budget: Math.round(Math.pow(Math.max(0,50-40),2)*45000), stadium: 'Martinez Valero',                                   capacity: 33732, squad: [
        makePlayer(pid(), 'Edgar Badia',         'GK', 29, 66, 'ESP'),
        makePlayer(pid(), 'Adan',                'GK', 35, 64, 'ESP'),
        makePlayer(pid(), 'Pedro Bigas',         'CB', 30, 64, 'ESP'),
        makePlayer(pid(), 'Diego Gonzalez',      'CB', 26, 63, 'ESP'),
        makePlayer(pid(), 'Josema',              'RB', 30, 62, 'ESP'),
        makePlayer(pid(), 'Tete Morente',        'LW', 27, 66, 'ESP'),
        makePlayer(pid(), 'Guti',                'LB', 26, 62, 'ESP'),
        makePlayer(pid(), 'Dani Calvo',          'CB', 31, 63, 'ESP'),
        makePlayer(pid(), 'Pere Milla',          'RW', 28, 64, 'ESP'),
        makePlayer(pid(), 'Ivan Marcone',        'CDM',34, 63, 'ARG'),
        makePlayer(pid(), 'Fidel',               'LW', 31, 64, 'ESP'),
        makePlayer(pid(), 'Lucas Boye',          'ST', 26, 65, 'ARG'),
        makePlayer(pid(), 'Josan',               'CM', 26, 62, 'ESP'),
        makePlayer(pid(), 'Lautaro Blanco',      'LB', 27, 62, 'ARG'),
        makePlayer(pid(), 'Raul Guti',           'CM', 28, 61, 'ESP'),
        makePlayer(pid(), 'Emiliano Rigoni',     'RW', 30, 63, 'ARG'),
        makePlayer(pid(), 'Benedetto',           'ST', 33, 63, 'ARG'),
    ]},
    { id: 'ovi',  name: 'Oviedo',             short: 'OVI', color: '#003F8C', colorAlt: '#FFFFFF', prestige: 51, budget: Math.round(Math.pow(Math.max(0,51-40),2)*45000), stadium: 'Carlos Tartiere',                                   capacity: 22000, squad: [
        makePlayer(pid(), 'Axel Werner',         'GK', 23, 64, 'ARG'),
        makePlayer(pid(), 'Alfonso',             'GK', 32, 63, 'ESP'),
        makePlayer(pid(), 'Carlos Hernandez',    'RB', 28, 63, 'ESP'),
        makePlayer(pid(), 'Costas',              'CB', 30, 63, 'ESP'),
        makePlayer(pid(), 'Nieto',               'CB', 27, 62, 'ESP'),
        makePlayer(pid(), 'Calero',              'LB', 26, 63, 'ESP'),
        makePlayer(pid(), 'Borja Baston',        'ST', 31, 65, 'ESP'),
        makePlayer(pid(), 'Mossa',               'LW', 27, 63, 'ESP'),
        makePlayer(pid(), 'Marco Sangalli',      'CM', 26, 63, 'ITA'),
        makePlayer(pid(), 'Brayan Cortes',       'GK', 27, 63, 'COL'),
        makePlayer(pid(), 'Stevie Mallan',       'CM', 29, 62, 'SCO'),
        makePlayer(pid(), 'Javi Mier',           'CDM',23, 63, 'ESP'),
        makePlayer(pid(), 'Joel Armini',         'CB', 22, 63, 'ESP'),
        makePlayer(pid(), 'Lucas Ahijado',       'LW', 22, 61, 'ESP'),
        makePlayer(pid(), 'David Costas',        'CM', 29, 62, 'ESP'),
        makePlayer(pid(), 'Cazorla',             'CM', 39, 64, 'ESP'),
        makePlayer(pid(), 'Viti',                'RW', 23, 62, 'ESP'),
    ]},
    { id: 'cor',  name: 'Cordoba',            short: 'COR', color: '#007A33', colorAlt: '#FFFFFF', prestige: 46, budget: Math.round(Math.pow(Math.max(0,46-40),2)*45000), stadium: 'Nuevo Arcangel',                                    capacity: 20989, squad: [
        makePlayer(pid(), 'Carlos Marin',        'GK', 30, 60, 'ESP'),
        makePlayer(pid(), 'Edu Frias',           'GK', 26, 57, 'ESP'),
        makePlayer(pid(), 'Ekaitz Arrondo',      'RB', 25, 58, 'ESP'),
        makePlayer(pid(), 'Bernardo Cruz',       'CB', 30, 59, 'ESP'),
        makePlayer(pid(), 'Dragisa Gudelj',      'CB', 30, 59, 'SRB'),
        makePlayer(pid(), 'Kike Marquez',        'LB', 28, 58, 'ESP'),
        makePlayer(pid(), 'Jacobo Muniz',        'CM', 25, 60, 'ESP'),
        makePlayer(pid(), 'Edu Carbonell',       'CM', 28, 58, 'ESP'),
        makePlayer(pid(), 'Antonio Casas',       'ST', 24, 61, 'ESP'),
        makePlayer(pid(), 'Simo',                'LW', 28, 59, 'MAR'),
        makePlayer(pid(), 'Carlos Puga',         'RW', 27, 58, 'ESP'),
        makePlayer(pid(), 'Willy Ledesma',       'ST', 36, 61, 'ESP'),
        makePlayer(pid(), 'Julian Barcenas',     'LW', 25, 59, 'ESP'),
        makePlayer(pid(), 'Luismi',              'CDM',28, 57, 'ESP'),
        makePlayer(pid(), 'Adilson Goiano',      'CB', 26, 57, 'BRA'),
        makePlayer(pid(), 'Karim Azamoum',       'CM', 23, 57, 'MAR'),
        makePlayer(pid(), 'Owusu',               'RW', 27, 57, 'GHA'),
    ]},
    { id: 'cas',  name: 'Castellon',          short: 'CAS', color: '#003DA5', colorAlt: '#FFFFFF', prestige: 46, budget: Math.round(Math.pow(Math.max(0,46-40),2)*45000), stadium: 'Estadio Castalia',                                  capacity: 15400, squad: [
        makePlayer(pid(), 'Jaime Garrido',       'GK', 28, 60, 'ESP'),
        makePlayer(pid(), 'Alvaro Gonzalez',     'GK', 25, 56, 'ESP'),
        makePlayer(pid(), 'Iturra',              'RB', 28, 58, 'ESP'),
        makePlayer(pid(), 'Samu Leal',           'CB', 27, 58, 'ESP'),
        makePlayer(pid(), 'Esteban',             'CB', 29, 58, 'ARG'),
        makePlayer(pid(), 'Jorge Pascual',       'LB', 26, 57, 'ESP'),
        makePlayer(pid(), 'Javi Castellano',     'CM', 27, 59, 'ESP'),
        makePlayer(pid(), 'Isi',                 'RW', 26, 59, 'ESP'),
        makePlayer(pid(), 'Alex Lorenzo',        'CDM',25, 57, 'ESP'),
        makePlayer(pid(), 'Ruymon Lemes',        'ST', 28, 59, 'ESP'),
        makePlayer(pid(), 'Carlos Ramos',        'LW', 24, 57, 'ESP'),
        makePlayer(pid(), 'Aridane Hernandez',   'CB', 33, 59, 'ESP'),
        makePlayer(pid(), 'Fran Villalba',       'CM', 25, 60, 'ESP'),
        makePlayer(pid(), 'Hugo Simon',          'CM', 24, 57, 'ESP'),
        makePlayer(pid(), 'Pep Chavarria',       'ST', 26, 57, 'ESP'),
        makePlayer(pid(), 'Alex Millan',         'RW', 22, 56, 'ESP'),
        makePlayer(pid(), 'Juanma Soria',        'LB', 29, 56, 'ESP'),
    ]},
    { id: 'amo',  name: 'Amorebieta',         short: 'AMO', color: '#0052A5', colorAlt: '#FFFFFF', prestige: 43, budget: Math.round(Math.pow(Math.max(0,43-40),2)*45000), stadium: 'Campo Urritxe',                                     capacity: 2800,  squad: [
        makePlayer(pid(), 'Julen Agirre',        'GK', 28, 57, 'ESP'),
        makePlayer(pid(), 'Iker Onaindia',       'GK', 24, 53, 'ESP'),
        makePlayer(pid(), 'Unai Llarena',        'RB', 26, 55, 'ESP'),
        makePlayer(pid(), 'Ander Albizua',       'CB', 29, 55, 'ESP'),
        makePlayer(pid(), 'Aitor Guridi',        'CB', 28, 54, 'ESP'),
        makePlayer(pid(), 'Mikel Larzabal',      'LB', 25, 54, 'ESP'),
        makePlayer(pid(), 'Mikel Villalibre',    'CM', 24, 55, 'ESP'),
        makePlayer(pid(), 'Pablo Valcarce',      'CDM',27, 54, 'ESP'),
        makePlayer(pid(), 'Arkaitz Ruiz',        'CM', 26, 54, 'ESP'),
        makePlayer(pid(), 'Ander Gayoso',        'LW', 23, 55, 'ESP'),
        makePlayer(pid(), 'Jon Ander Garrido',   'ST', 27, 55, 'ESP'),
        makePlayer(pid(), 'Aitor Llanos',        'RW', 25, 54, 'ESP'),
        makePlayer(pid(), 'Josu Etxeberria',     'ST', 30, 54, 'ESP'),
        makePlayer(pid(), 'Asier Eraso',         'CM', 29, 54, 'ESP'),
        makePlayer(pid(), 'Unai Larrea',         'LB', 22, 53, 'ESP'),
        makePlayer(pid(), 'Andoni Zubikarai',    'RB', 26, 53, 'ESP'),
        makePlayer(pid(), 'Inigo Eguaras',       'CM', 24, 53, 'ESP'),
    ]},
    { id: 'fer',  name: 'Ferrol',             short: 'FER', color: '#003DA5', colorAlt: '#FFFFFF', prestige: 43, budget: Math.round(Math.pow(Math.max(0,43-40),2)*45000), stadium: 'O Inferniño',                                       capacity: 5500,  squad: [
        makePlayer(pid(), 'Tomas Mejias',        'GK', 33, 57, 'ESP'),
        makePlayer(pid(), 'Marcos Dorado',       'GK', 25, 52, 'ESP'),
        makePlayer(pid(), 'Fran Manzanara',      'RB', 27, 54, 'ESP'),
        makePlayer(pid(), 'Jose Carlos',         'CB', 29, 55, 'ESP'),
        makePlayer(pid(), 'Bello',               'CB', 26, 54, 'ESP'),
        makePlayer(pid(), 'Alvaro Gimenez',      'LB', 28, 53, 'ESP'),
        makePlayer(pid(), 'Mikel Villanueva',    'CM', 26, 55, 'ESP'),
        makePlayer(pid(), 'Dani Lopez',          'CDM',28, 54, 'ESP'),
        makePlayer(pid(), 'Cris Montes',         'CM', 25, 54, 'ESP'),
        makePlayer(pid(), 'Javi Fernandez',      'RW', 27, 55, 'ESP'),
        makePlayer(pid(), 'Sergi Sala',          'LW', 26, 54, 'ESP'),
        makePlayer(pid(), 'Noel Lopez',          'ST', 25, 55, 'ESP'),
        makePlayer(pid(), 'Pablo Arbelo',        'ST', 27, 53, 'ESP'),
        makePlayer(pid(), 'Aaron Sanabria',      'RW', 29, 54, 'ESP'),
        makePlayer(pid(), 'Isma Ruiz',           'LB', 24, 53, 'ESP'),
        makePlayer(pid(), 'Rafa Sanchez',        'CB', 26, 52, 'ESP'),
        makePlayer(pid(), 'Jonatan Gomez',       'ST', 28, 52, 'ESP'),
    ]},
    { id: 'eld',  name: 'Eldense',            short: 'ELD', color: '#CF0000', colorAlt: '#FFFFFF', prestige: 42, budget: Math.round(Math.pow(Math.max(0,42-40),2)*45000), stadium: 'Estadio Nuevo Pepico Amat',                         capacity: 5500,  squad: [
        makePlayer(pid(), 'Israel Puerto',       'GK', 29, 56, 'ESP'),
        makePlayer(pid(), 'Lucas Cantero',       'GK', 25, 51, 'ESP'),
        makePlayer(pid(), 'Sergi Tomas',         'RB', 26, 53, 'ESP'),
        makePlayer(pid(), 'Raul Grego',          'CB', 28, 53, 'ESP'),
        makePlayer(pid(), 'Carlos Cots',         'CB', 27, 52, 'ESP'),
        makePlayer(pid(), 'Pedro Alcala',        'LB', 27, 52, 'ESP'),
        makePlayer(pid(), 'Fede Vico',           'CM', 29, 55, 'ESP'),
        makePlayer(pid(), 'Pablo Gozalbez',      'CDM',28, 53, 'ESP'),
        makePlayer(pid(), 'Marco Gonzalez',      'CM', 25, 52, 'ESP'),
        makePlayer(pid(), 'Oscar Aranda',        'LW', 26, 54, 'ESP'),
        makePlayer(pid(), 'David Ballester',     'RW', 27, 53, 'ESP'),
        makePlayer(pid(), 'Juanmi',              'ST', 31, 54, 'ESP'),
        makePlayer(pid(), 'Gerardo Morales',     'ST', 26, 52, 'ESP'),
        makePlayer(pid(), 'Fabian Sanchez',      'CM', 24, 52, 'ESP'),
        makePlayer(pid(), 'Berni',               'LB', 30, 51, 'ESP'),
        makePlayer(pid(), 'Alberto Giner',       'RB', 25, 51, 'ESP'),
        makePlayer(pid(), 'Jorge Morato',        'ST', 23, 51, 'ESP'),
    ]},
    { id: 'and',  name: 'Andorra FC',         short: 'AND', color: '#CF0000', colorAlt: '#FFFF00', prestige: 42, budget: Math.round(Math.pow(Math.max(0,42-40),2)*45000), stadium: 'Estadi Nacional',                                   capacity: 3306,  squad: [
        makePlayer(pid(), 'Gazzaniga II',        'GK', 28, 56, 'AND'),
        makePlayer(pid(), 'Marc Vales',          'GK', 25, 51, 'AND'),
        makePlayer(pid(), 'Carlos Martinez',     'RB', 27, 53, 'ESP'),
        makePlayer(pid(), 'Ildefons Lima',       'CB', 42, 55, 'AND'),
        makePlayer(pid(), 'Marc Pujol',          'CB', 27, 52, 'AND'),
        makePlayer(pid(), 'Moises San Nicolas',  'LB', 26, 52, 'ESP'),
        makePlayer(pid(), 'Marc Rebes',          'CM', 25, 54, 'ESP'),
        makePlayer(pid(), 'Alex Martinez',       'CDM',27, 53, 'AND'),
        makePlayer(pid(), 'Clofent',             'CM', 26, 52, 'ESP'),
        makePlayer(pid(), 'Javi Riera',          'LW', 28, 54, 'ESP'),
        makePlayer(pid(), 'Cristian Martinez',   'RW', 25, 53, 'ESP'),
        makePlayer(pid(), 'Victor Bernat',       'ST', 27, 54, 'AND'),
        makePlayer(pid(), 'Andres Prieto',       'ST', 29, 52, 'ESP'),
        makePlayer(pid(), 'Alex Fores',          'CM', 24, 52, 'ESP'),
        makePlayer(pid(), 'Miquel Vidal',        'LB', 26, 51, 'ESP'),
        makePlayer(pid(), 'Bongo',               'CB', 29, 51, 'CPV'),
        makePlayer(pid(), 'Pau Perez',           'ST', 22, 51, 'ESP'),
    ]},
];

LA_LIGA_TEAMS.forEach(t => { ALL_TEAMS.push(t); TEAM_MAP[t.id] = t; });
LA_LIGA2_TEAMS.forEach(t => { ALL_TEAMS.push(t); TEAM_MAP[t.id] = t; });

LEAGUES['la_liga'] = {
    id: 'la_liga',
    name: 'La Liga',
    country: 'spain',
    tier: 1,
    teams: LA_LIGA_TEAMS.map(t => t.id),
    relegationSpots: 3,
    promotionSpots: 0,
    promotionPlayoff: 0,
};

LEAGUES['la_liga2'] = {
    id: 'la_liga2',
    name: 'La Liga 2',
    country: 'spain',
    tier: 2,
    teams: LA_LIGA2_TEAMS.map(t => t.id),
    relegationSpots: 4,
    promotionSpots: 2,
    promotionPlayoff: 4,
};
